In [1]:
# MPAGE Package Testing
# This notebook demonstrates basic functionality of the MPAGE package

# Load the package
devtools::load_all()

ℹ Loading MPAGE

In [2]:
rna_mod_proteins <- get_rna_mod_proteins()
rna_mod_proteins

   gene_symbol modification_type functional_role
1  ADAR        A-to-I editing    writer
2  ADARB1      A-to-I editing    writer
3  ADARB2      A-to-I editing    writer
4  NAT10       ac4C              writer
5  ALKBH3      m1A               eraser
6  ALKBH7      m1A               eraser
7  RRP8        m1A               writer
8  TRMT10B     m1A               writer
9  TRMT10C     m1A               writer
10 TRMT6       m1A               writer
11 TRMT61A     m1A               writer
12 TRMT61B     m1A               writer
13 YTHDC1      m1A, m6A          reader
14 YTHDF1      m1A, m6A          reader
15 YTHDF2      m1A, m6A, m5C     reader
16 ALKBH1      m1A,m5C           eraser
17 YTHDF3      m1A,m6A           reader
18 FTO         m1A,m6A,m6Am      eraser
19 TET1        m5C               eraser
20 TET2        m5C               eraser
21 TET3        m5C               eraser
22 ALYREF      m5C               reader
23 RAD52       m5C               reader
24 SRSF2       m5C               reader
25 YBX1        m5C               reader
26 YBX2        m5C               reader
27 DNMT1       m5C               writer
28 DNMT3A      m5C               writer
29 DNMT3B      m5C               writer
30 NOP2        m5C               writer
⋮  ⋮           ⋮                 ⋮
56 VIRMA       m6A               writer
57 WTAP        m6A               writer
58 ZC3H13      m6A               writer
59 ZCCHC4      m6A               writer
60 FMR1        m6A, m5C          reader
61 IGF2BP3     m6A, m7G          reader
62 PCF11       m6Am              reader
63 METTL4      m6Am              writer
64 PCIF1       m6Am              writer
65 EIF4E       m7G               reader
66 NCBP1       m7G               reader
67 NCBP2       m7G               reader
68 QKI         m7G               reader
69 BUD23       m7G               writer
70 METTL1      m7G               writer
71 RNMT        m7G               writer
72 TRMT112     m7G               writer
73 WDR4        m7G               writer
74 DKC1        Ψ                 writer
75 PUS1        Ψ                 writer
76 PUS10       Ψ                 writer
77 PUS3        Ψ                 writer
78 PUS7        Ψ                 writer
79 PUS7L       Ψ                 writer
80 RPUSD1      Ψ                 writer
81 RPUSD2      Ψ                 writer
82 RPUSD3      Ψ                 writer
83 RPUSD4      Ψ                 writer
84 TRUB1       Ψ                 writer
85 TRUB2       Ψ                 writer

In [3]:
networkds <- build_ppi_network()
merged_networks <- merge_ppi_networks(networkds, merge_method = "union", add_source_labels = TRUE)

Processing STRING database...

STRING Network Summary:

Processed 6857702 unique interactions

Unique proteins: 19622

Nodes: 16185
Edges: 236000
Average degree: 29.16281

Processing BIOGRID database...

BIOGRID Network Summary:

Processed 976169 unique interactions

Unique proteins: 20334

Nodes: 20169
Edges: 959426
Average degree: 95.13868

Processing INTACT database...

INTACT Network Summary:

Processed 606332 unique interactions

Unique proteins: 18416

Nodes: 5597
Edges: 20870
Average degree: 7.457567

Merging 3 networks using method: union

=== Merged Network Summary ===
Data sources: string, biogrid, intact
Merge method: union
Total nodes: 21604
Total edges: 1079304
Network density: 0.0046
Average degree: 99.92

=== Source Contribution ===

biogrid  intact  string
 904639   11187  236000

Interactions from multiple sources: 66409 (6.2%)

In [4]:
sub_modules <- identify_modules_iterative(merged_networks,
    min_module_size = 9,
    max_module_size = 85,
    target_proteins = rna_mod_proteins$gene_symbol
)

Identified 42 modules containing target proteins

Total target proteins covered: 77

In [ ]:
library(dplyr)

Attaching package: ‘dplyr’


The following object is masked from ‘package:MPAGE’:

    as_data_frame


The following object is masked from ‘package:testthat’:

    matches


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [8]:
read.csv("data-raw/rmp.tsv", sep = "\t") %>%
    full_join(rna_mod_proteins, by = c("Gene.name" = "gene_symbol")) %>%
    write.table("data-raw/rmp_all.tsv", sep = "\t", quote = FALSE)

Warning message in full_join(., rna_mod_proteins, by = c(Gene.name = "gene_symbol")):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 16 of `x` matches multiple rows in `y`.
ℹ Row 17 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

In [17]:
read.csv("data-raw/rmp_all.tsv", sep = "\t", ) %>%
    dplyr::select(Gene.name, RNA.modification.type, Protein.class) %>%
    dplyr::rename(gene_symbol = Gene.name, modification_type = RNA.modification.type, functional_role = Protein.class) %>%
    arrange(modification_type, functional_role, gene_symbol) %>%
    saveRDS("inst/extdata/rnamod_proteins.rds")

In [14]:
rna_mod_proteins

   gene_symbol modification_type functional_role
1  ADAR        A-to-I editing    writer
2  ADARB1      A-to-I editing    writer
3  ADARB2      A-to-I editing    writer
4  NAT10       ac4C              writer
5  ALKBH3      m1A               eraser
6  ALKBH7      m1A               eraser
7  RRP8        m1A               writer
8  TRMT10B     m1A               writer
9  TRMT10C     m1A               writer
10 TRMT6       m1A               writer
11 TRMT61A     m1A               writer
12 TRMT61B     m1A               writer
13 YTHDC1      m1A, m6A          reader
14 YTHDF1      m1A, m6A          reader
15 YTHDF2      m1A, m6A, m5C     reader
16 ALKBH1      m1A,m5C           eraser
17 YTHDF3      m1A,m6A           reader
18 FTO         m1A,m6A,m6Am      eraser
19 TET1        m5C               eraser
20 TET2        m5C               eraser
21 TET3        m5C               eraser
22 ALYREF      m5C               reader
23 RAD52       m5C               reader
24 SRSF2       m5C               reader
25 YBX1        m5C               reader
26 YBX2        m5C               reader
27 DNMT1       m5C               writer
28 DNMT3A      m5C               writer
29 DNMT3B      m5C               writer
30 NOP2        m5C               writer
⋮  ⋮           ⋮                 ⋮
57 WTAP        m6A               writer
58 ZC3H13      m6A               writer
59 ZCCHC4      m6A               writer
60 FMR1        m6A, m5C          reader
61 IGF2BP3     m6A, m7G          reader
62 PCF11       m6Am              reader
63 METTL4      m6Am              writer
64 PCIF1       m6Am              writer
65 CBC         m7G               reader
66 EIF4E       m7G               reader
67 NCBP1       m7G               reader
68 NCBP2       m7G               reader
69 QKI         m7G               reader
70 BUD23       m7G               writer
71 METTL1      m7G               writer
72 RNMT        m7G               writer
73 TRMT112     m7G               writer
74 WDR4        m7G               writer
75 DKC1        Ψ                 writer
76 PUS1        Ψ                 writer
77 PUS10       Ψ                 writer
78 PUS3        Ψ                 writer
79 PUS7        Ψ                 writer
80 PUS7L       Ψ                 writer
81 RPUSD1      Ψ                 writer
82 RPUSD2      Ψ                 writer
83 RPUSD3      Ψ                 writer
84 RPUSD4      Ψ                 writer
85 TRUB1       Ψ                 writer
86 TRUB2       Ψ                 writer

In [6]:
names(sub_modules) <- paste0("Module_", 1:length(sub_modules))

In [8]:
sub_modules

[[1]]
[[1]]$module_id
[1] "RC4_1"

[[1]]$genes
 [1] "ALKBH2"    "ALKBH4"    "ALKBH6"    "ALKBH7"    "ALKBH8"    "ASPG"
 [7] "C20ORF85"  "CCDC24"    "FAM166B"   "FTO"       "GPANK1"    "HRASLS"
[13] "HSF4"      "INSC"      "KRTAP19-6" "MISP"      "MORN3"     "MYOZ3"
[19] "OIP5"      "PRR5L"     "RIBC1"     "RUSC1"     "TEKT3"     "TEKT4"
[25] "TTC19"     "WBSCR27"   "ZMYND12"   "ZNF77"

[[1]]$size
[1] 28

[[1]]$algorithm
[1] "FASTGREEDY"

[[1]]$depth
[1] 4

[[1]]$target_proteins
[1] "ALKBH7" "FTO"


[[2]]
[[2]]$module_id
[1] "RC5_1"

[[2]]$genes
 [1] "ABCD1"    "ACAD10"   "ACSL1"    "AGPAT5"   "APLNR"    "AQP3"
 [7] "BDH1"     "BRINP2"   "C4ORF29"  "CMTM8"    "CYBA"     "FASTKD1"
[13] "GK"       "KIAA0368" "KIAA1586" "MAGEA8"   "MAS1"     "MTX1"
[19] "NSUN3"    "OSTM1"    "PTH2R"    "RAMP2"    "SFXN5"    "SLC25A30"
[25] "SLC25A35" "SLC2A12"  "TMIGD3"   "VSIG4"

[[2]]$size
[1] 28

[[2]]$algorithm
[1] "FASTGREEDY"

[[2]]$depth
[1] 5

[[2]]$target_proteins
[1] "NSUN3"


[[3]]
[[3]]$module_id
[1] "RC3_1"

[[3]]$genes
 [1] "ABCB7"        "ADCK4"        "AFG3L2"       "ARMT1"        "ATAD3B"
 [6] "ATP5B"        "ATP5E"        "ATP5F1"       "ATP5H"        "ATP5J"
[11] "ATP5O"        "BCS1L"        "C17ORF80"     "C17ORF89"     "C19ORF52"
[16] "C7ORF55"      "C8ORF82"      "CCDC109B"     "CCDC90B"      "CISD3"
[21] "CLPB"         "CMAS"         "COX15"        "DNAJA3"       "DNAJC15"
[26] "DNAJC19"      "DNAJC28"      "DNAJC4"       "E7ENQ6_HUMAN" "ECSIT"
[31] "EXD2"         "GFY"          "GRPEL2"       "HEATR4"       "HSPA9"
[36] "IGSF22"       "LETM1"        "LOC440570"    "LONP1"        "LRPPRC"
[41] "MCU"          "MCUR1"        "MRPS26"       "ND4"          "NDUFA12"
[46] "NDUFA2"       "NDUFA5"       "NDUFA6"       "NDUFA7"       "NDUFA9"
[51] "NDUFAF1"      "NDUFAF2"      "NDUFAF3"      "NDUFAF4"      "NDUFAF6"
[56] "NDUFS1"       "NDUFS4"       "NDUFS7"       "NDUFV3"       "NIPSNAP1"
[61] "NNT"          "ODF3L1"       "OTC"          "PAM16"        "PARL"
[66] "PMPCB"        "PTAR1"        "PTPMT1"       "PYCR2"        "RMND1"
[71] "RPUSD3"       "SLC25A51"     "SLC30A9"      "SLC36A1"      "SLIRP"
[76] "SP6"          "STOML2"       "SURF1"        "TACO1"        "TIMM44"
[81] "TMEM70"       "VWA8"         "PMS2CL"       "RD3L"

[[3]]$size
[1] 84

[[3]]$algorithm
[1] "FASTGREEDY"

[[3]]$depth
[1] 3

[[3]]$target_proteins
[1] "LRPPRC" "RPUSD3"


[[4]]
[[4]]$module_id
[1] "RC4_1"

[[4]]$genes
 [1] "ANGEL2"       "ATP5J2-PTCD1" "ATPAF1"       "BCL2L12"      "C10ORF2"
 [6] "C20ORF96"     "C6ORF203"     "ERAL1"        "KIAA0391"     "MGME1"
[11] "MTERF3"       "MTIF3"        "PNPLA8"       "POLG"         "POLRMT"
[16] "TFAM"         "TRUB2"        "TWNK"

[[4]]$size
[1] 18

[[4]]$algorithm
[1] "FASTGREEDY"

[[4]]$depth
[1] 4

[[4]]$target_proteins
[1] "TRUB2"


[[5]]
[[5]]$module_id
[1] "RC4_2"

[[5]]$genes
 [1] "ALAS1"          "C1ORF220"       "C7ORF55-LUC7L2" "DNLZ"
 [5] "EEF1AKMT3"      "GSTT2"          "GUF1"           "HINT2"
 [9] "LYRM7"          "MRM1"           "MTRF1"          "MTRF1L"
[13] "NT5DC2"         "PDK3"           "PDP2"           "PDPR"
[17] "PMPCA"          "POLDIP2"        "RNMTL1"         "THEM4"
[21] "THG1L"          "TRMT61B"        "TSFM"           "TMSB4XP2"

[[5]]$size
[1] 24

[[5]]$algorithm
[1] "FASTGREEDY"

[[5]]$depth
[1] 4

[[5]]$target_proteins
[1] "TRMT61B"


[[6]]
[[6]]$module_id
[1] "RC4_3"

[[6]]$genes
 [1] "AARS2"    "C1QBP"    "CDK5RAP1" "CLPX"     "COX8A"    "DHRS4L2"
 [7] "DUS2"     "FTSJ2"    "LBX2"     "METTL2A"  "MTIF2"    "MTO1"
[13] "ND3"      "NDUFAF5"  "NDUFAF7"  "NDUFS6"   "NUBPL"    "OXLD1"
[19] "PREPL"    "PUS1"     "THUMPD2"  "TRIT1"    "TRMT1"    "TRMT10A"
[25] "TRMT2B"   "TRMT5"    "UQCC1"    "UQCC2"    "YARS2"    "YBEY"
[31] "OR4S2"    "NDUFAF8"

[[6]]$size
[1] 32

[[6]]$algorithm
[1] "FASTGREEDY"

[[6]]$depth
[1] 4

[[6]]$target_proteins
[1] "PUS1"


[[7]]
[[7]]$module_id
[1] "RC3_5"

[[7]]$genes
 [1] "ACOT1"      "ACOT2"      "ANKRD20A8P" "ELAC2"      "FASTKD2"
 [6] "ICT1"       "METTL15"    "MMAB"       "MRPS36"     "MTERF1"
[11] "MTG2"       "NPM2"       "NUDT6"      "PPIF"       "PYCR1"
[16] "RCC1L"      "RNR2"       "RPUSD4"     "TEFM"       "THEM5"
[21] "TRMT10C"    "WBSCR16"    "TCAIM"      "TRNI"

[[7]]$size
[1] 24

[[7]]$algorithm
[1] "FASTGREEDY"

[[7]]$depth
[1] 3

[[7]]$target_proteins
[1] "RPUSD4"  "TRMT10C"


[[8]]
[[8]]$module_id
[1] "RC3_1"

[[8]]$genes
 [1] "ADAM8"      "ATP5L2"     "C12ORF65"   "CZIB"       "DDX28"
 [6] "GADD45GIP1" "GFM2"       "GTPBP10"    "GTPBP6"     "GTPBP8"
[11] "H1FNT"      "MALSU1"     "MIEF1-2"    "MRM2"       "MRM3"
[16] "MRPL10"     "MRPL11"     "MRPL13"     "MRPL14"     "MRPL15"
[21] "MRPL16"     "MRPL18"     "MRPL2"      "MRPL20"     "MRPL21"
[26] "MRPL22"     "MRPL23"     "MRPL24"     "MRPL28"     "MRPL3"
[31] "MRPL30"     "MRPL34"     "MRPL35"     "MRPL37"     "MRPL38"
[36] "MRPL39"     "MRPL4"      "MRPL41"     "MRPL42"     "MRPL43"
[41] "MRPL44"     "MRPL45"     "MRPL47"     "MRPL48"     "MRPL49"
[46] "MRPL50"     "MRPL51"     "MRPL52"     "MRPL53"     "MRPL54"
[51] "MRPL55"     "MRPL57"     "MRPL58"     "MRPS18A"    "MRPS30"
[56] "MTERF4"     "MTFMT"      "MTG1"       "MTRES1"     "NDUFAB1"
[61] "NSUN4"      "NSUN7"      "PLCXD1"     "PUS7L"      "TMEM177"
[66] "TSTD3"      "SORCS3"

[[8]]$size
[1] 67

[[8]]$algorithm
[1] "FASTGREEDY"

[[8]]$depth
[1] 3

[[8]]$target_proteins
[1] "NSUN4" "NSUN7" "PUS7L"


[[9]]
[[9]]$module_id
[1] "RC3_2"

[[9]]$genes
 [1] "AURKAIP1"    "CHCHD1"      "DUSP11"      "HCG_1984214" "MAP4K3"
 [6] "MAST1"       "MCAT"        "MRPL1"       "MRPS10"      "MRPS11"
[11] "MRPS14"      "MRPS17"      "MRPS18B"     "MRPS18C"     "MRPS2"
[16] "MRPS21"      "MRPS22"      "MRPS23"      "MRPS24"      "MRPS25"
[21] "MRPS27"      "MRPS28"      "MRPS31"      "MRPS33"      "MRPS34"
[26] "MRPS35"      "MRPS7"       "NGRN"        "NOA1"        "OXA1L"
[31] "PTCD3"       "RBFA"        "RNF157"      "TFB1M"       "TRMT10B"
[36] "ZNF707"      "ZNF133"

[[9]]$size
[1] 37

[[9]]$algorithm
[1] "FASTGREEDY"

[[9]]$depth
[1] 3

[[9]]$target_proteins
[1] "TRMT10B"


[[10]]
[[10]]$module_id
[1] "RC3_1"

[[10]]$genes
 [1] "ADAL"         "ADCY10"       "ADK"          "ADSL"         "ADSS1"
 [6] "ADSS2"        "ALDH16A1"     "AMPD1"        "AMPD2"        "AMPD3"
[11] "APRT"         "ATIC"         "CD163L1"      "DOHH"         "ENPP1"
[16] "ENPP3"        "ENTPD4"       "ENTPD5"       "ENTPD6"       "EPHX2"
[21] "GMPR"         "GMPR2"        "GMPS"         "GUCY1A1"      "GUCY1A2"
[26] "GUCY1B1"      "GUCY2F"       "IMPDH1"       "ITPA"         "NPR1"
[31] "NPR2"         "PAFAH1B2"     "PAPSS1"       "PAPSS2"       "PDE10A"
[36] "PDE11A"       "PDE1A"        "PDE1B"        "PDE1C"        "PDE5A"
[41] "PDE6C"        "PDE6H"        "PDE7A"        "PDE7B"        "PDE8A"
[46] "PDE8B"        "PLPP1"        "PROSC"        "SLC25A39"     "TATDN1"
[51] "WDR4"         "F8VP50_HUMAN" "PLPP6"        "PLPPR4"

[[10]]$size
[1] 54

[[10]]$algorithm
[1] "FASTGREEDY"

[[10]]$depth
[1] 3

[[10]]$target_proteins
[1] "WDR4"


[[11]]
[[11]]$module_id
[1] "RC4_1"

[[11]]$genes
 [1] "ABRAXAS1"        "AQP7P3"          "ATR"             "ATRIP"
 [5] "BARD1"           "BLM"             "BRCA2"           "BRCA3"
 [9] "BRIP1"           "C15ORF26"        "C17ORF82"        "CHEK2"
[13] "DCST2"           "DNA2"            "EME1"            "ENSP00000461865"
[17] "ENSP00000491596" "ETAA1"           "EXO1"            "FANCM"
[21] "FBH1"            "FEN1"            "FSBP"            "GEN1"
[25] "H2AX"            "HELQ"            "HLTF"            "ITIH5"
[29] "MCPH1"           "MRE11"           "MUS81"           "NBN"
[33] "PIF1"            "POLD1"           "POLQ"            "RAD17"
[37] "RAD50"           "RAD51"           "RAD51B"          "RAD51C"
[41] "RAD51D"          "RAD51D-2"        "RAD52"           "RAD54B"
[45] "RAD54L"          "RAD9A"           "RADX"            "RBBP8"
[49] "RECQL5"          "REV3L"           "RMI1"            "RMI2"
[53] "RNF168"          "SHLD1"           "SHLD2"           "SHLD3"
[57] "SLCO1B7"         "SLX1A"           "SMARCAL1"        "SPIDR"
[61] "SWI5"            "TOP3A"           "TP53BP1"         "UIMC1"
[65] "WRN"             "XPA"             "XRCC2"           "XRCC3"
[69] "RBMY2BP"         "LOC101930047"    "ZRANB3"          "WSCD1"
[73] "WSCD2"

[[11]]$size
[1] 73

[[11]]$algorithm
[1] "FASTGREEDY"

[[11]]$depth
[1] 4

[[11]]$target_proteins
[1] "RAD52"


[[12]]
[[12]]$module_id
[1] "RC5_1"

[[12]]$genes
 [1] "AOC4P"    "CBX5"     "CCDC37"   "DNMT1"    "KMT5B"    "KMT5C"
 [7] "MBD4"     "NFATC2"   "SETDB1"   "SNHG6"    "SNHG7"    "SUV39H1"
[13] "SUV39H2"  "UHRF1"    "ZBTB33"   "ZNF10"    "ZNF227"   "ZNF263"
[19] "ZNF274"   "ZNF649"   "RBBP4P1"  "RPL26P30" "ZNF45"    "ZNF678"

[[12]]$size
[1] 24

[[12]]$algorithm
[1] "FASTGREEDY"

[[12]]$depth
[1] 5

[[12]]$target_proteins
[1] "DNMT1"


[[13]]
[[13]]$module_id
[1] "RC4_1"

[[13]]$genes
 [1] "ARID4A"   "ARID4B"   "BRMS1"    "BRMS1L"   "C22ORF31" "CCSAP"
 [7] "DEPDC4"   "DPCR1"    "EMSY"     "FAM60A"   "FLJ25613" "FOXK2"
[13] "FRA10F"   "GATAD1"   "HDAC1"    "KDM5A"    "KLF10"    "KLF9"
[19] "MAX"      "MXD1"     "MXD3"     "MXD4"     "MYT1"     "PHF12"
[25] "PHF23"    "SAP130"   "SAP25"    "SAP30"    "SAP30L"   "SIN3A"
[31] "SIN3B"    "SINHCAF"  "SUDS3"    "TET1"     "TGIF2"    "TGIF2LX"
[37] "ZNF704"   "MGS"

[[13]]$size
[1] 38

[[13]]$algorithm
[1] "FASTGREEDY"

[[13]]$depth
[1] 4

[[13]]$target_proteins
[1] "TET1"


[[14]]
[[14]]$module_id
[1] "RC3_1"

[[14]]$genes
 [1] "C10ORF131" "CCNQ"      "CDX2"      "EOMES"     "FAM217A"   "FAM71B"
 [7] "FOXA2"     "FOXD1"     "FOXD3"     "GATA6"     "MIXL1"     "NANOG"
[13] "NUP62CL"   "OTX2"      "POU5F1"    "PROX2"     "SALL3"     "SALL4"
[19] "SIX3"      "SIX6"      "SOX1"      "SOX21"     "SYNDIG1L"  "TBX3"
[25] "TET2"      "TET3"      "TFEC"      "VRTN"      "WT1"       "ZIC2"
[31] "ZFP42"     "RNASE11"   "UTF1"      "TBXT"      "ZIC5"      "ZFPM2"
[37] "ZSCAN10"   "ZGLP1"     "POU5F1B"

[[14]]$size
[1] 39

[[14]]$algorithm
[1] "FASTGREEDY"

[[14]]$depth
[1] 3

[[14]]$target_proteins
[1] "TET2" "TET3"


[[15]]
[[15]]$module_id
[1] "RC3_1"

[[15]]$genes
 [1] "AIRE"      "ASH1L"     "CAMKMT"    "CDC14C"    "CDC73"     "CTR9"
 [7] "DNMT3A"    "DNMT3B"    "H2AB1"     "H2AC18"    "H2AW"      "H2AZ1"
[13] "H2BC1"     "H2BC13"    "H2BC14"    "H2BC15"    "H2BC17"    "H2BC18"
[19] "H2BC3"     "H2BC5"     "H2BC9"     "H2BE1"     "H2BS1"     "H2BU1"
[25] "H2BW1"     "H2BW2"     "H3-2"      "H3-3B"     "H3-4"      "H3-5"
[31] "H3C12"     "H3C13"     "H3C14"     "H3C15"     "H4C7"      "HDAC10"
[37] "HDAC8"     "KAT6B"     "KDM4B"     "KDM6B"     "KDM7A"     "KMT2E"
[43] "LEO1"      "MORC3"     "MPHOSPH8"  "NKX2-8"    "PADI4"     "PAF1"
[49] "PLEKHM1P"  "PRDM9"     "PRMT6"     "PXK"       "RNF20"     "RNF40"
[55] "RTF1"      "RTF2"      "SETD7"     "SETMAR"    "SIRT5"     "SKIC2"
[61] "SMYD3"     "TRDMT1"    "MACROH2A2" "ZNF557"    "ZCWPW2"    "SKIC8"
[67] "MIR124-3"  "LINC01270" "SPINDOC"

[[15]]$size
[1] 69

[[15]]$algorithm
[1] "FASTGREEDY"

[[15]]$depth
[1] 3

[[15]]$target_proteins
[1] "DNMT3A" "DNMT3B" "TRDMT1"


[[16]]
[[16]]$module_id
[1] "RC3_1"

[[16]]$genes
 [1] "AFF1"     "AFF3"     "AFF4"     "CCDC154"  "CCNT1"    "CCNT2"
 [7] "CHIC1"    "CTDP1"    "DENND2D"  "EAF1"     "EAF2"     "ELL"
[13] "ELL2"     "ELL3"     "ELOA"     "ELOA2"    "ELOB"     "ELOC"
[19] "ELP2"     "ELP4"     "FAM49A"   "FAM49B"   "FGF12"    "ICE1"
[25] "ICE2"     "IGLV2-23" "MLLT1"    "NELFE"    "NUFIP1"   "PCIF1"
[31] "PEX2"     "SUPT4H1"  "TCEA2"

[[16]]$size
[1] 33

[[16]]$algorithm
[1] "FASTGREEDY"

[[16]]$depth
[1] 3

[[16]]$target_proteins
[1] "PCIF1"


[[17]]
[[17]]$module_id
[1] "RC3_1"

[[17]]$genes
[1] "ARHGEF12"   "DUS1L"      "DUS3L"      "FRMPD2"     "PLEKHG4B"
[6] "SARS"       "TRMT61A"    "PTPN20"     "TRS-AGA2-4"

[[17]]$size
[1] 9

[[17]]$algorithm
[1] "FASTGREEDY"

[[17]]$depth
[1] 3

[[17]]$target_proteins
[1] "TRMT61A"


[[18]]
[[18]]$module_id
[1] "RC4_1"

[[18]]$genes
 [1] "ALKBH3"       "ANKRD55"      "ASB17"        "ATXN3"        "BEAN1"
 [6] "BRSK2"        "C9ORF171"     "CAPS"         "CAPSL"        "CCNJL"
[11] "DCDC5"        "DCX"          "DYNC1H1"      "DYNC1I1"      "DYNC1I2"
[16] "EML1"         "EML2"         "EML4"         "EML6"         "FAM71D"
[21] "FBXO25"       "FSD1L"        "GABRA1"       "GLI1"         "HEY1"
[26] "KCNH5"        "KIAA0895L"    "LOC260334"    "MAPT"         "METTL22"
[31] "NEAT1"        "NUDC"         "NXNL2"        "PAK1"         "PRRG2"
[36] "PTCRA"        "RHBDL3"       "SVBP"         "TCP11L1"      "TCP11L2"
[41] "TMEM151B"     "TMEM61"       "TPSB2"        "TTL"          "TUBA1A"
[46] "TUBA1B"       "TUBA1C"       "TUBA3C"       "TUBA3D"       "TUBA3E"
[51] "TUBA4A"       "TUBA4B"       "TUBAL3"       "TUBB"         "TUBB1"
[56] "TUBB2A"       "TUBB2B"       "TUBB3"        "TUBB4A"       "TUBB4B"
[61] "TUBB6"        "UCHL3"        "VCF1"         "VCP"          "YAP1"
[66] "ZC2HC1B"      "VCPKMT"       "VASH1"        "LOC100505498" "TUBB8B"

[[18]]$size
[1] 70

[[18]]$algorithm
[1] "FASTGREEDY"

[[18]]$depth
[1] 4

[[18]]$target_proteins
[1] "ALKBH3"


[[19]]
[[19]]$module_id
[1] "RC4_1"

[[19]]$genes
 [1] "ABCF2"        "ADGB"         "ALPK3"        "ASCL5"        "ATAD3C"
 [6] "CALY"         "CCDC81"       "CHCHD2P9"     "COL23A1"      "EEF1A1P5"
[11] "EFCAB12"      "EFCAB5"       "EIF4A2"       "EIF4E1B"      "EIF4E3"
[16] "EIF4EBP3"     "FER1L5"       "FRG1B"        "GCNA"         "GVINP1"
[21] "H1F0"         "H1FX"         "H2AFB3"       "H3.Y"         "HDGF"
[26] "HEXIM1"       "HIST1H1A"     "HIST1H1B"     "HIST1H1C"     "HIST1H1D"
[31] "HIST1H1E"     "HIST1H1T"     "HIST1H2AG"    "HIST1H2AH"    "HIST1H2BC"
[36] "HMX2"         "HNRNPA1L2"    "IGHV3-33"     "IGHV3-64D"    "IGKV1D-13"
[41] "IGKV2-30"     "IQCA1P1"      "LARP7"        "MAGED2"       "MEPCE"
[46] "NAP1L4"       "PABPC1L"      "PABPC3"       "PDCD4"        "PHF6"
[51] "PRSS3"        "RN7SK"        "RPL37AP8"     "SNURF"        "SPAG17"
[56] "SPRTN"        "TMA7"         "TNIP1"        "YBX2"         "LOC100128274"
[61] "ZNF37A"       "TAAR3"        "TMEM232"      "RNA18S5"      "RNA28S5"
[66] "ZNF735"

[[19]]$size
[1] 66

[[19]]$algorithm
[1] "FASTGREEDY"

[[19]]$depth
[1] 4

[[19]]$target_proteins
[1] "YBX2"


[[20]]
[[20]]$module_id
[1] "RC4_1"

[[20]]$genes
 [1] "ADGRB2"     "ADGRD1"     "ARHGEF33"   "C12ORF45"   "CDK11A"
 [6] "CTDSPL2"    "DDX19A"     "DDX19B-2"   "FOXI2"      "GLE1"
[11] "IPO5"       "IPO7"       "KPNA2"      "KPNA3"      "KPNA5"
[16] "KPNA6"      "KPNA7"      "KPNB1"      "NEMP1"      "NOSIP"
[21] "NPIPB6"     "NUMA1"      "NUP133"     "NUP153"     "NUP188"
[26] "NUP214"     "NUP37"      "NUP42"      "NUP50"      "NUP88"
[31] "NUP93"      "NUP98"      "NUPR1"      "PCID2"      "PPIAL4D"
[36] "PPIAL4H"    "R3HCC1"     "RAE1"       "RAN"        "RANBP1"
[41] "RANBP2"     "RANGAP1"    "RCC1"       "RGPD2"      "RGPD3"
[46] "RGPD4"      "RNF2"       "RNMT"       "RPS6KL1"    "SDPR"
[51] "SLFN11"     "SLX4"       "TIPARP"     "TNPO1"      "TPR"
[56] "TRN-GTT2-1" "TTC24"      "TRF-GAA1-5" "RNF222"

[[20]]$size
[1] 59

[[20]]$algorithm
[1] "FASTGREEDY"

[[20]]$depth
[1] 4

[[20]]$target_proteins
[1] "RNMT"


[[21]]
[[21]]$module_id
[1] "RC5_1"

[[21]]$genes
 [1] "ADAR"   "ANKHD1" "CCNF"   "FRMPD3" "MRE11A" "MYH10"  "NARS"   "NMT1"
 [9] "PHF3"   "SEPT7"  "TOP2B"  "XRCC6"

[[21]]$size
[1] 12

[[21]]$algorithm
[1] "FASTGREEDY"

[[21]]$depth
[1] 5

[[21]]$target_proteins
[1] "ADAR"


[[22]]
[[22]]$module_id
[1] "RC5_1"

[[22]]$genes
 [1] "ACT"          "AHCY"         "AHSA1"        "BIRC3"        "C14ORF183"
 [6] "CLEC18B"      "CSRP2"        "DBET"         "EIF4E"        "GART"
[11] "GTPBP1"       "HARS"         "IGHV1-18"     "IGHV1-45"     "LOC100128429"
[16] "MARCHF4"      "MARCHF9"      "NKAPP1"       "OLA1"         "OR13C4"
[21] "PLS3"         "UBE2H"        "UFL1"         "WDR5"         "GLIPR1L1"

[[22]]$size
[1] 25

[[22]]$algorithm
[1] "FASTGREEDY"

[[22]]$depth
[1] 5

[[22]]$target_proteins
[1] "EIF4E"


[[23]]
[[23]]$module_id
[1] "RC5_2"

[[23]]$genes
 [1] "ASCC3"   "C8ORF88" "C9ORF72" "CCAR2"   "CCDC8"   "CTPS1"   "EFTUD2"
 [8] "EIF4G1"  "OR5AR1"  "OTUD1"   "PRPF8"   "RCC2"    "RNU5A-1" "SND1"
[15] "STIP1"   "USP10"   "VARS"    "VCAM1"

[[23]]$size
[1] 18

[[23]]$algorithm
[1] "FASTGREEDY"

[[23]]$depth
[1] 5

[[23]]$target_proteins
[1] "SND1"


[[24]]
[[24]]$module_id
[1] "RC5_1"

[[24]]$genes
 [1] "C14ORF166" "C18ORF63"  "CBLL1"     "DDX3Y"     "DDX5"      "EIF4B"
 [7] "GIGYF2"    "IGKV1-5"   "LRRC16B"   "METTL14"   "METTL3"    "MEX3C"
[13] "PAN2"      "PCBP1"     "PRKDC"     "RBCK1"     "SMURF1"    "WTAP"
[19] "YTHDF1"    "YTHDF2"    "ZNF840P"

[[24]]$size
[1] 21

[[24]]$algorithm
[1] "FASTGREEDY"

[[24]]$depth
[1] 5

[[24]]$target_proteins
[1] "CBLL1"   "METTL14" "METTL3"  "WTAP"    "YTHDF1"  "YTHDF2"


[[25]]
[[25]]$module_id
[1] "RC3_7"

[[25]]$genes
 [1] "AARS"     "FARSB"    "KDF1"     "KIAA0101" "MAB21L2"  "NSUN2"
 [7] "PHACTR3"  "SETSIP"   "SLC45A3"  "TSN"      "ZC3HAV1L" "TAFA4"

[[25]]$size
[1] 12

[[25]]$algorithm
[1] "FASTGREEDY"

[[25]]$depth
[1] 3

[[25]]$target_proteins
[1] "NSUN2"


[[26]]
[[26]]$module_id
[1] "RC4_1"

[[26]]$genes
 [1] "DNM1P34"      "GUSBP4"       "LINC00339"    "LINC00847"    "LINC01268"
 [6] "LOC100129917" "LOC100287015" "LOC728743"    "LOC93432"     "LRRC53"
[11] "NNT-AS1"      "OBSL1"        "PSMA3-AS1"    "RRP7B"        "SH3BP5-AS1"
[16] "TTN-AS1"      "YTHDC1"       "ZFP69"

[[26]]$size
[1] 18

[[26]]$algorithm
[1] "FASTGREEDY"

[[26]]$depth
[1] 4

[[26]]$target_proteins
[1] "YTHDC1"


[[27]]
[[27]]$module_id
[1] "RC4_2"

[[27]]$genes
 [1] "ALYREF"    "API5"      "C15ORF52"  "C17ORF85"  "C19ORF47"  "CAAP1"
 [7] "CHTOP"     "CT45A6"    "DDX39B"    "DHX34"     "E2F4"      "EFCC1"
[13] "EIF4A3"    "FRG2"      "FYTTD1"    "MYCN"      "NCBP3"     "NXF1"
[19] "NXF2B"     "NXF3"      "NXF5"      "NXT1"      "PYM1"      "RBM33"
[25] "SAP30BP"   "SARNP"     "SNORA5A"   "THOC1"     "THOC2"     "THOC3"
[31] "THOC5"     "THOC6"     "THOC7"     "UPF2"      "UPF3A"     "UPF3B"
[37] "ZC3H11A"   "HILS1"     "SPATA31E1" "MAGOH2P"   "OR6S1"

[[27]]$size
[1] 41

[[27]]$algorithm
[1] "FASTGREEDY"

[[27]]$depth
[1] 4

[[27]]$target_proteins
[1] "ALYREF"


[[28]]
[[28]]$module_id
[1] "RC4_3"

[[28]]$genes
 [1] "ANKRD50"         "ARRDC3"          "C1ORF35"         "CCAR1"
 [5] "CCNL1"           "CDK11B"          "CPSF2"           "CPSF3"
 [9] "CPSF4"           "CPSF4L"          "CPSF6"           "CSTF1"
[13] "CSTF2"           "CSTF2T"          "CSTF3"           "DBX2"
[17] "DDX42"           "DEPDC7"          "ENSP00000423325" "FAM76A"
[21] "FAM76B"          "FIP1L1"          "HTRA4"           "IGHV3-30"
[25] "KIAA1614"        "LINC00305"       "MAPKAPK2"        "MECP2"
[29] "NCBP1"           "NCBP2"           "NRDE2"           "NSRP1"
[33] "PABPN1"          "PAPOLA"          "PAPOLB"          "PAPOLG"
[37] "PCF11"           "PPIL4"           "PPP1R10"         "PPP1R8"
[41] "PRPF40A"         "PRPF4B"          "RAD18"           "RAMAC"
[45] "RAMACL"          "RBBP6"           "RBM15B"          "RBM25"
[49] "RBM5"            "RBM7"            "RNU1-4"          "SLBP"
[53] "SLC35G3"         "SNRPA"           "SRRT"            "SSU72P2"
[57] "SSU72P3"         "SSU72P4"         "SSU72P5"         "SSU72P7"
[61] "SSU72P8"         "SUGP1"           "SUV420H2"        "TENT2"
[65] "TOP1"            "TOX4"            "TSPYL5"          "WDR33"
[69] "WDR82"           "ZC3H4"           "ZC3H6"           "ZCCHC8"
[73] "ZFC3H1"

[[28]]$size
[1] 73

[[28]]$algorithm
[1] "FASTGREEDY"

[[28]]$depth
[1] 4

[[28]]$target_proteins
[1] "NCBP1"  "NCBP2"  "PCF11"  "RBM15B"


[[29]]
[[29]]$module_id
[1] "RC4_4"

[[29]]$genes
 [1] "ABHD12B"   "ACIN1"     "ADARB2"    "AKAP17A"   "ARGLU1"    "ARL6IP4"
 [7] "ASB18"     "BCLAF1"    "C11ORF57"  "CCDC9"     "CDK12"     "CLEC18C"
[13] "CLK1"      "CLK2"      "CLK3"      "CLK4"      "DDX23"     "DHX40"

In [7]:
saveRDS(sub_modules, file = "inst/extdata/rmp_modules.rds")

In [9]:
asxxx

ERROR: Error: object 'asxxx' not found

In [ ]:
for (i in seq_along(modules)) {
    # print(intersect(sub_modules[[i]]$genes, rna_mod_proteins$gene_symbol))
    # print(sub_modules[[i]]$genes)
    print(i)
    print(rna_mod_proteins %>% dplyr::filter(gene_symbol %in% modules[[i]]$genes))
}

ERROR: Error: object 'modules' not found

In [ ]:
sub_modules[[1]]$genes

 [1] "ABCB6"      "ARL5B"      "ATP12A"     "ATP1B1"     "ATP7B"
 [6] "ATP8B2"     "C1ORF74"    "CD164L2"    "CD226"      "CD3D"
[11] "CLEC2D"     "CNNM4"      "DGCR2"      "DNAJC11"    "DSTYK"
[16] "FAM63B"     "GRPR"       "HSDL1"      "ITM2A"      "JTB"
[21] "KIAA1586"   "KLRC4"      "KLRD1"      "KLRF1"      "MBLAC2"
[26] "MICB"       "MTCH1"      "MTCH2"      "NCR2"       "NKAIN2"
[31] "NSUN3"      "PLD6"       "PPTC7"      "RHOBTB3"    "RHOT1"
[36] "SAYSD1"     "SCCPDH"     "SLC25A16"   "SLC25A20"   "SLC25A33"
[41] "SLC35D2"    "TACR3"      "TMEM184B"   "TRABD"      "TYROBP"
[46] "USP30"      "SLC25A10-2"

In [ ]:
print_enrichment_summary(functional_enrichment(gene_set = sub_modules[[1]]$genes, key_proteins = sub_modules[[1]]$target_proteins))

'select()' returned 1:1 mapping between keys and columns

'select()' returned 1:many mapping between keys and columns

Running functional enrichment analysis...

Running KEGG enrichment...

Reading KEGG annotation online: "https://rest.kegg.jp/link/hsa/pathway"...

Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway/hsa"...

Running GO-Biological Process enrichment...

Running WikiPathways enrichment...

Enrichment analysis completed!

=== Functional Enrichment Analysis Summary ===
Input genes: 47
Mapped genes: 44
Organism: hsa

=== KEGG Enrichment (1 significant pathways) ===
1. Natural killer cell mediated cytotoxicity (p=8.00e-05, q=3.60e-03, genes=4)

=== GO_BP Enrichment (41 significant pathways) ===
1. mitochondrion organization (p=4.79e-07, q=3.58e-04, genes=9)
2. mitochondrial fusion (p=1.07e-06, q=4.00e-04, genes=4)
3. mitochondrial transport (p=3.07e-06, q=7.65e-04, genes=6)
4. positive regulation of leukocyte mediated cytotoxicity (p=1.58e-05, q=1.75e-03, genes=4)
5. stimulatory C-type lectin receptor signaling pathway (p=1.78e-05, q=1.75e-03, genes=3)
6. response to lectin (p=1.78e-05, q=1.75e-03, genes=3)
7. cellular response to lectin (p=1.78e-05, q=1.75e-03, genes=3)
8. positive regulation of cell killing (p=1.87e-05, q=1.75e-03, genes=4)
9. positive regulation of natural killer cell mediated cytotoxicity (p=3.64e-05, q=3.02e-03, genes=3)
10. positive regulation of natural killer cell mediated immunity (p=6.45e-05, q=4.83e-03, genes=3)

=== WIKIPATHWAYS Enrichment (No significant pathways) ===

In [ ]:
library(DOSE)
library(org.Hs.eg.db)
library(clusterProfiler)
library(dplyr)

Attaching package: ‘dplyr’


The following object is masked from ‘package:AnnotationDbi’:

    select


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, setequal, union


The following object is masked from ‘package:generics’:

    explain


The following object is masked from ‘package:MPAGE’:

    as_data_frame


The following object is masked from ‘package:testthat’:

    matches


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [16]:
ids <- bitr(rna_mod_proteins$gene_symbol, fromType = "SYMBOL", toType = c("ENTREZID", "ENSEMBL"), OrgDb = "org.Hs.eg.db") %>%
    full_join(rna_mod_proteins, by = c("SYMBOL" = "gene_symbol"))
ids

'select()' returned 1:many mapping between keys and columns

   SYMBOL  ENTREZID ENSEMBL         modification_type functional_role
1  ADAR    103      ENSG00000160710 A-to-I editing    writer
2  ADARB1  104      ENSG00000197381 A-to-I editing    writer
3  ADARB2  105      ENSG00000185736 A-to-I editing    writer
4  NAT10   55226    ENSG00000135372 ac4C              writer
5  ALKBH3  221120   ENSG00000166199 m1A               eraser
6  ALKBH7  84266    ENSG00000125652 m1A               eraser
7  RRP8    23378    ENSG00000132275 m1A               writer
8  TRMT10B 158234   ENSG00000165275 m1A               writer
9  TRMT10C 54931    ENSG00000174173 m1A               writer
10 TRMT6   51605    ENSG00000089195 m1A               writer
11 TRMT61A 115708   ENSG00000166166 m1A               writer
12 TRMT61B 55006    ENSG00000171103 m1A               writer
13 YTHDC1  91746    ENSG00000083896 m1A, m6A          reader
14 YTHDC1  91746    ENSG00000275272 m1A, m6A          reader
15 YTHDF1  54915    ENSG00000149658 m1A, m6A          reader
16 YTHDF2  51441    ENSG00000198492 m1A, m6A, m5C     reader
17 ALKBH1  8846     ENSG00000100601 m1A,m5C           eraser
18 YTHDF3  253943   ENSG00000185728 m1A,m6A           reader
19 FTO     79068    ENSG00000140718 m1A,m6A,m6Am      eraser
20 TET1    80312    ENSG00000138336 m5C               eraser
21 TET2    54790    ENSG00000168769 m5C               eraser
22 TET3    200424   ENSG00000187605 m5C               eraser
23 ALYREF  10189    ENSG00000183684 m5C               reader
24 RAD52   5893     ENSG00000002016 m5C               reader
25 SRSF2   6427     ENSG00000161547 m5C               reader
26 YBX1    4904     ENSG00000065978 m5C               reader
27 YBX2    51087    ENSG00000006047 m5C               reader
28 YBX2    51087    ENSG00000288504 m5C               reader
29 DNMT1   1786     ENSG00000130816 m5C               writer
30 DNMT3A  1788     ENSG00000119772 m5C               writer
⋮  ⋮       ⋮        ⋮               ⋮                 ⋮
64 VIRMA   25962    ENSG00000164944 m6A               writer
65 WTAP    9589     ENSG00000146457 m6A               writer
66 ZC3H13  23091    ENSG00000123200 m6A               writer
67 ZCCHC4  29063    ENSG00000168228 m6A               writer
68 FMR1    2332     ENSG00000102081 m6A, m5C          reader
69 IGF2BP3 10643    ENSG00000136231 m6A, m7G          reader
70 PCF11   51585    ENSG00000165494 m6Am              reader
71 METTL4  64863    ENSG00000101574 m6Am              writer
72 PCIF1   63935    ENSG00000100982 m6Am              writer
73 EIF4E   1977     ENSG00000151247 m7G               reader
74 NCBP1   4686     ENSG00000136937 m7G               reader
75 NCBP2   22916    ENSG00000114503 m7G               reader
76 QKI     9444     ENSG00000112531 m7G               reader
77 BUD23   114049   ENSG00000071462 m7G               writer
78 METTL1  4234     ENSG00000037897 m7G               writer
79 RNMT    8731     ENSG00000101654 m7G               writer
80 TRMT112 51504    ENSG00000173113 m7G               writer
81 WDR4    10785    ENSG00000160193 m7G               writer
82 DKC1    1736     ENSG00000130826 Ψ                 writer
83 PUS1    80324    ENSG00000177192 Ψ                 writer
84 PUS10   150962   ENSG00000162927 Ψ                 writer
85 PUS3    83480    ENSG00000110060 Ψ                 writer
86 PUS7    54517    ENSG00000091127 Ψ                 writer
87 PUS7L   83448    ENSG00000129317 Ψ                 writer
88 RPUSD1  113000   ENSG00000007376 Ψ                 writer
89 RPUSD2  27079    ENSG00000166133 Ψ                 writer
90 RPUSD3  285367   ENSG00000156990 Ψ                 writer
91 RPUSD4  84881    ENSG00000165526 Ψ                 writer
92 TRUB1   142940   ENSG00000165832 Ψ                 writer
93 TRUB2   26995    ENSG00000167112 Ψ                 writer

In [ ]:
enrichWP(ids$ENTREZID,
    organism = "Homo sapiens", pAdjustMethod = "BH",
    pvalueCutoff = 0.01,
    qvalueCutoff = 0.05
) %>% as.data.frame()

     ID Description GeneRatio BgRatio RichFactor FoldEnrichment zScore pvalue
     p.adjust qvalue geneID Count

In [ ]:
enrichKEGG(ids$ENTREZID,
        organism = "hsa", pAdjustMethod = "BH",
        pvalueCutoff = 0.01,
        qvalueCutoff = 0.05
) %>% as.data.frame()

         category           subcategory   ID
hsa04650 Organismal Systems Immune system hsa04650
         Description                               GeneRatio BgRatio
hsa04650 Natural killer cell mediated cytotoxicity 4/17      134/9440
         RichFactor FoldEnrichment zScore   pvalue       p.adjust
hsa04650 0.02985075 16.57594       7.712907 8.004587e-05 0.003602064
         qvalue      geneID              Count
hsa04650 0.003286094 3824/4277/9436/7305 4

In [ ]:
enrichGO(ids$ENTREZID, org.Hs.eg.db,
        ont = "BP", pAdjustMethod = "BH",
        pvalueCutoff = 0.01,
        qvalueCutoff = 0.05,
        readable = TRUE
) %>% as.data.frame()

           ID
GO:0007005 GO:0007005
GO:0008053 GO:0008053
GO:0006839 GO:0006839
GO:0001912 GO:0001912
GO:0002223 GO:0002223
GO:1990840 GO:1990840
GO:1990858 GO:1990858
GO:0031343 GO:0031343
GO:0045954 GO:0045954
GO:0002717 GO:0002717
GO:0001910 GO:0001910
GO:0002429 GO:0002429
GO:0031341 GO:0031341
GO:0007006 GO:0007006
GO:0002768 GO:0002768
GO:0042269 GO:0042269
           Description
GO:0007005 mitochondrion organization
GO:0008053 mitochondrial fusion
GO:0006839 mitochondrial transport
GO:0001912 positive regulation of leukocyte mediated cytotoxicity
GO:0002223 stimulatory C-type lectin receptor signaling pathway
GO:1990840 response to lectin
GO:1990858 cellular response to lectin
GO:0031343 positive regulation of cell killing
GO:0045954 positive regulation of natural killer cell mediated cytotoxicity
GO:0002717 positive regulation of natural killer cell mediated immunity
GO:0001910 regulation of leukocyte mediated cytotoxicity
GO:0002429 immune response-activating cell surface receptor signaling pathway
GO:0031341 regulation of cell killing
GO:0007006 mitochondrial membrane organization
GO:0002768 immune response-regulating cell surface receptor signaling pathway
GO:0042269 regulation of natural killer cell mediated cytotoxicity
           GeneRatio BgRatio   RichFactor FoldEnrichment zScore    pvalue
GO:0007005 9/42      445/18805 0.02022472  9.055377       8.136323 4.785959e-07
GO:0008053 4/42      35/18805  0.11428571 51.170068      14.055465 1.070098e-06
GO:0006839 6/42      183/18805 0.03278689 14.679938       8.798226 3.068008e-06
GO:0001912 4/42      68/18805  0.05882353 26.337535       9.903015 1.577930e-05
GO:0002223 3/42      23/18805  0.13043478 58.400621      13.031914 1.778467e-05
GO:1990840 3/42      23/18805  0.13043478 58.400621      13.031914 1.778467e-05
GO:1990858 3/42      23/18805  0.13043478 58.400621      13.031914 1.778467e-05
GO:0031343 4/42      71/18805  0.05633803 25.224681       9.675438 1.873510e-05
GO:0045954 3/42      29/18805  0.10344828 46.317734      11.554849 3.635336e-05
GO:0002717 3/42      35/18805  0.08571429 38.377551      10.471559 6.451133e-05
GO:0001910 4/42      100/18805 0.04000000 17.909524       8.021418 7.214967e-05
GO:0002429 6/42      340/18805 0.01764706  7.901261       6.075637 1.012545e-04
GO:0031341 4/42      110/18805 0.03636364 16.281385       7.604925 1.045244e-04
GO:0007006 4/42      120/18805 0.03333333 14.924603       7.239783 1.463453e-04
GO:0002768 6/42      372/18805 0.01612903  7.221582       5.734201 1.654083e-04
GO:0042269 3/42      53/18805  0.05660377 25.343666       8.396509 2.245353e-04
           p.adjust     qvalue
GO:0007005 0.0003383673 0.0002780894
GO:0008053 0.0003782797 0.0003108917
GO:0006839 0.0007230272 0.0005942247
GO:0001912 0.0016557148 0.0013607602
GO:0002223 0.0016557148 0.0013607602
GO:1990840 0.0016557148 0.0013607602
GO:1990858 0.0016557148 0.0013607602
GO:0031343 0.0016557148 0.0013607602
GO:0045954 0.0028557587 0.0023470242
GO:0002717 0.0045609509 0.0037484477
GO:0001910 0.0046372558 0.0038111594
GO:0002429 0.0056845198 0.0046718602
GO:0031341 0.0056845198 0.0046718602
GO:0007006 0.0073904355 0.0060738784
GO:0002768 0.0077962466 0.0064073969
GO:0042269 0.0099216515 0.0081541750
           geneID                                                  Count
GO:0007005 DNAJC11/JTB/MTCH1/MTCH2/PLD6/RHOT1/SLC25A33/TRABD/USP30 9
GO:0008053 MTCH2/PLD6/TRABD/USP30                                  4
GO:0006839 MTCH1/MTCH2/RHOT1/SLC25A16/SLC25A20/SLC25A33            6
GO:0001912 CD226/KLRC4/KLRD1/TYROBP                                4
GO:0002223 KLRC4/KLRD1/TYROBP                                      3
GO:1990840 KLRC4/KLRD1/TYROBP                                      3
GO:1990858 KLRC4/KLRD1/TYROBP                                      3
GO:0031343 CD226/KLRC4/KLRD1/TYROBP                                4
GO:0045954 CD226/KLRC4/KLRD1                                       3
GO:0002717 CD226/KLRC4/KLRD1                                       3
GO:0001910 CD226/KLRC4/KLRD1/TYROBP                                4
GO:0002429 CD226/CD3D/KLRC4/KLRD1/MICB/TYROBP                      6
GO:0031341 CD226/KLRC4/KLRD1/TYROBP                                4
GO:0007006 DNAJC11/MTCH1/MTCH2/RHOT1                               4
GO:0002768 CD226/CD3D/KLRC4/KLRD1/MICB/TYROBP                      6
GO:0042269 CD226/KLRC4/KLRD1                                       3

In [ ]:
all_vertices <- igraph::V(merged_networks)$name
target_proteins <- rna_mod_proteins$gene_symbol
target_in_network <- target_proteins[target_proteins %in% all_vertices]
length(target_in_network)
setdiff(target_proteins, all_vertices)

[1] 56

[1] "NSUN1" "DNMT2"

In [ ]:
fc <- igraph::cluster_fast_greedy(merged_networks)
module_list <- igraph::groups(fc)

In [ ]:
names(module_list[[1]])

NULL

In [ ]:
louvain_clusters <- igraph::cluster_louvain(merged_networks)

In [ ]:
louvain_members <- membership(louvain_clusters)
modularity_score <- modularity(louvain_clusters)
cat("Louvain模块度：", modularity_score, "\n")

ERROR: Error in membership(louvain_clusters): could not find function "membership"

In [ ]:
module_sizes <- table(louvain_members)
module_sizes

louvain_members
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16
1865 2948 4831 5302 1405 2261 2619  223   30   60    2    5    7    2    1    9
  17   18   19   20   21   22   23   24   25   26   27   28   29   30
   2    2    3    2    3    2    2    2    2    2    4    2    2    4

In [ ]:
louvain_module_df <- data.frame(
  gene = names(louvain_members),
  module_id = as.integer(louvain_members),
  stringsAsFactors = FALSE
)

In [ ]:
subgraph_genes <- louvain_module_df$gene[louvain_module_df$module_id %in% c(2, 3, 4, 5, 6, 7)]
rna_subgraph <- induced_subgraph(merged_networks, subgraph_genes)
cat("RNA修饰子网络规模：", vcount(rna_subgraph), "节点，", ecount(rna_subgraph), "边\n")

RNA修饰子网络规模： 19366 节点， 984347 边

In [ ]:
subgraph_genes <- louvain_module_df$gene[louvain_module_df$module_id %in% c(2)]
rna_subgraph <- induced_subgraph(merged_networks, subgraph_genes)
fine_clusters <- cluster_fast_greedy(rna_subgraph)

In [ ]:
fine_clusters

IGRAPH clustering fast greedy, groups: 39, mod: 0.43
+ groups:
  $`1`
    [1] "ABHD8"           "ADAT1"           "ADPRH"           "AGGF1"
    [5] "AGO1"            "AGO2"            "AGO3"            "ALG13"
    [9] "ALKBH1"          "ALKBH2"          "ALKBH6"          "ALKBH7"
   [13] "ALKBH8"          "ANKHD1"          "ANKHD1-EIF4EBP3" "ANKLE1"
   [17] "ANKRD17"         "ANKRD33B"        "ANKRD37"         "ANXA2R"
   [21] "ASZ1"            "ATXN2"           "B9D2"            "BICC1"
   [25] "BTG3"            "BTG4"            "C14ORF79"        "C6ORF48"
   [29] "C8ORF58"         "C9ORF57"         "C9ORF84"         "C9ORF85"
   [33] "CACTIN-AS1"      "CCDC179"         "CCDC3"           "CCDC83"
  + ... omitted several groups/vertices

In [ ]:
louvain_module_df %>%
    dplyr::filter(gene %in% rna_mod_proteins$gene_symbol) %>%
    arrange(module_id)

   gene      module_id
1  ADARB2    2
2  ALKBH1    2
3  ALKBH5    2
4  ALYREF    2
5  FTO       2
6  HNRNPA2B1 2
7  IGF2BP1   2
8  IGF2BP2   2
9  IGF2BP3   2
10 RBM15     2
11 RBM15B    2
12 VIRMA     2
13 YTHDC1    2
14 YTHDF1    2
15 YTHDF2    2
16 YTHDF3    2
17 ZC3H13    2
18 NSUN3     3
19 ALKBH3    4
20 METTL3    4
21 RNMT      4
22 WDR4      4
23 WTAP      4
24 ADARB1    6
25 DKC1      6
26 EIF4E     6
27 METTL1    6
28 METTL14   6
29 NSUN2     6
30 NSUN4     6
31 NSUN5     6
32 NSUN6     6
33 NSUN7     6
34 PUS1      6
35 PUS3      6
36 PUS7      6
37 RPS25     6
38 RPS26     6
39 RPUSD4    6
40 TRMT10C   6
41 TRMT6     6
42 TRMT61A   6
43 TRMT61B   6
44 TRUB1     6
45 TRUB2     6
46 YBX1      6
47 YTHDC2    6
48 ADAR      7
49 DNMT1     7
50 DNMT3A    7
51 DNMT3B    7
52 TET1      7
53 TET2      7
54 TET3      7

In [ ]:
sapply(louvain_clusters, function(x) length(x))

 membership memberships  modularity       names      vcount   algorithm
       2682        4004        3630        5008         268        4110

In [ ]:
igraph::membership(louvain_clusters)
igraph::modularity(louvain_clusters)

                  A1BG                   A1CF                    A2M
                     1                      2                      1
                 A2ML1                A3GALT2                 A4GALT
                     1                      3                      4
                 A4GNT                   AAAS                   AACS
                     4                      4                      3
                 AADAC                  AADAT                  AAED1
                     5                      3                      6
                 AAGAB                   AAK1                  AAMDC
                     4                      2                      2
                  AAMP                  AANAT                   AAR2
                     6                      5                      3
                  AARD                   AARS                  AARS1
                     2                      3                      7
                 AARS2                 AARSD1                  AASDH
                     7                      3                      4
              AASDHPPT                   AASS                   AATF
                     3                      7                      6
                  AATK                   ABAT                  ABCA1
                     3                      3                      1
                ABCA10                 ABCA12                 ABCA13
                     3                      1                      6
               ABCA17P                  ABCA2                  ABCA3
                     2                      4                      4
                 ABCA4                  ABCA5                  ABCA6
                     5                      4                      1
                 ABCA7                  ABCA8                  ABCA9
                     4                      1                      3
                 ABCB1                 ABCB10                 ABCB11
                     4                      4                      4
                 ABCB4                  ABCB5                  ABCB6
                     4                      4                      4
                 ABCB7                  ABCB8                  ABCB9
                     7                      4                      4
                 ABCC1                 ABCC10                 ABCC11
                     4                      4                      3
                ABCC12                 ABCC13                  ABCC2
                     3                      6                      4
                 ABCC3                  ABCC4                  ABCC5
                     4                      4                      4
                 ABCC6                  ABCC8                  ABCC9
                     3                      4                      4
                 ABCD1                  ABCD2                  ABCD3
                     4                      4                      4
                 ABCD4                  ABCE1                  ABCF1
                     4                      7                      6
                 ABCF2                ABCF2-2                  ABCF3
                     6                      7                      2
                 ABCG1                  ABCG2                  ABCG4
                     1                      4                      4
                 ABCG5                  ABCG8                  ABHD1
                     4                      4                      4
                ABHD10                 ABHD11                 ABHD12
                     7                      2                      4
               ABHD12B                 ABHD13                ABHD14A
                     6                      4                      4
          ABHD14A-ACY1                ABHD14B                 ABHD15
                     3                      3                      3
            ABHD15-AS1                ABHD16A                ABHD16B
                     8                      4                      6
               ABHD17A                ABHD17B                ABHD17C
                     2                      4                      4
                 ABHD2                  ABHD3                  ABHD4
                     2                      4                      4
                 ABHD5                  ABHD6                  ABHD8
                     4                      4                      2
                  ABI1                   ABI2                   ABI3
                     2                      2                      2
                ABI3BP                ABITRAM                   ABL1
                     1                      2                      4
                  ABL2                 ABLIM1                 ABLIM2
                     2                      2                      4
                ABLIM3                    ABO                    ABR
                     2                      1                      2
                  ABRA                 ABRACL               ABRAXAS1
                     3                      2                      6
              ABRAXAS2                   ABT1                  ABTB1
                     6                      6                      1
                 ABTB2                  ACAA1                  ACAA2
                     2                      7                      7
                 ACACA                  ACACB                 ACAD10
                     3                      3                      4
                ACAD11                  ACAD8                  ACAD9
                     6                      7                      7
                 ACADL                  ACADM                  ACADS
                     7                      7                      7
                ACADSB                 ACADVL                   ACAN
                     7                      7                      1
                 ACAP1                  ACAP2                  ACAP3
                     4                      3                      3
                 ACAT1                  ACAT2                  ACBD3
                     7                      3                      4
                 ACBD4                  ACBD5                  ACBD6
                     2                      4                      2
                 ACBD7                   ACCS                  ACCSL
                     4                      2                      1
                   ACD                    ACE                   ACE2
                     3                      4                      7
                 ACER1                  ACER2                  ACER3
                     4                      4                      4
                   ACF                   ACHE                  ACIN1
                     6                      5                      6
                 ACKR1                  ACKR2                  ACKR3
                     1                      4                      1
                 ACKR4                   ACLY                  ACMSD
                     1                      3                      3
                  ACN9                   ACO1                   ACO2
                     7                      7                      7
                 ACOD1                  ACOT1                 ACOT11
                     3                      7                      2
                ACOT12                 ACOT13                  ACOT2
                     7                      3                      7
                 ACOT4                  ACOT6                  ACOT7
                     7                      1                      3
                 ACOT8                  ACOT9                  ACOX1
                     3                      3                      7
                 ACOX2                  ACOX3                  ACOXL
                     7                      7                      7
                  ACP1                   ACP2                   ACP4
                     3                      4                      1
                  ACP5                   ACP6                   ACP7
                     1                      7                      3
                  ACPP                   ACPT                    ACR
                     1                      2                      2
                 ACRBP                   ACRC                  ACRV1
                     2                      4                      1
                ACSBG1                 ACSBG2                  ACSF2
                     4                      4                      7
                 ACSF3                  ACSL1                  ACSL3
                     7                      4                      4
                 ACSL4                  ACSL5                  ACSL6
                     4                      4                      4
                 ACSM1                 ACSM2A                 ACSM2B
                     2                      7                      7
                 ACSM3                  ACSM4                  ACSM5
                     7                      7                      7
                 ACSS1                  ACSS2                  ACSS3
                     7                      7                      7
                   ACT                  ACTA1                  ACTA2
                     6                      3                      3
             ACTA2-AS1                   ACTB                 ACTBL2
                     3                      3                      3
                 ACTC1                  ACTG1               ACTG1P14
                     6                      3                      8
                 ACTG2                 ACTL10                 ACTL6A
                     3                      2                      6
                ACTL6B                 ACTL7A                 ACTL7B
                     6                      3                      2
                 ACTL8                  ACTL9                  ACTN1
                     6                      2                      3
                 ACTN2                  ACTN3                  ACTN4
                     3                      3                      3
                ACTR10                 ACTR1A                 ACTR1B
                     3                      3                      3
                 ACTR2                  ACTR3                 ACTR3B
                     3                      3                      3
                ACTR3C                  ACTR5                  ACTR6
                     3                      6                      6
                 ACTR8                 ACTRT1                 ACTRT2
                     6                      3                      3
                ACTRT3                  ACVR1                 ACVR1B
                     3                      1                      4
                ACVR1C                 ACVR2A                 ACVR2B
                     1                      4                      4
                ACVRL1                   ACY1                   ACY3
                     1                      3                      2
                 ACYP1                  ACYP2                    ADA
                     7                      3                      3
                  ADA2                  ADAD1                  ADAD2
                     3                      4                      3
                  ADAL                 ADAM10                 ADAM11
                     3                      4                      1
                ADAM12                 ADAM15                 ADAM17
                     2                      4                      4
                ADAM18                 ADAM19                 ADAM1A
                     4                      1                      4
                 ADAM2                 ADAM20               ADAM20P1
                     1                      1                      2
                ADAM21                 ADAM22                 ADAM23
                     1                      4                      4
                ADAM28                 ADAM29                 ADAM30
                     1                      3                      1
                ADAM32                 ADAM33                  ADAM5
                     4                      4                      3
                 ADAM7                  ADAM8                  ADAM9
                     4                      3                      1
              ADAMDEC1                ADAMTS1               ADAMTS10
                     3                      1                      1
              ADAMTS12               ADAMTS13               ADAMTS14
                     1                      1                      1
              ADAMTS15               ADAMTS16               ADAMTS17
                     1                      6                      1
              ADAMTS18               ADAMTS19                ADAMTS2
                     1                      1                      1
              ADAMTS20                ADAMTS3                ADAMTS4
                     3                      1                      1
               ADAMTS5                ADAMTS6                ADAMTS7
                     1                      3                      1
               ADAMTS8                ADAMTS9            ADAMTS9-AS2
                     1                      1                      6
              ADAMTSL1               ADAMTSL2               ADAMTSL3
                     1                      1                      2
              ADAMTSL4               ADAMTSL5                  ADAP1
                     2                      2                      2
                 ADAP2                   ADAR                 ADARB1
                     2                      6                      6
                ADARB2             ADARB2-AS1                  ADAT1
                     6                      4                      3
                 ADAT2                  ADAT3                  ADCK1
                     3                      3                      4
                 ADCK2                  ADCK3                  ADCK4
                     4                      4                      4
                 ADCK5                  ADCY1                 ADCY10
                     7                      3                      3
                 ADCY2                  ADCY3                  ADCY4
                     3                      4                      3
                 ADCY5                  ADCY6                  ADCY7
                     3                      4                      3
                 ADCY8                  ADCY9                ADCYAP1
                     3                      4                      4
             ADCYAP1R1                   ADD1                   ADD2
                     4                      4                      4
                  ADD3                   ADGB                 ADGRA1
                     4                      6                      4
                ADGRA2                 ADGRA3                 ADGRB1
                     1                      4                      4
                ADGRB2                 ADGRB3                 ADGRD1
                     6                      4                      2
                ADGRE1                 ADGRE2                 ADGRE3
                     4                      4                      4
                ADGRE5                 ADGRF1                 ADGRF5
                     4                      4                      1
                ADGRG1                 ADGRG2                 ADGRG3
                     4                      4                      4
                ADGRG4                 ADGRG5                 ADGRG6
                     4                      4                      1
                ADGRG7                 ADGRL1                 ADGRL2
                     4                      4                      4
                ADGRL3                 ADGRL4                 ADGRV1
                     4                      3                      2
                 ADH1A                  ADH1B                  ADH1C
                     5                      5                      5
                  ADH4                   ADH5                   ADH6
                     5                      5                      5
                  ADH7                 ADHFE1                   ADI1
                     5                      5                      3
                ADIPOQ                ADIPOR1                ADIPOR2
                     4                      4                      4
                 ADIRF                 ADISSP                    ADK
                     3                      3                      3
                   ADM                   ADM2                   ADM5
                     4                      4                      2
                  ADNP                  ADNP2                    ADO
                     6                      6                      3
                ADORA1                ADORA2A                ADORA2B
                     4                      4                      4
                ADORA3                  ADPGK              ADPGK-AS1
                     4                      4                      8
                 ADPRH                ADPRHL1                ADPRHL2
                     3                      2                      3
                 ADPRM                 ADRA1A                 ADRA1B
                     4                      4                      4
                ADRA1D                 ADRA2A                 ADRA2B
                     4                      4                      4
                ADRA2C                  ADRB1                  ADRB2
                     4                      4                      4
                 ADRB3                 ADRBK1                 ADRBK2
                     4                      4                      3
                 ADRM1                   ADSL                   ADSS
                     3                      3                      3
                 ADSS1                  ADSS2                 ADSSL1
                     3                      3                      2
                 ADTRP                  AEBP1                  AEBP2
                     4                      2                      6
                   AEN                    AES                  AFAP1
                     2                      2                      3
             AFAP1-AS1                AFAP1L1                AFAP1L2
                     8                      2                      3
                  AFD1                   AFDN                   AFF1
                     1                      4                      6
                  AFF2                   AFF3                   AFF4
                     6                      6                      6
                 AFG1L                  AFG2A                AFG3L1P
                     3                      2                      1
                AFG3L2                    AFM                  AFMID
                     7                      1                      3
                   AFP                  AFTPH                    AGA
                     1                      4                      7
                 AGAP1                 AGAP11                  AGAP2

[1] 0.3166346

In [ ]:
fc <- igraph::cluster_fast_greedy(merged_networks)
module_list <- igraph::groups(fc)
intersect(get_rna_mod_proteins()$gene_symbol, module_list[["6"]])

character(0)

In [ ]:
fc <- igraph::cluster_edge_betweenness(merged_networks)
module_list <- igraph::groups(fc)
intersect(get_rna_mod_proteins()$gene_symbol, module_list[["6"]])

In [ ]:
names(module_list)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30"
[31] "31" "32" "33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45"
[46] "46" "47" "48" "49" "50" "51" "52" "53" "54" "55" "56" "57" "58" "59" "60"
[61] "61" "62" "63" "64" "65" "66" "67" "68" "69" "70" "71" "72" "73" "74" "75"
[76] "76" "77" "78" "79"

In [ ]:
module_list[["5"]]

 [1] "ART1"     "OR52N1"   "OR52N5"   "SEPTIN1"  "SEPTIN10" "SEPTIN11"
 [7] "SEPTIN12" "SEPTIN14" "SEPTIN2"  "SEPTIN3"  "SEPTIN4"  "SEPTIN5"
[13] "SEPTIN6"  "SEPTIN7"  "SEPTIN8"  "SEPTIN9"  "TMEM250"

In [ ]:
merged_networks_i <- merge_ppi_networks(networkds, merge_method = "intersection", add_source_labels = TRUE)

Merging 3 networks using method: intersection

=== Merged Network Summary ===
Data sources: string, biogrid, intact
Merge method: intersection
Total nodes: 3802
Total edges: 6113
Network density: 0.0008
Average degree: 3.22

=== Source Contribution ===

biogrid  intact  string
   6113    6113    6113

Interactions from multiple sources: 6113 (100.0%)

In [ ]:
merged_networks_i

IGRAPH 80f364c UNW- 3802 6113 --
+ attr: name (v/c), degree (v/n), weight (e/n), sources (e/c)
+ edges from 80f364c (vertex names):
 [1] AAGAB   --AP2S1   AAK1    --AP2M1   AAK1    --AP2S1   AAR2    --EFTUD2
 [5] AASDHPPT--USP22   AATF    --NGDN    ABCB7   --FECH    ABHD16A --RNF5
 [9] ABI1    --ABL1    ABI1    --CYFIP1  ABI1    --NCKAP1  ABI1    --WASF1
[13] ABI1    --WASF2   ABI2    --BRK1    ABI2    --CYFIP1  ABI2    --NCK2
[17] ABI2    --NCKAP1  ABI2    --TRIM32  ABI2    --WASF1   ABL1    --CRK
[21] ABL1    --CRKL    ABL1    --RIN1    ABL1    --YWHAB   ABL1    --YWHAE
[25] ABL1    --YWHAG   ABL1    --YWHAH   ABL1    --YWHAZ   ABL2    --CRK
[29] ABL2    --RIN1    ABTB1   --CUL3    ABTB1   --EEF1A2  ACAD9   --ECSIT
+ ... omitted several edges

In [ ]:
networkds

$string
IGRAPH 37070ab UN-- 16185 236000 --
+ attr: name (v/c), source (e/c)
+ edges from 37070ab (vertex names):
 [1] ARF5 --ACAP1     ARF5 --COPA      ARF5 --RAB11FIP3 ARF5 --COPB2
 [5] ARF5 --COPE      ARF5 --ARF3      ARF5 --ARFGAP1   ARF5 --RAB11FIP1
 [9] ARF5 --CYTH1     ARF5 --IQSEC1    ARF5 --RAB11A    ARF5 --ARFGAP2
[13] ARF5 --COPB1     ARF5 --ARF4      ARF5 --ASAP1     ARF5 --RAB11FIP4
[17] ARF5 --GORAB     ARF5 --ACAP2     ARF5 --ARFGAP3   ARF5 --ARFIP1
[21] ARF5 --ARF1      ARF5 --CDKN2A    ARF5 --GBF1      ARF5 --ARFIP2
[25] ARF5 --AGAP1     ARF5 --ASAP2     ARF5 --COPZ1     M6PR --GGA3
[29] M6PR --VTI1A     M6PR --TGOLN2    M6PR --GGA2      M6PR --GGA1
+ ... omitted several edges

$biogrid
IGRAPH 21b965d UN-- 20169 959426 --
+ attr: name (v/c), source (e/c)
+ edges from 21b965d (vertex names):
 [1] MAP2K4--FLNC     MYPN  --ACTN2    ACVR1 --FNTA     GATA2 --PML
 [5] RPA2  --STAT3    ARF1  --GGA3     ARF3  --ARFIP2   ARF3  --ARFIP1
 [9] XRN1  --ALDOA    APP   --APPBP2   APLP1 --DAB1     CITED2--TFAP2A
[13] EP300 --TFAP2A   APOB  --MTTP     ARRB2 --RALGDS   CSF1R --GRB2
[17] PRRC2A--GRB2     LSM1  --NARS     SLC4A1--SLC4A1AP BCL3  --BARD1
[21] ADRB1 --GIPC1    BRCA1 --ATF1     BRCA1 --MSH2     BRCA1 --BARD1
[25] BRCA1 --MSH6     ARVCF --CDH15    PCBD1 --CACNA1C  PSEN2 --CAPN1
[29] CAPN3 --TTN      ITPR1 --CA8      MAGI1 --CTNNB1   RB1   --CUX1
+ ... omitted several edges

$intact
IGRAPH 6ba410c UN-- 5597 20870 --
+ attr: name (v/c), source (e/c)
+ edges from 6ba410c (vertex names):
 [1] MDM2    --TP53    MDM2    --TP53    CDK4    --CCND1   CDK4    --CCND1
 [5] CCNT1   --CDK9    EIF4EBP1--EIF4E   BCL2L1  --BAD     CASP8   --FADD
 [9] HRAS    --RAF1    HRAS    --RAF1    EGFR    --SHC1    CBL     --SH3KBP1
[13] CBL     --SH3KBP1 PEX3    --PEX19   RAD51D  --XRCC2   EIF4EBP1--EIF4E
[17] BRCA1   --BRIP1   BRCA1   --BRIP1   MYC     --MAX     BRCA2   --RAD51
[21] EGFR    --GRB2    GRB2    --SHC1    BRCA2   --RAD51   EIF4A3  --CASC3
[25] RAC1    --PAK1    LSM2    --LSM3    CSNK2B  --CSNK2A1 CHUK    --IKBKG
[29] IKBKB   --IKBKG   CHUK    --IKBKG   IKBKB   --IKBKG   LSM2    --LSM3
+ ... omitted several edges

In [ ]:
visualize_ppi_network(networkds[["string"]], interactive = TRUE)

Warning message in visualize_ppi_network(networkds[["string"]], interactive = TRUE):
“visNetwork package not available, falling back to static plot”

ERROR: Error in cut.default(edge_weights, breaks = length(unique(edge_weights))): invalid number of intervals

In [ ]:
modules <- readRDS("inst/extdata/rmp_modules.rds")
exp_data <- readRDS("data-raw/GSE26378_GPL570_gene_expression.rds")
pheno_data <- readRDS("data-raw/GSE26378_GPL570_phenotype.rds")

In [ ]:
sample_condition <- pheno_data %>%
    dplyr::select(`disease state:ch1`) %>%
    dplyr::mutate(condition = ifelse(`disease state:ch1` == "septic shock patient", "case", "control"))
sample_condition_list <- sample_condition$condition
names(sample_condition_list) <- rownames(sample_condition)
sample_condition_list

GSM647527 GSM647528 GSM647529 GSM647530 GSM647531 GSM647532 GSM647533 GSM647534
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647535 GSM647536 GSM647537 GSM647538 GSM647539 GSM647540 GSM647541 GSM647542
   "case" "control" "control" "control" "control"    "case"    "case"    "case"
GSM647543 GSM647544 GSM647545 GSM647546 GSM647547 GSM647548 GSM647549 GSM647550
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647551 GSM647552 GSM647553 GSM647554 GSM647555 GSM647556 GSM647557 GSM647558
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647559 GSM647560 GSM647561 GSM647562 GSM647563 GSM647564 GSM647565 GSM647566
   "case"    "case"    "case"    "case"    "case"    "case"    "case" "control"
GSM647567 GSM647568 GSM647569 GSM647570 GSM647571 GSM647572 GSM647573 GSM647574
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647575 GSM647576 GSM647577 GSM647578 GSM647579 GSM647580 GSM647581 GSM647582
"control"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647583 GSM647584 GSM647585 GSM647586 GSM647587 GSM647588 GSM647589 GSM647590
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647591 GSM647592 GSM647593 GSM647594 GSM647595 GSM647596 GSM647597 GSM647598
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647599 GSM647600 GSM647601 GSM647602 GSM647603 GSM647604 GSM647605 GSM647606
   "case"    "case"    "case"    "case"    "case" "control" "control" "control"
GSM647607 GSM647608 GSM647609 GSM647610 GSM647611 GSM647612 GSM647613 GSM647614
"control" "control"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647615 GSM647616 GSM647617 GSM647618 GSM647619 GSM647620 GSM647621 GSM647622
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647623 GSM647624 GSM647625 GSM647626 GSM647627 GSM647628 GSM647629
"control" "control" "control" "control"    "case"    "case"    "case"

In [ ]:
results <- final_integrated_analysis(exp_data, sample_condition_list, modules,
    module_pairs = NULL,
    min_samples = 3, activity_method = "gsva"
)

ERROR: Error in final_integrated_analysis(exp_data, sample_condition_list, modules, : No modules with sufficient genes (minimum 3 genes)

In [ ]:
results <- intra_gene_pair(exp_data, sample_condition_list, modules[[28]]$genes,
     min_samples = 3
)

In [ ]:
modules[[28]]$target_proteins

[1] "METTL1" "PUS1"   "PUS3"   "PUS7"   "TRUB1"  "WDR4"

In [ ]:
results %>% arrange(case_pattern_ratio)

              gene1   gene2    p_value      odds_ratio case_pattern_ratio
odds ratio90  TRIT1   TRMT10A  1.604438e-04 0.11174990 0.09756098
odds ratio103 TRUB1   USP2-AS1 1.487620e-06 0.07231636 0.12195122
odds ratio102 TRUB1   WDR4     3.104934e-06 0.08041801 0.13414634
odds ratio94  TRIT1   USP2-AS1 6.316758e-04 0.15967806 0.14634146
odds ratio27  PUS1    PUS10    1.174836e-05 0.09733087 0.15853659
odds ratio31  PUS1    RPUSD1   5.984485e-05 0.11932821 0.15853659
odds ratio89  RPUSD2  USP2-AS1 2.655909e-04 0.14499551 0.15853659
odds ratio93  TRIT1   WDR4     2.655909e-04 0.14499551 0.15853659
odds ratio30  PUS1    PUSL1    2.982467e-03 0.19113129 0.17073171
odds ratio61  PUS7    RPUSD1   3.807016e-06 0.08521619 0.17073171
odds ratio88  RPUSD2  WDR4     1.441869e-08 0.03905683 0.18292683
odds ratio91  TRIT1   TRMT5    1.629383e-03 0.18565479 0.19512195
odds ratio37  PUS1    WDR4     6.598824e-06 0.09059590 0.21951220
odds ratio60  PUS7    PUSL1    9.033590e-04 0.17675393 0.21951220
odds ratio28  PUS1    PUS3     1.216305e-03 0.18930513 0.23170732
odds ratio38  PUS1    USP2-AS1 6.221523e-03 0.23011735 0.23170732
odds ratio67  PUS7    WDR4     1.216305e-03 0.18930513 0.23170732
odds ratio3   FAAH2   PUS3     8.668674e-03 0.26217410 0.25609756
odds ratio13  FAAH2   USP2-AS1 8.668674e-03 0.26217410 0.25609756
odds ratio34  PUS1    TRMT10A  6.961442e-04 0.17564706 0.25609756
odds ratio64  PUS7    TRMT10A  1.105756e-01 0.40728405 0.26829268
odds ratio65  PUS7    TRMT5    1.734795e-02 0.27896219 0.26829268
odds ratio68  PUS7    USP2-AS1 1.508564e-03 0.18687842 0.26829268
odds ratio2   FAAH2   PUS10    1.797155e-03 0.19846361 0.28048780
odds ratio6   FAAH2   RPUSD1   6.426203e-04 0.15920756 0.28048780
odds ratio16  METTL1  PUS3     5.204917e-03 0.24371647 0.28048780
odds ratio35  PUS1    TRMT5    4.120644e-02 0.35837739 0.28048780
odds ratio86  RPUSD2  TRMT5    4.120644e-02 0.35837739 0.28048780
odds ratio19  METTL1  RPUSD1   9.641420e-03 0.25846449 0.29268293
odds ratio12  FAAH2   WDR4     2.292785e-03 0.20247474 0.31707317
⋮             ⋮       ⋮        ⋮            ⋮          ⋮
odds ratio66  PUS7    TRUB1    9.641420e-03  3.869003  0.7073171
odds ratio84  RPUSD2  TRIT1    4.398816e-01  1.481236  0.7073171
odds ratio92  TRIT1   TRUB1    3.571884e-02  2.964333  0.7317073
odds ratio4   FAAH2   PUS7     1.767427e-01  2.160553  0.7439024
odds ratio8   FAAH2   TRIT1    1.615823e-01  2.156910  0.7560976
odds ratio20  METTL1  RPUSD2   3.009537e-03  4.944258  0.7560976
odds ratio33  PUS1    TRIT1    5.747514e-02  2.786351  0.7560976
odds ratio21  METTL1  TRIT1    3.288445e-02  2.977372  0.7682927
odds ratio87  RPUSD2  TRUB1    6.221523e-03  4.345609  0.7682927
odds ratio7   FAAH2   RPUSD2   9.033590e-04  5.657583  0.7804878
odds ratio17  METTL1  PUS7     2.785341e-03  4.654586  0.7804878
odds ratio40  PUS10   PUS7     2.067013e-03  4.999291  0.7926829
odds ratio24  METTL1  TRUB1    2.888807e-04  6.545643  0.8048780
odds ratio77  RPUSD1  RPUSD2   3.012998e-05  9.347404  0.8048780
odds ratio11  FAAH2   TRUB1    9.218337e-03  3.993058  0.8170732
odds ratio36  PUS1    TRUB1    4.913260e-04  6.230592  0.8170732
odds ratio50  PUS3    PUS7     1.045059e-04  7.681947  0.8292683
odds ratio53  PUS3    RPUSD2   5.690211e-07 14.959592  0.8292683
odds ratio78  RPUSD1  TRIT1    1.045059e-04  7.681947  0.8292683
odds ratio43  PUS10   RPUSD2   1.174836e-05 10.274232  0.8414634
odds ratio70  PUSL1   RPUSD2   2.655909e-04  6.896765  0.8414634
odds ratio81  RPUSD1  TRUB1    6.171957e-06 11.263484  0.8536585
odds ratio99  TRMT5   TRUB1    3.300840e-05  9.188510  0.8536585
odds ratio54  PUS3    TRIT1    4.760580e-07 15.472864  0.8658537
odds ratio74  PUSL1   TRUB1    3.104934e-06 12.435025  0.8658537
odds ratio47  PUS10   TRUB1    2.867491e-07 17.629044  0.9024390
odds ratio57  PUS3    TRUB1    4.195357e-09 27.881876  0.9024390
odds ratio44  PUS10   TRIT1    7.908221e-07 16.605284  0.9146341
odds ratio71  PUSL1   TRIT1    4.852696e-06 13.696309  0.9146341
odds ratio96  TRMT10A TRUB1    3.188291e-08 29.686583  0.9512195
              control_pattern_ratio case_correlation control_correlation
odds ratio90  0.4761905              0.305520044      0.50175625
odds ratio103 0.6666667             -0.408006085     -0.59215232
odds ratio102 0.6666667             -0.485049010     -0.31832491
odds ratio94  0.5238095             -0.377018941     -0.44891499
odds ratio27  0.6666667             -0.083284347      0.08015272
odds ratio31  0.6190476             -0.188884410     -0.11417879
odds ratio89  0.5714286              0.012420140      0.22426609
odds ratio93  0.5714286             -0.270329525     -0.24416431
odds ratio30  0.5238095              0.433348313      0.30552241
odds ratio61  0.7142857             -0.315550724     -0.27731682
odds ratio88  0.8571429             -0.050710780      0.12592601
odds ratio91  0.5714286              0.360745998      0.40018312
odds ratio37  0.7619048              0.008033744      0.43742741
odds ratio60  0.6190476              0.350274385     -0.03974345
odds ratio28  0.6190476             -0.039796755      0.20704940
odds ratio38  0.5714286             -0.341612452     -0.03531434
odds ratio67  0.6190476             -0.249347707     -0.28805111
odds ratio3   0.5714286             -0.262170223      0.10800310
odds ratio13  0.5714286              0.392587304     -0.34393160
odds ratio34  0.6666667              0.092389740     -0.12467816
odds ratio64  0.4761905              0.280009906      0.54459198
odds ratio65  0.5714286              0.362989318      0.44332698
odds ratio68  0.6666667             -0.405621641     -0.42021130
odds ratio2   0.6666667             -0.198700199     -0.04942954
odds ratio6   0.7142857              0.089634427     -0.20583233
odds ratio16  0.6190476              0.066200472     -0.12943998
odds ratio35  0.5238095              0.459363078      0.45008739
odds ratio86  0.5238095              0.201358717      0.32374837
odds ratio19  0.6190476              0.070415243      0.18041334
odds ratio12  0.6666667             -0.186511583     -0.31591304
⋮             ⋮                     ⋮                ⋮
odds ratio66  0.3809524              0.70633473       0.779854575
odds ratio84  0.6190476              0.53339678      -0.096351378
odds ratio92  0.4761905              0.75661607       0.546498338
odds ratio4   0.5714286              0.28386150       0.259360976
odds ratio8   0.5714286              0.10900530      -0.051664699
odds ratio20  0.3809524              0.45228120      -0.053105308
odds ratio33  0.5238095              0.64436234       0.060773318
odds ratio21  0.5238095              0.12952982       0.182714948
odds ratio87  0.4285714              0.28815471      -0.060751395
odds ratio7   0.3809524              0.48637662      -0.023229314
odds ratio17  0.4285714              0.45172217       0.096856203
odds ratio40  0.4285714              0.19036745       0.205583505
odds ratio24  0.3809524              0.11989506      -0.010963316
odds ratio77  0.2857143             -0.03160024       0.266203421
odds ratio11  0.5238095              0.11360607       0.329695458
odds ratio36  0.4285714              0.43693379       0.056158874
odds ratio50  0.3809524              0.10716343       0.644697837
odds ratio53  0.2380952             -0.35849168      -0.007781517
odds ratio78  0.3809524             -0.47665753      -0.216938449
odds ratio43  0.3333333             -0.18879257       0.202946130
odds ratio70  0.4285714              0.26598670       0.031793246
odds ratio81  0.3333333             -0.45887454      -0.434635376
odds ratio99  0.3809524              0.42554964       0.460493537
odds ratio54  0.2857143             -0.10658713       0.386538501
odds ratio74  0.3333333              0.26183204      -0.230722253
odds ratio47  0.3333333              0.31734291       0.064387926
odds ratio57  0.2380952              0.24375025       0.691236929
odds ratio44  0.3809524              0.12494685       0.357386788
odds ratio71  0.4285714              0.31970186       0.145945064
odds ratio96  0.3809524              0.62758370       0.697607201
              correlation_change adj_p_value  significant
odds ratio90  -0.196236203       7.657546e-04  TRUE
odds ratio103  0.184146235       1.952501e-05  TRUE
odds ratio102 -0.166724099       3.260181e-05  TRUE
odds ratio94   0.071896045       2.326729e-03  TRUE
odds ratio27  -0.163437069       7.709862e-05  TRUE
odds ratio31  -0.074705622       3.307215e-04  TRUE
odds ratio89  -0.211845951       1.115482e-03  TRUE
odds ratio93  -0.026165213       1.115482e-03  TRUE
odds ratio30   0.127825901       7.348870e-03  TRUE
odds ratio61  -0.038233899       3.633970e-05  TRUE
odds ratio88  -0.176636787       7.569814e-07  TRUE
odds ratio91  -0.039437118       4.623926e-03  TRUE
odds ratio37  -0.429393670       4.949118e-05  TRUE
odds ratio60   0.390017837       2.964147e-03  TRUE
odds ratio28  -0.246846153       3.648914e-03  TRUE
odds ratio38  -0.306298113       1.389915e-02  TRUE
odds ratio67   0.038703400       3.648914e-03  TRUE
odds ratio3   -0.370173323       1.857573e-02  TRUE
odds ratio13   0.736518907       1.857573e-02  TRUE
odds ratio34   0.217067905       2.436505e-03  TRUE
odds ratio64  -0.264582071       1.527689e-01 FALSE
odds ratio65  -0.080337667       3.252740e-02  TRUE
odds ratio68   0.014589655       4.399979e-03  TRUE
odds ratio2   -0.149270655       4.965824e-03  TRUE
odds ratio6    0.295466754       2.326729e-03  TRUE
odds ratio16   0.195640453       1.242082e-02  TRUE
odds ratio35   0.009275687       6.457725e-02 FALSE
odds ratio86  -0.122389649       6.457725e-02 FALSE
odds ratio19  -0.109998095       1.946825e-02  TRUE
odds ratio12   0.129401455       6.018560e-03  TRUE
⋮             ⋮                  ⋮            ⋮
odds ratio66  -0.07351985        1.946825e-02  TRUE
odds ratio84   0.62974816        5.189614e-01 FALSE
odds ratio92   0.21011774        5.769966e-02 FALSE
odds ratio4    0.02450053        2.291110e-01 FALSE
odds ratio8    0.16066999        2.120768e-01 FALSE
odds ratio20   0.50538651        7.348870e-03  TRUE
odds ratio33   0.58358902        8.621272e-02 FALSE
odds ratio21  -0.05318513        5.395106e-02 FALSE
odds ratio87   0.34890611        1.389915e-02  TRUE
odds ratio7    0.50960594        2.964147e-03  TRUE
odds ratio17   0.35486597        7.133192e-03  TRUE
odds ratio40  -0.01521605        5.565034e-03  TRUE
odds ratio24   0.13085838        1.166634e-03  TRUE
odds ratio77  -0.29780366        1.860970e-04  TRUE
odds ratio11  -0.21608939        1.935851e-02  TRUE
odds ratio36   0.38077492        1.910712e-03  TRUE
odds ratio50  -0.53753441        5.225294e-04  TRUE
odds ratio53  -0.35071016        9.957870e-06  TRUE
odds ratio78  -0.25971908        5.225294e-04  TRUE
odds ratio43  -0.39173870        7.709862e-05  TRUE
odds ratio70   0.23419345        1.115482e-03  TRUE
odds ratio81  -0.02423917        4.949118e-05  TRUE
odds ratio99  -0.03494390        1.925490e-04  TRUE
odds ratio54  -0.49312563        9.957870e-06  TRUE
odds ratio74   0.49255429        3.260181e-05  TRUE
odds ratio47   0.25295499        7.527165e-06  TRUE
odds ratio57  -0.44748668        4.405124e-07  TRUE
odds ratio44  -0.23243994        1.186233e-05  TRUE
odds ratio71   0.17375680        4.246109e-05  TRUE
odds ratio96  -0.07002350        1.115902e-06  TRUE

In [ ]:
modules[[28]]$target_proteins

[1] "METTL1" "PUS1"   "PUS3"   "PUS7"   "TRUB1"  "WDR4"

In [ ]:
exp_data[c("KLRF1", "RHOT1"), ] %>%
    t() %>%
    as.data.frame() %>%
    dplyr::mutate(large = KLRF1 > RHOT1) %>%
    tibble::rownames_to_column("sample") %>%
    left_join(sample_condition %>% tibble::rownames_to_column("sample"), by = "sample") %>%
    group_by(condition, large) %>%
    summarise(n = dplyr::n())

`summarise()` has grouped output by 'condition'. You can override using the
`.groups` argument.

  condition large n
1 case      FALSE 78
2 case       TRUE  4
3 control   FALSE  4
4 control    TRUE 17

In [ ]:
sample_condition

          disease state:ch1    condition
GSM647527 septic shock patient case
GSM647528 septic shock patient case
GSM647529 septic shock patient case
GSM647530 septic shock patient case
GSM647531 septic shock patient case
GSM647532 septic shock patient case
GSM647533 normal control       control
GSM647534 normal control       control
GSM647535 septic shock patient case
GSM647536 normal control       control
GSM647537 normal control       control
GSM647538 normal control       control
GSM647539 normal control       control
GSM647540 septic shock patient case
GSM647541 septic shock patient case
GSM647542 septic shock patient case
GSM647543 septic shock patient case
GSM647544 septic shock patient case
GSM647545 septic shock patient case
GSM647546 septic shock patient case
GSM647547 septic shock patient case
GSM647548 septic shock patient case
GSM647549 septic shock patient case
GSM647550 septic shock patient case
GSM647551 septic shock patient case
GSM647552 septic shock patient case
GSM647553 septic shock patient case
GSM647554 septic shock patient case
GSM647555 septic shock patient case
GSM647556 septic shock patient case
⋮         ⋮                    ⋮
GSM647600 septic shock patient case
GSM647601 septic shock patient case
GSM647602 septic shock patient case
GSM647603 septic shock patient case
GSM647604 normal control       control
GSM647605 normal control       control
GSM647606 normal control       control
GSM647607 normal control       control
GSM647608 normal control       control
GSM647609 septic shock patient case
GSM647610 septic shock patient case
GSM647611 septic shock patient case
GSM647612 septic shock patient case
GSM647613 septic shock patient case
GSM647614 septic shock patient case
GSM647615 septic shock patient case
GSM647616 septic shock patient case
GSM647617 septic shock patient case
GSM647618 septic shock patient case
GSM647619 septic shock patient case
GSM647620 septic shock patient case
GSM647621 normal control       control
GSM647622 normal control       control
GSM647623 normal control       control
GSM647624 normal control       control
GSM647625 normal control       control
GSM647626 normal control       control
GSM647627 septic shock patient case
GSM647628 septic shock patient case
GSM647629 septic shock patient case

In [ ]:
sample_condition_list

GSM647527 GSM647528 GSM647529 GSM647530 GSM647531 GSM647532 GSM647533 GSM647534
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647535 GSM647536 GSM647537 GSM647538 GSM647539 GSM647540 GSM647541 GSM647542
   "case" "control" "control" "control" "control"    "case"    "case"    "case"
GSM647543 GSM647544 GSM647545 GSM647546 GSM647547 GSM647548 GSM647549 GSM647550
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647551 GSM647552 GSM647553 GSM647554 GSM647555 GSM647556 GSM647557 GSM647558
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647559 GSM647560 GSM647561 GSM647562 GSM647563 GSM647564 GSM647565 GSM647566
   "case"    "case"    "case"    "case"    "case"    "case"    "case" "control"
GSM647567 GSM647568 GSM647569 GSM647570 GSM647571 GSM647572 GSM647573 GSM647574
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647575 GSM647576 GSM647577 GSM647578 GSM647579 GSM647580 GSM647581 GSM647582
"control"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647583 GSM647584 GSM647585 GSM647586 GSM647587 GSM647588 GSM647589 GSM647590
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647591 GSM647592 GSM647593 GSM647594 GSM647595 GSM647596 GSM647597 GSM647598
   "case"    "case"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647599 GSM647600 GSM647601 GSM647602 GSM647603 GSM647604 GSM647605 GSM647606
   "case"    "case"    "case"    "case"    "case" "control" "control" "control"
GSM647607 GSM647608 GSM647609 GSM647610 GSM647611 GSM647612 GSM647613 GSM647614
"control" "control"    "case"    "case"    "case"    "case"    "case"    "case"
GSM647615 GSM647616 GSM647617 GSM647618 GSM647619 GSM647620 GSM647621 GSM647622
   "case"    "case"    "case"    "case"    "case"    "case" "control" "control"
GSM647623 GSM647624 GSM647625 GSM647626 GSM647627 GSM647628 GSM647629
"control" "control" "control" "control"    "case"    "case"    "case"

In [ ]:
results %>% arrange(p_value)

              gene1    gene2    p_value      odds_ratio  case_pattern_ratio
odds ratio703 KLRF1    RHOT1    2.596360e-12  0.01345648 0.04878049
odds ratio713 KLRF1    TYROBP   1.031573e-11  0.01428514 0.04878049
odds ratio456 DSTYK    KLRC4    2.850361e-11 51.37798682 0.90243902
odds ratio705 KLRF1    SCCPDH   3.501772e-11  0.01758212 0.04878049
odds ratio866 PPTC7    TYROBP   3.984040e-11  0.02019869 0.07317073
odds ratio691 KLRD1    TYROBP   8.237410e-11  0.02204168 0.10975610
odds ratio714 KLRF1    USP30    1.387661e-10  0.02203915 0.06097561
odds ratio692 KLRD1    USP30    2.220829e-10  0.02468593 0.12195122
odds ratio765 MTCH1    SCCPDH   3.938140e-10  0.02227625 0.04878049
odds ratio660 KLRC4    SCCPDH   4.797438e-10  0.02653193 0.07317073
odds ratio683 KLRD1    SCCPDH   4.797438e-10  0.02653193 0.07317073
odds ratio941 TMEM184B TYROBP   5.634806e-10  0.02739098 0.13414634
odds ratio668 KLRC4    TYROBP   1.065510e-09  0.03084835 0.10975610
odds ratio690 KLRD1    TRABD    1.065510e-09  0.03084835 0.10975610
odds ratio596 JTB      KLRC4    1.355077e-09 33.14786769 0.85365854
odds ratio667 KLRC4    TRABD    1.470203e-09  0.02792551 0.06097561
odds ratio707 KLRF1    SLC25A20 1.470203e-09  0.02792551 0.06097561
odds ratio706 KLRF1    SLC25A16 1.485237e-09  0.03117273 0.08536585
odds ratio681 KLRD1    RHOT1    2.736842e-09  0.03459707 0.12195122
odds ratio685 KLRD1    SLC25A20 2.736842e-09  0.03459707 0.12195122
odds ratio588 ITM2A    SLC25A33 3.792937e-09  0.02755344 0.04878049
odds ratio487 FAM63B   KLRD1    4.798796e-09 29.66611370 0.92682927
odds ratio545 HSDL1    KLRF1    4.798796e-09 29.66611370 0.92682927
odds ratio763 MTCH1    RHOT1    6.623288e-09  0.03842740 0.13414634
odds ratio394 DGCR2    KLRD1    6.623288e-09 26.02309727 0.86585366
odds ratio457 DSTYK    KLRD1    6.623288e-09 26.02309727 0.86585366
odds ratio597 JTB      KLRD1    6.623288e-09 26.02309727 0.86585366
odds ratio694 KLRF1    MICB     8.199208e-09  0.02513652 0.03658537
odds ratio929 SLC25A33 TYROBP   9.557476e-09  0.03091987 0.21951220
odds ratio623 KIAA1586 KLRF1    1.028777e-08 90.83271604 0.98780488
⋮             ⋮        ⋮        ⋮            ⋮           ⋮
odds ratio72  ARL5B    RHOBTB3  1            1.1158037   0.4268293
odds ratio74  ARL5B    SAYSD1   1            0.9449830   0.4146341
odds ratio86  ATP12A   ATP7B    1            0.9129895   0.5487805
odds ratio110 ATP12A   NSUN3    1            1.1124644   0.5975610
odds ratio120 ATP12A   SLC35D2  1            1.0659945   0.6341463
odds ratio127 ATP1B1   ATP8B2   1            0.8989052   0.4024390
odds ratio130 ATP1B1   CLEC2D   1            1.0582200   0.5853659
odds ratio153 ATP1B1   RHOBTB3  1            1.0521393   0.5365854
odds ratio172 ATP7B    DNAJC11  1            1.0724033   0.4878049
odds ratio179 ATP7B    KIAA1586 1            0.9053299   0.4512195
odds ratio244 CD226    CLEC2D   1            0.9129895   0.5487805
odds ratio340 CLEC2D   SAYSD1   1            1.1522463   0.3658537
odds ratio347 CLEC2D   TMEM184B 1            0.9110100   0.4268293
odds ratio392 DGCR2    KIAA1586 1            1.0396119   0.3902439
odds ratio428 DNAJC11  MBLAC2   1            0.9417177   0.5853659
odds ratio450 DSTYK    FAM63B   1            0.9819843   0.3292683
odds ratio627 KIAA1586 MTCH2    1            1.0521393   0.5365854
odds ratio628 KIAA1586 NCR2     1            1.1045697   0.5487805
odds ratio656 KLRC4    PPTC7    1            0.9129895   0.5487805
odds ratio729 MBLAC2   SLC25A33 1            0.9129895   0.5487805
odds ratio753 MICB     TRABD    1            0.8989052   0.4024390
odds ratio801 NCR2     SLC25A16 1            1.0183462   0.6707317
odds ratio817 NKAIN2   SLC25A16 1            0.8962150   0.5731707
odds ratio876 RHOBTB3  TMEM184B 1            1.1045697   0.5487805
odds ratio888 RHOT1    TRABD    1            1.0366762   0.3414634
odds ratio913 SLC25A16 TACR3    1            0.9292464   0.3170732
odds ratio922 SLC25A20 TRABD    1            1.0300068   0.1951220
odds ratio927 SLC25A33 TMEM184B 1            1.1045697   0.5487805
odds ratio159 ATP1B1   SLC25A33 1            0.9587181   0.5609756
odds ratio771 MTCH1    TMEM184B 1            1.0430595   0.4390244
              control_pattern_ratio case_correlation control_correlation
odds ratio703 0.8095238              0.37195082       0.41706782
odds ratio713 0.7619048              0.03744307      -0.44171902
odds ratio456 0.1428571             -0.21369771       0.11417772
odds ratio705 0.7619048              0.13498778       0.15396858
odds ratio866 0.8095238              0.48356183       0.30806635
odds ratio691 0.8571429              0.20183942      -0.12244349
odds ratio714 0.7619048             -0.07550657      -0.13153228
odds ratio692 0.8571429              0.11257776       0.06576940
odds ratio765 0.7142857              0.05992875       0.21934357
odds ratio660 0.7619048              0.11155051      -0.03106498
odds ratio683 0.7619048              0.26229257       0.05071156
odds ratio941 0.8571429              0.26053197       0.47665363
odds ratio668 0.8095238             -0.07637585      -0.29619816
odds ratio690 0.8095238             -0.26917084       0.02238242
odds ratio596 0.1428571              0.16102160       0.39480137
odds ratio667 0.7142857             -0.53973479       0.04653763
odds ratio707 0.7142857              0.29211999      -0.07542754
odds ratio706 0.7619048              0.27853438       0.07968724
odds ratio681 0.8095238              0.31089356      -0.07002139
odds ratio685 0.8095238              0.39315574      -0.03120609
odds ratio588 0.6666667              0.69104901       0.57550814
odds ratio487 0.2857143              0.17755936       0.54083914
odds ratio545 0.2857143              0.43993437       0.01084798
odds ratio763 0.8095238              0.37108521       0.41596813
odds ratio394 0.1904762             -0.45026307      -0.33242618
odds ratio457 0.1904762             -0.13740704       0.06385326
odds ratio597 0.1904762              0.34900155       0.48856551
odds ratio694 0.6190476              0.24633157      -0.22530651
odds ratio929 0.9047619             -0.09561428       0.01553236
odds ratio623 0.4285714              0.56828442       0.32575763
⋮             ⋮                     ⋮                ⋮
odds ratio72  0.3809524             -0.034736252     -0.065106070
odds ratio74  0.4285714              0.536150897      0.151010187
odds ratio86  0.5714286              0.322261895      0.096431904
odds ratio110 0.5714286              0.355729946      0.197219714
odds ratio120 0.6190476             -0.180918568     -0.101273603
odds ratio127 0.4285714             -0.092942636     -0.336548636
odds ratio130 0.5714286              0.127238066      0.265601656
odds ratio153 0.5238095              0.383318581      0.471216229
odds ratio172 0.4761905              0.148178617      0.168726930
odds ratio179 0.4761905              0.092059371     -0.130346183
odds ratio244 0.5714286              0.464241840      0.739068606
odds ratio340 0.3333333              0.554620189      0.277223918
odds ratio347 0.4285714              0.244057978     -0.188137725
odds ratio392 0.3809524             -0.416449926     -0.004101903
odds ratio428 0.5714286             -0.321683877     -0.339855118
odds ratio450 0.3333333              0.107567795      0.304044639
odds ratio627 0.5238095              0.184482060      0.240978523
odds ratio628 0.5238095             -0.267418564     -0.327167814
odds ratio656 0.5714286              0.271952327      0.109772545
odds ratio729 0.5714286              0.371246204      0.421757199
odds ratio753 0.4285714              0.186095204     -0.286427073
odds ratio801 0.6666667             -0.038800103     -0.250398977
odds ratio817 0.5714286              0.021760003      0.048097307
odds ratio876 0.5238095             -0.001086428     -0.463279965
odds ratio888 0.3333333              0.108970445     -0.257414890
odds ratio913 0.3333333              0.077416379     -0.398580908
odds ratio922 0.1904762              0.245517356      0.217567426
odds ratio927 0.5238095              0.285788048      0.004279411
odds ratio159 0.5714286              0.249327775      0.005318554
odds ratio771 0.4285714              0.536888804      0.764912244
              correlation_change adj_p_value  significant
odds ratio703 -0.04511699        2.456157e-09 TRUE
odds ratio713  0.47916209        4.879340e-09 TRUE
odds ratio456 -0.32787543        7.537805e-09 TRUE
odds ratio705 -0.01898079        7.537805e-09 TRUE
odds ratio866  0.17549548        7.537805e-09 TRUE
odds ratio691  0.32428291        1.298765e-08 TRUE
odds ratio714  0.05602571        1.875324e-08 TRUE
odds ratio692  0.04680837        2.626131e-08 TRUE
odds ratio765 -0.15941482        4.125797e-08 TRUE
odds ratio660  0.14261549        4.125797e-08 TRUE
odds ratio683  0.21158101        4.125797e-08 TRUE
odds ratio941 -0.21612166        4.442105e-08 TRUE
odds ratio668  0.21982231        7.199806e-08 TRUE
odds ratio690 -0.29155326        7.199806e-08 TRUE
odds ratio596 -0.23377976        7.805747e-08 TRUE
odds ratio667 -0.58627242        7.805747e-08 TRUE
odds ratio707  0.36754753        7.805747e-08 TRUE
odds ratio706  0.19884714        7.805747e-08 TRUE
odds ratio681  0.38091495        1.294526e-07 TRUE
odds ratio685  0.42436183        1.294526e-07 TRUE
odds ratio588  0.11554087        1.708628e-07 TRUE
odds ratio487 -0.36327978        1.973765e-07 TRUE
odds ratio545  0.42908639        1.973765e-07 TRUE
odds ratio763 -0.04488292        2.320604e-07 TRUE
odds ratio394 -0.11783689        2.320604e-07 TRUE
odds ratio457 -0.20126030        2.320604e-07 TRUE
odds ratio597 -0.13956396        2.320604e-07 TRUE
odds ratio694  0.47163809        2.770161e-07 TRUE
odds ratio929 -0.11114664        3.117715e-07 TRUE
odds ratio623  0.24252679        3.241510e-07 TRUE
⋮             ⋮                  ⋮            ⋮
odds ratio72   0.03036982        1            FALSE
odds ratio74   0.38514071        1            FALSE
odds ratio86   0.22582999        1            FALSE
odds ratio110  0.15851023        1            FALSE
odds ratio120 -0.07964496        1            FALSE
odds ratio127  0.24360600        1            FALSE
odds ratio130 -0.13836359        1            FALSE
odds ratio153 -0.08789765        1            FALSE
odds ratio172 -0.02054831        1            FALSE
odds ratio179  0.22240555        1            FALSE
odds ratio244 -0.27482677        1            FALSE
odds ratio340  0.27739627        1            FALSE
odds ratio347  0.43219570        1            FALSE
odds ratio392 -0.41234802        1            FALSE
odds ratio428  0.01817124        1            FALSE
odds ratio450 -0.19647684        1            FALSE
odds ratio627 -0.05649646        1            FALSE
odds ratio628  0.05974925        1            FALSE
odds ratio656  0.16217978        1            FALSE
odds ratio729 -0.05051100        1            FALSE
odds ratio753  0.47252228        1            FALSE
odds ratio801  0.21159887        1            FALSE
odds ratio817 -0.02633730        1            FALSE
odds ratio876  0.46219354        1            FALSE
odds ratio888  0.36638533        1            FALSE
odds ratio913  0.47599729        1            FALSE
odds ratio922  0.02794993        1            FALSE
odds ratio927  0.28150864        1            FALSE
odds ratio159  0.24400922        1            FALSE
odds ratio771 -0.22802344        1            FALSE

In [ ]:
modules

[[1]]
[[1]]$module_id
[1] "RC4_1"

[[1]]$genes
 [1] "ABCB6"      "ARL5B"      "ATP12A"     "ATP1B1"     "ATP7B"
 [6] "ATP8B2"     "C1ORF74"    "CD164L2"    "CD226"      "CD3D"
[11] "CLEC2D"     "CNNM4"      "DGCR2"      "DNAJC11"    "DSTYK"
[16] "FAM63B"     "GRPR"       "HSDL1"      "ITM2A"      "JTB"
[21] "KIAA1586"   "KLRC4"      "KLRD1"      "KLRF1"      "MBLAC2"
[26] "MICB"       "MTCH1"      "MTCH2"      "NCR2"       "NKAIN2"
[31] "NSUN3"      "PLD6"       "PPTC7"      "RHOBTB3"    "RHOT1"
[36] "SAYSD1"     "SCCPDH"     "SLC25A16"   "SLC25A20"   "SLC25A33"
[41] "SLC35D2"    "TACR3"      "TMEM184B"   "TRABD"      "TYROBP"
[46] "USP30"      "SLC25A10-2"

[[1]]$size
[1] 47

[[1]]$algorithm
[1] "FASTGREEDY"

[[1]]$depth
[1] 4

[[1]]$target_proteins
[1] "NSUN3"


[[2]]
[[2]]$module_id
[1] "RC5_1"

[[2]]$genes
 [1] "BHLHA15" "DAPL1"   "EIF1AD"  "EIF2D"   "EIF2S3B" "FAM111B" "G2E3"
 [8] "GAGE1"   "GAGE10"  "GAGE12C" "GAGE12D" "GAGE12E" "GAGE12F" "GAGE12G"
[15] "GAGE12H" "GAGE12J" "GAGE13"  "GAGE2A"  "GAGE2E"  "GIN1"    "HBA1"
[22] "HBS1L"   "IFRD1"   "LRRC47"  "MCTS1"   "PARP6"   "PARP8"   "PELO"
[29] "RIOK3"   "RPL41"   "RPS11"   "RPS15"   "RPS17"   "RPS18"   "RPS19"
[36] "RPS2"    "RPS21"   "RPS23"   "RPS24"   "RPS25"   "RPS26"   "RPS27A"
[43] "RPS28"   "RPS3"    "RPS3A"   "RPS8"    "SELENOP"

[[2]]$size
[1] 47

[[2]]$algorithm
[1] "FASTGREEDY"

[[2]]$depth
[1] 5

[[2]]$target_proteins
[1] "RPS25" "RPS26"


[[3]]
[[3]]$module_id
[1] "RC6_1"

[[3]]$genes
 [1] "CBX6"   "KAL1"   "MB21D1" "MEIOC"  "NMNAT1" "YTHDC2" "ZCCHC6" "ZNF107"
 [9] "ZNF121" "ZNF48"  "ZNF512" "ZNF800"

[[3]]$size
[1] 12

[[3]]$algorithm
[1] "FASTGREEDY"

[[3]]$depth
[1] 6

[[3]]$target_proteins
[1] "YTHDC2"


[[4]]
[[4]]$module_id
[1] "RC6_2"

[[4]]$genes
 [1] "ADARB1"  "CCDC137" "OASL"    "PRKRA"   "PURG"    "SPTY2D1" "TAF1A"
 [8] "TAF1B"   "TAF1C"   "TAF1D"   "TTF1"    "ZBTB47"  "ZNF184"  "ZNF273"
[15] "ZNF467"  "ZNF616"  "ZNF668"  "ZNF689"  "ZNF777"  "ZNF624"  "ZNF845"
[22] "ZNF92"   "ZNF791"

[[4]]$size
[1] 23

[[4]]$algorithm
[1] "FASTGREEDY"

[[4]]$depth
[1] 6

[[4]]$target_proteins
[1] "ADARB1"


[[5]]
[[5]]$module_id
[1] "RC6_1"

[[5]]$genes
 [1] "C3ORF17" "DDRGK1"  "DKC1"    "GAR1"    "GPATCH4" "HECTD1"  "NEPRO"
 [8] "NOM1"    "NOP10"   "NVL"     "PNMAL1"  "POP1"    "RBM4B"   "RPP25"
[15] "RPP30"   "TERC"

[[5]]$size
[1] 16

[[5]]$algorithm
[1] "FASTGREEDY"

[[5]]$depth
[1] 6

[[5]]$target_proteins
[1] "DKC1"


[[6]]
[[6]]$module_id
[1] "RC6_1"

[[6]]$genes
 [1] "BOP1"     "CEBPZ"    "DNAJC9"   "EBNA1BP2" "GNL1"     "GNL3"
 [7] "GNL3L"    "KCTD19"   "MAK16"    "NIP7"     "NLE1"     "NOC2L"
[13] "NOC3L"    "NOP2"     "NOP53"    "NSA2"     "NSUN5"    "NSUN6"
[19] "NSUN7"    "P2RY11"   "PAK1IP1"  "RPF1"     "RRP1"     "RRP15"
[25] "RRP1B"    "RSL24D1"  "TRDMT1"   "WDR74"

[[6]]$size
[1] 28

[[6]]$algorithm
[1] "FASTGREEDY"

[[6]]$depth
[1] 6

[[6]]$target_proteins
[1] "NSUN5" "NSUN6" "NSUN7"


[[7]]
[[7]]$module_id
[1] "RC6_2"

[[7]]$genes
 [1] "CDKL2"  "DDX10"  "DDX18"  "DDX47"  "DDX52"  "DDX56"  "GTPBP4" "IFI16"
 [9] "PES1"   "RANBP9" "TRMT6"  "WDR12"  "WDR18"

[[7]]$size
[1] 13

[[7]]$algorithm
[1] "FASTGREEDY"

[[7]]$depth
[1] 6

[[7]]$target_proteins
[1] "TRMT6"


[[8]]
[[8]]$module_id
[1] "RC5_1"

[[8]]$genes
 [1] "DDX21"     "DUX4"      "HNRNPA0"   "HNRNPF"    "HNRNPH3"   "HNRNPK"
 [7] "HNRNPM"    "HOXC-AS3"  "MATR3"     "MIR1-2"    "MIR107"    "MIR140"
[13] "MIR143"    "MIR15A"    "MIR16-2"   "MIR17"     "MIR18A"    "MIR199A1"
[19] "MIR200B"   "MIR206"    "MIR20A"    "MIR29B2"   "MIR92A1"   "MIR92A2"
[25] "NUDT21"    "PCDHA2"    "PTBP1"     "PTBP3"     "SYNCRIP"   "TRA2B"
[31] "YBX1"      "ZNF514"    "ZMIZ1-AS1" "SYT8"

[[8]]$size
[1] 34

[[8]]$algorithm
[1] "FASTGREEDY"

[[8]]$depth
[1] 5

[[8]]$target_proteins
[1] "YBX1"


[[9]]
[[9]]$module_id
[1] "RC5_2"

[[9]]$genes
[1] "CCDC178"      "IGF2BP1"      "MIR138-1"     "LOC100506797"

[[9]]$size
[1] 4

[[9]]$algorithm
[1] "FASTGREEDY"

[[9]]$depth
[1] 5

[[9]]$target_proteins
[1] "IGF2BP1"


[[10]]
[[10]]$module_id
[1] "RC5_3"

[[10]]$genes
 [1] "C2ORF49"   "DDX1"      "FAM98A"    "FAM98B"    "FIRRE"     "IGF2BP3"
 [7] "MIR106A"   "MIR10B"    "MIR141"    "MIR16-1"   "MIR18B"    "MIR199A2"
[13] "MIR222"    "MIR7-3"    "MIRLET7A2" "PRMT1"     "RNASE1"    "RTCB"
[19] "RTRAF"     "YBX3"      "ZBTB8OS"

[[10]]$size
[1] 21

[[10]]$algorithm
[1] "FASTGREEDY"

[[10]]$depth
[1] 5

[[10]]$target_proteins
[1] "IGF2BP3"


[[11]]
[[11]]$module_id
[1] "RC5_4"

[[11]]$genes
 [1] "C2ORF78"    "FAIM3"      "FGF11"      "HNRNPA1"    "HNRNPA2B1"
 [6] "HNRNPA3"    "HNRNPR"     "MATR3-2"    "MIR122"     "MIR200A"
[11] "MIR29A"     "MIR29B1"    "MIR429"     "MIR9-3"     "MIR98"
[16] "NONO"       "PRMT8"      "RBM14"      "RBM45"      "RN7SK"
[21] "SCARNA22"   "SFPQ"       "STRBP"      "TAF15"      "HNRNPA1P48"
[26] "HNRNPA1P70"

[[11]]$size
[1] 26

[[11]]$algorithm
[1] "FASTGREEDY"

[[11]]$depth
[1] 5

[[11]]$target_proteins
[1] "HNRNPA2B1"


[[12]]
[[12]]$module_id
[1] "RC5_1"

[[12]]$genes
 [1] "ACF"       "ALKBH5"    "ATXN2L"    "AVEN"      "CPEB1"     "FAM103A2P"
 [7] "FAM195A"   "GTPBP1"    "HERC2P4"   "LINC01541" "MCTS2P"    "RAF1"
[13] "RBMS1"     "SCARNA1"   "SMN1"      "STAU1"     "TSPYL5"    "XRN1"
[19] "ZCCHC11"   "SNORA81"

[[12]]$size
[1] 20

[[12]]$algorithm
[1] "FASTGREEDY"

[[12]]$depth
[1] 5

[[12]]$target_proteins
[1] "ALKBH5"


[[13]]
[[13]]$module_id
[1] "RC5_2"

[[13]]$genes
 [1] "APOBEC3F"  "ATXN2"     "CDKN2AIP"  "CELF1"     "DAZL"      "ELAVL2"
 [7] "ELAVL3"    "FAM120A"   "FAM195B"   "FTH1P3"    "FUBP1"     "GSPT2"
[13] "HNRNPC"    "IGF2BP2"   "LARP1"     "LARP1B"    "LARP4"     "LARP4B"
[19] "MBNL2"     "MKRN1"     "MOV10"     "MYCN"      "NUPL2"     "ORF1"
[25] "PABPC1"    "PABPC4"    "PABPC4L"   "PABPC5"    "PAIP1"     "PAIP2"
[31] "PAIP2B"    "PUM1"      "PUM2"      "RAVER1"    "RBM47"     "RNF216P1"
[37] "SCARNA5"   "SNORD22"   "SRRD"      "STAU2"     "TIAL1"     "ZCCHC3"
[43] "ZNF326"    "RTP3"      "ZCCHC24"   "PHKA2-AS1" "SHFL"      "TMED10P1"
[49] "OR6S1"

[[13]]$size
[1] 49

[[13]]$algorithm
[1] "FASTGREEDY"

[[13]]$depth
[1] 5

[[13]]$target_proteins
[1] "IGF2BP2"


[[14]]
[[14]]$module_id
[1] "RC6_1"

[[14]]$genes
 [1] "CSDE1"     "FBL"       "LINC00240" "LRRC16B"   "NUFIP2"    "PRRC2C"
 [7] "RNF113A"   "RPA4"      "TRIM56"    "YTHDF2"    "ZC3HAV1"   "ZNF93"
[13] "ZNF850"

[[14]]$size
[1] 13

[[14]]$algorithm
[1] "FASTGREEDY"

[[14]]$depth
[1] 6

[[14]]$target_proteins
[1] "YTHDF2"


[[15]]
[[15]]$module_id
[1] "RC6_2"

[[15]]$genes
 [1] "AGO1"      "AGO3"      "ANKRD17"   "CPEB4"     "EIF4ENIF1" "FAM120C"
 [7] "FUBP3"     "LSM14A"    "PRRC2A"    "PRRC2B"    "R3HDM1"    "SECISBP2"
[13] "SMG1"      "SMG6"      "TDRD3"     "YTHDF1"    "YTHDF3"    "ZC3H7A"

[[15]]$size
[1] 18

[[15]]$algorithm
[1] "FASTGREEDY"

[[15]]$depth
[1] 6

[[15]]$target_proteins
[1] "YTHDF1" "YTHDF3"


[[16]]
[[16]]$module_id
[1] "RC5_1"

[[16]]$genes
[1] "ADAR"      "ARHGEF10L" "ELAVL4"    "XRN2"

[[16]]$size
[1] 4

[[16]]$algorithm
[1] "FASTGREEDY"

[[16]]$depth
[1] 5

[[16]]$target_proteins
[1] "ADAR"


[[17]]
[[17]]$module_id
[1] "RC6_1"

[[17]]$genes
 [1] "ALYREF"    "C8ORF88"   "CLNS1A"    "DDX5"      "DHX15"     "FN1"
 [7] "ITGA4"     "KRT9"      "OR5AR1"    "PPIAP22"   "SND1"      "TARDBP"
[13] "VCAM1"     "VRK3"      "RPL23AP42" "MEMO1P1"

[[17]]$size
[1] 16

[[17]]$algorithm
[1] "FASTGREEDY"

[[17]]$depth
[1] 6

[[17]]$target_proteins
[1] "ALYREF"


[[18]]
[[18]]$module_id
[1] "RC5_2"

[[18]]$genes
 [1] "ACE2"         "ADGB"         "ANXA2P2"      "C2ORF43"      "CBLL1"
 [6] "CCAT1"        "DCD"          "FBXO39"       "GRM2"         "HRNR"
[11] "IGHV1-18"     "IGKV2-30"     "KBTBD3"       "LINC00152"    "LOC100128429"
[16] "LOC102724560" "MBD5"         "MBD6"         "NDN"          "NGB"
[21] "NKAPP1"       "OGT"          "OR13C4"       "RCC2"         "RNH1"
[26] "THOC3"        "TRIM28"       "UFL1"         "WTAP"         "ZNF253"
[31] "ZNF28"        "ZNF468"       "GAFA3"        "IGHD6-19"     "IGKV2-28"
[36] "LINC00336"    "USP17L23"     "ZNF354B"      "ZNF493"       "ZNF90"
[41] "ZNF37A"       "ZNF823"       "ZNF737"       "ZNF732"       "ZNF681"
[46] "ZNF728"       "ZNF98"

[[18]]$size
[1] 47

[[18]]$algorithm
[1] "FASTGREEDY"

[[18]]$depth
[1] 5

[[18]]$target_proteins
[1] "WTAP"


[[19]]
[[19]]$module_id
[1] "RC6_1"

[[19]]$genes
[1] "ABCF2"     "DHFRP1"    "DPPA2P2"   "HUWE1"     "METTL14"   "MIR548AJ1"
[7] "PSAT1P1"   "SRP9P1"

[[19]]$size
[1] 8

[[19]]$algorithm
[1] "FASTGREEDY"

[[19]]$depth
[1] 6

[[19]]$target_proteins
[1] "METTL14"


[[20]]
[[20]]$module_id
[1] "RC6_2"

[[20]]$genes
 [1] "ADARB2"   "EEF1A1"   "EEF1A1P5" "EEF1A2"   "EEF1D"    "FER1L6"
 [7] "HEXIM1"   "MAP1B"    "MEPCE"    "N6AMT2"   "PRPF8"    "SLC24A2"
[13] "UBE2NL"   "GAS8-AS1" "ZNF735"

[[20]]$size
[1] 15

[[20]]$algorithm
[1] "FASTGREEDY"

[[20]]$depth
[1] 6

[[20]]$target_proteins
[1] "ADARB2"


[[21]]
[[21]]$module_id
[1] "RC6_1"

[[21]]$genes
 [1] "EIF4A1"   "EIF4A2"   "EIF4B"    "EIF4E"    "EIF4E1B"  "EIF4E3"
 [7] "EIF4EBP3" "EIF4G1"   "EIF4G2"   "EIF4G3"   "EIF4H"    "PDCD4"
[13] "RAMAC"    "SLC45A3"

[[21]]$size
[1] 14

[[21]]$algorithm
[1] "FASTGREEDY"

[[21]]$depth
[1] 6

[[21]]$target_proteins
[1] "EIF4E"


[[22]]
[[22]]$module_id
[1] "RC5_6"

[[22]]$genes
 [1] "CCDC8"   "EEF1DP3" "EEF1G"   "MIAT"    "MTDH"    "NSUN2"   "PHACTR3"
 [8] "SMCO2"   "NXF4"    "OR8G5"   "TAFA4"

[[22]]$size
[1] 11

[[22]]$algorithm
[1] "FASTGREEDY"

[[22]]$depth
[1] 5

[[22]]$target_proteins
[1] "NSUN2"


[[23]]
[[23]]$module_id
[1] "RC3_16"

[[23]]$genes
 [1] "C18ORF63"  "C1ORF167"  "CBLL2"     "EEF1AKNMT" "IGKV1-5"   "METTL16"
 [7] "METTL3"    "METTL4"    "METTL5"    "VIRMA"     "ZCCHC4"

[[23]]$size
[1] 11

[[23]]$algorithm
[1] "FASTGREEDY"

[[23]]$depth
[1] 3

[[23]]$target_proteins
[1] "METTL3" "VIRMA"


[[24]]
[[24]]$module_id
[1] "RC5_1"

[[24]]$genes
 [1] "CZIB"    "DDX28"   "GTPBP6"  "GTPBP8"  "MALSU1"  "MIEF1-2" "MRM2"
 [8] "MRM3"    "MRPL10"  "MRPL11"  "MRPL14"  "MRPL18"  "MRPL23"  "MRPL24"
[15] "MRPL30"  "MRPL34"  "MRPL37"  "MRPL38"  "MRPL39"  "MRPL42"  "MRPL43"
[22] "MRPL46"  "MRPL47"  "MRPL48"  "MRPL50"  "MRPL51"  "MRPL52"  "MRPL53"
[29] "MRPL54"  "MRPL55"  "MRPL57"  "MRPL58"  "MRPS30"  "MTERF4"  "MTG1"
[36] "MTRES1"  "NSUN4"   "PUS7L"

[[24]]$size
[1] 38

[[24]]$algorithm
[1] "FASTGREEDY"

[[24]]$depth
[1] 5

[[24]]$target_proteins
[1] "NSUN4"


[[25]]
[[25]]$module_id
[1] "RC5_1"

[[25]]$genes
 [1] "AFG3L2"     "ANKRD20A8P" "BCS1L"      "C8ORF82"    "CCDC109B"
 [6] "DNAJC15"    "DNAJC28"    "ELAC2"      "EXD2"       "GFM2"
[11] "MRPS26"     "MRRF"       "MTFMT"      "MTRF1"      "NFS1"
[16] "OTC"        "PAM16"      "PPIF"       "PYCR1"      "PYCR2"
[21] "SLIRP"      "TACO1"      "TIMM44"     "TRMT10C"    "VWA8"
[26] "MRRFP1"     "TRNI"

[[25]]$size
[1] 27

[[25]]$algorithm
[1] "FASTGREEDY"

[[25]]$depth
[1] 5

[[25]]$target_proteins
[1] "TRMT10C"


[[26]]
[[26]]$module_id
[1] "RC5_2"

[[26]]$genes
 [1] "AK4"            "ALAS1"          "ATP5D"          "ATP5O"
 [5] "C10ORF2"        "C17ORF80"       "C1QBP"          "C7ORF55-LUC7L2"
 [9] "CCDC90B"        "CDK5RAP1"       "CLPX"           "COQ5"
[13] "COX8A"          "DNAJA3"         "DNAJC19"        "EEF1AKMT3"
[17] "FASTKD5"        "GFM1"           "GTPBP3"         "HINT2"
[21] "IMMP2L"         "LETM1"          "LONP1"          "MCUR1"
[25] "MMAB"           "MRM1"           "MTG2"           "MTIF2"
[29] "MTRF1L"         "NME4"           "NT5DC2"         "PDE12"
[33] "PDK3"           "PDPR"           "PMPCA"          "PMPCB"
[37] "PNPLA8"         "POLDIP2"        "POLG"           "RTN4IP1"
[41] "SSBP1"          "STOML2"         "TEFM"           "TFAM"
[45] "TRMT61B"        "TSFM"           "TWNK"           "TMSB4XP2"

[[26]]$size
[1] 48

[[26]]$algorithm
[1] "FASTGREEDY"

[[26]]$depth
[1] 5

[[26]]$target_proteins
[1] "TRMT61B"


[[27]]
[[27]]$module_id
[1] "RC5_3"

[[27]]$genes
 [1] "ACOT1"        "ACOT2"        "ANGEL2"       "ATP5J2-PTCD1" "ATPAF1"
 [6] "C12ORF65"     "C6ORF203"     "DHX30"        "DUSP1"        "ERAL1"
[11] "FASTKD2"      "FASTKD3"      "GRSF1"        "GTPBP10"      "GUF1"
[16] "HNRNPDL"      "ICT1"         "KIAA0391"     "LRPPRC"       "METTL15"
[21] "METTL17"      "MGME1"        "MRPS17"       "MRPS36"       "MTERF1"
[26] "MTERF3"       "MTIF3"        "MTPAP"        "NGRN"         "PNPT1"
[31] "POLRMT"       "PTCD1"        "RCC1L"        "RNMTL1"       "RNR2"
[36] "RPUSD3"       "RPUSD4"       "SUPV3L1"      "TBRG4"        "THEM4"
[41] "THEM5"        "TRUB2"        "WBSCR16"

[[27]]$size
[1] 43

[[27]]$algorithm
[1] "FASTGREEDY"

[[27]]$depth
[1] 5

[[27]]$target_proteins
[1] "RPUSD4" "TRUB2"


[[28]]
[[28]]$module_id
[1] "RC2_5"

[[28]]$genes
 [1] "FAAH2"    "METTL1"   "PUS1"     "PUS10"    "PUS3"     "PUS7"
 [7] "PUSL1"    "RPUSD1"   "RPUSD2"   "TRIT1"    "TRMT10A"  "TRMT5"
[13] "TRUB1"    "WDR4"     "USP2-AS1"

[[28]]$size
[1] 15

[[28]]$algorithm
[1] "FASTGREEDY"

[[28]]$depth
[1] 2

[[28]]$target_proteins
[1] "METTL1" "PUS1"   "PUS3"   "PUS7"   "TRUB1"  "WDR4"


[[29]]
[[29]]$module_id
[1] "RC1_28"

[[29]]$genes
[1] "ALKBH1"  "BCCIP"   "DUS1L"   "DUS2"    "FTO"     "THUMPD2" "TRMT61A"

[[29]]$size
[1] 7

[[29]]$algorithm
[1] "FASTGREEDY"

[[29]]$depth
[1] 1

[[29]]$target_proteins
[1] "ALKBH1"  "FTO"     "TRMT61A"


[[30]]
[[30]]$module_id
[1] "RC5_1"

[[30]]$genes
 [1] "CDC73"     "CHD1"      "CTR9"      "DNMT3A"    "DNMT3B"    "H2BC14"
 [7] "H2BC15"    "H2BC3"     "H2BC4"     "H2BC9"     "H4C6"      "LEO1"
[13] "PAF1"      "PCDHGA2"   "PLEKHM1P"  "RNF20"     "RNF40"     "RTF1"
[19] "RTF2"      "SKIC2"     "TRIM51"    "SKIC8"     "MIR124-3"  "LINC01270"

[[30]]$size
[1] 24

[[30]]$algorithm
[1] "FASTGREEDY"

[[30]]$depth
[1] 5

[[30]]$target_proteins
[1] "DNMT3A" "DNMT3B"


[[31]]
[[31]]$module_id
[1] "RC5_1"

[[31]]$genes
 [1] "BARHL1"         "BCL9"           "BCL9L"          "CCDC169-SOHLH2"
 [5] "DMRT1"          "FIGLA"          "FOXL2"          "ISL1"
 [9] "ISL2"           "LDB1"           "LHX6"           "LHX8"
[13] "LHX9"           "MNX1"           "NEUROG2"        "NOBOX"
[17] "NR0B1"          "NR5A1"          "OLIG2"          "OSR2"
[21] "PAX8"           "PYGO2"          "RPL29P11"       "SOHLH2"
[25] "SRY"            "SSBP3"          "SSBP4"          "T"
[29] "TBR1"           "TBX20"          "TCF7L1"         "TCF7L2"
[33] "TET2"           "TLE1"           "TLE3"           "TLE4"
[37] "WT1"            "ZFPM2"

[[31]]$size
[1] 38

[[31]]$algorithm
[1] "FASTGREEDY"

[[31]]$depth
[1] 5

[[31]]$target_proteins
[1] "TET2"


[[32]]
[[32]]$module_id
[1] "RC2_3"

[[32]]$genes
 [1] "FAM217A" "GRHL1"   "GRHL2"   "GRHL3"   "NFE4"    "PRMT5"   "PRMT6"
 [8] "SPIN4"   "TET3"    "ZNF557"

[[32]]$size
[1] 10

[[32]]$algorithm
[1] "FASTGREEDY"

[[32]]$depth
[1] 2

[[32]]$target_proteins
[1] "TET3"


[[33]]
[[33]]$module_id
[1] "RC4_1"

[[33]]$genes
 [1] "ARID4A"   "ARID4B"   "BRMS1"    "BRMS1L"   "BRPF3"    "EMSY"
 [7] "FAM60A"   "FLJ25613" "FOXK2"    "GATAD1"   "KDM5A"    "KLF10"
[13] "KLF9"     "MAX"      "MNT"      "MXD1"     "MXD3"     "MXD4"
[19] "PHF12"    "PHF13"    "PHF21B"   "PHF23"    "SAP130"   "SAP25"
[25] "SAP30"    "SAP30L"   "SIN3A"    "SIN3B"    "SINHCAF"  "SUDS3"
[31] "TET1"     "TGIF2"    "TGIF2LX"  "TNRC18"   "ZNF704"   "MGS"

[[33]]$size
[1] 36

[[33]]$algorithm
[1] "FASTGREEDY"

[[33]]$depth
[1] 4

[[33]]$target_proteins
[1] "TET1"


[[34]]
[[34]]$module_id
[1] "RC5_1"

[[34]]$genes
 [1] "CBX5"     "DNMT1"    "HIST2H3A" "KMT5B"    "KMT5C"    "MBD1"
 [7] "SENP7"    "SETDB1"   "SNHG6"    "SUV39H1"  "SUV39H2"  "ZFP64"
[13] "ZNF518A"  "ZNF649"   "RBBP4P1"  "RPL26P30" "ZNF678"   "TRBV2"

[[34]]$size
[1] 18

[[34]]$algorithm
[1] "FASTGREEDY"

[[34]]$depth
[1] 5

[[34]]$target_proteins
[1] "DNMT1"


[[35]]
[[35]]$module_id
[1] "RC5_1"

[[35]]$genes
[1] "AZGP1P2"  "DIDO1"    "EEF1B2P5" "PROM2"    "RBM15"    "USP48"

[[35]]$size
[1] 6

[[35]]$algorithm
[1] "FASTGREEDY"

[[35]]$depth
[1] 5

[[35]]$target_proteins
[1] "RBM15"


[[36]]
[[36]]$module_id
[1] "RC4_1"

[[36]]$genes
 [1] "CCNL1"    "EIF2AK1"  "FAM76A"   "FAM76B"   "FIZ1"     "LOC93432"
 [7] "MFAP1"    "NSRP1"    "PPP1R10"  "PSENEN"   "RBM15B"   "RSRP1"
[13] "TOX4"     "ZNF41"    "ZNF75D"

[[36]]$size
[1] 15

[[36]]$algorithm
[1] "FASTGREEDY"

[[36]]$depth
[1] 4

[[36]]$target_proteins
[1] "RBM15B"


[[37]]
[[37]]$module_id
[1] "RC4_2"

[[37]]$genes
 [1] "ANKRD50"   "C12ORF43"  "C20ORF197" "C2ORF73"   "CCDC159"   "CDK12"
 [7] "FAM178B"   "FDCSP"     "GAGE5"     "IFI27L1"   "LBH"       "MAP9"
[13] "PEA15"     "PRPF38B"   "REXO1"     "RP9"       "SDHAP2"    "SERF2"
[19] "SLTM"      "TCEAL7"    "TCEB3"     "ZC3H13"    "REXO5"

[[37]]$size
[1] 23

[[37]]$algorithm
[1] "FASTGREEDY"

[[37]]$depth
[1] 4

[[37]]$target_proteins
[1] "ZC3H13"


[[38]]
[[38]]$module_id
[1] "RC4_3"

[[38]]$genes
 [1] "ATHL1"        "C22ORF46"     "GLUD1P3"      "GUSBP1"       "GUSBP4"
 [6] "KLF7"         "LINC00339"    "LINC00847"    "LINC01268"    "LOC100129917"
[11] "LOC100287015" "LOC728743"    "MIR223"       "NNT-AS1"      "PSMA3-AS1"
[16] "RRP7B"        "SH3BP5-AS1"   "SNHG7"        "TBRG1"        "TTN-AS1"
[21] "YTHDC1"       "ZNF589"       "ZFP57"        "ZNF862"       "ZFP69"

[[38]]$size
[1] 25

[[38]]$algorithm
[1] "FASTGREEDY"

[[38]]$depth
[1] 4

[[38]]$target_proteins
[1] "YTHDC1"


[[39]]
[[39]]$module_id
[1] "RC4_1"

[[39]]$genes
 [1] "BOD1L1"       "CPSF6"        "CPSF7"        "FAM58A"       "LOC100506753"
 [6] "NCBP1"        "RAMACL"       "RNMT"         "SLC26A11"     "SLC35F4"
[11] "WDR82"        "STKLD1"

[[39]]$size
[1] 12

[[39]]$algorithm
[1] "FASTGREEDY"

[[39]]$depth
[1] 4

[[39]]$target_proteins
[1] "RNMT"


[[40]]
[[40]]$module_id
[1] "RC5_1"

[[40]]$genes
 [1] "ALKBH3"  "CAPS"    "CAPSL"   "EML1"    "EML2"    "FAM83F"  "SVBP"
 [8] "TPSB2"   "TTL"     "TUBA1A"  "TUBA1C"  "TUBB2A"  "TUBB2B"  "ZC2HC1B"
[15] "SNTN"

[[40]]$size
[1] 15

[[40]]$algorithm
[1] "FASTGREEDY"

[[40]]$depth
[1] 5

[[40]]$target_proteins
[1] "ALKBH3"

In [ ]:
library(progress)

In [ ]:
activity_methods <- paste0("method", 1:100)
pb_activity <- progress::progress_bar$new(
    format = "  [:bar] :percent (:current/:total) ETA: :eta",
    total = length(activity_methods), clear = FALSE, width = 60
)
processed_methods <- 0

for (method in activity_methods) {
    processed_methods <- processed_methods + 1
    if (length(activity_methods) > 0) pb_activity$tick()
}

ERROR: Error in pb_tick(self, private, len, tokens): !self$finished is not TRUE