In [1]:
# MPAGE Package Testing
# This notebook demonstrates basic functionality of the MPAGE package

# Load the package
devtools::load_all()

ℹ Loading MPAGE




Warning message:
“Objects listed as exports, but not present in namespace:
• add_custom_proteins
• filter_ppi_network
• load_ppi_network
• save_ppi_network
• save_rna_mod_proteins
• preprocess_intact_data
• load_intact_network
• download_intact_data”

In [2]:
networkds <- build_ppi_network()

Processing STRING database...

STRING Network Summary:

Processed 6857702 unique interactions

Unique proteins: 19622

Nodes: 16185
Edges: 236000
Average degree: 29.16281

Processing BIOGRID database...

BIOGRID Network Summary:

Processed 976169 unique interactions

Unique proteins: 20334

Nodes: 20169
Edges: 959426
Average degree: 95.13868

Processing INTACT database...

INTACT Network Summary:

Processed 606332 unique interactions

Unique proteins: 18416

Nodes: 5597
Edges: 20870
Average degree: 7.457567

In [3]:
# test <- preprocessing_string(
#     species_code = 9606,
#     score_threshold = 0,
#     output_file = "inst/extdata/stringdb_9606_v12.rds",
#     version = "12",
#     verbose = TRUE
# )

In [4]:
biogrid_file <- "data-raw/BIOGRID-ALL-4.4.248.tab3.txt"
biogrid_data <- data.table::fread(biogrid_file, sep = "\t", check.names = TRUE, quote = "")

In [5]:
verbose <- TRUE

In [6]:
if (verbose) {
  message(sprintf("Loaded %d interactions from BioGRID", nrow(biogrid_data)))
}

Loaded 2804534 interactions from BioGRID

In [7]:
biogrid_data %>% colnames()

 [1] "X.BioGRID.Interaction.ID"           "Entrez.Gene.Interactor.A"
 [3] "Entrez.Gene.Interactor.B"           "BioGRID.ID.Interactor.A"
 [5] "BioGRID.ID.Interactor.B"            "Systematic.Name.Interactor.A"
 [7] "Systematic.Name.Interactor.B"       "Official.Symbol.Interactor.A"
 [9] "Official.Symbol.Interactor.B"       "Synonyms.Interactor.A"
[11] "Synonyms.Interactor.B"              "Experimental.System"
[13] "Experimental.System.Type"           "Author"
[15] "Publication.Source"                 "Organism.ID.Interactor.A"
[17] "Organism.ID.Interactor.B"           "Throughput"
[19] "Score"                              "Modification"
[21] "Qualifications"                     "Tags"
[23] "Source.Database"                    "SWISS.PROT.Accessions.Interactor.A"
[25] "TREMBL.Accessions.Interactor.A"     "REFSEQ.Accessions.Interactor.A"
[27] "SWISS.PROT.Accessions.Interactor.B" "TREMBL.Accessions.Interactor.B"
[29] "REFSEQ.Accessions.Interactor.B"     "Ontology.Term.IDs"
[31] "Ontology.Term.Names"                "Ontology.Term.Categories"
[33] "Ontology.Term.Qualifier.IDs"        "Ontology.Term.Qualifier.Names"
[35] "Ontology.Term.Types"                "Organism.Name.Interactor.A"
[37] "Organism.Name.Interactor.B"

In [8]:
processed_data <- biogrid_data %>%
  dplyr::select(
    gene1 = Official.Symbol.Interactor.A,
    gene2 = Official.Symbol.Interactor.B,
    species_codeA = Organism.ID.Interactor.A,
    species_codeB = Organism.ID.Interactor.B,
    Experimental.System.Type
  ) %>%
  dplyr::filter(species_codeA == species_codeB, species_codeA == 9606)



if (verbose) {
  message(sprintf("Processed %d unique interactions", nrow(processed_data)))
  message(sprintf("Unique proteins: %d", length(unique(c(processed_data$gene1, processed_data$gene2)))))
}

Processed 1219381 unique interactions

Unique proteins: 20334

In [9]:
biogrid_data %>% colnames()

 [1] "X.BioGRID.Interaction.ID"           "Entrez.Gene.Interactor.A"
 [3] "Entrez.Gene.Interactor.B"           "BioGRID.ID.Interactor.A"
 [5] "BioGRID.ID.Interactor.B"            "Systematic.Name.Interactor.A"
 [7] "Systematic.Name.Interactor.B"       "Official.Symbol.Interactor.A"
 [9] "Official.Symbol.Interactor.B"       "Synonyms.Interactor.A"
[11] "Synonyms.Interactor.B"              "Experimental.System"
[13] "Experimental.System.Type"           "Author"
[15] "Publication.Source"                 "Organism.ID.Interactor.A"
[17] "Organism.ID.Interactor.B"           "Throughput"
[19] "Score"                              "Modification"
[21] "Qualifications"                     "Tags"
[23] "Source.Database"                    "SWISS.PROT.Accessions.Interactor.A"
[25] "TREMBL.Accessions.Interactor.A"     "REFSEQ.Accessions.Interactor.A"
[27] "SWISS.PROT.Accessions.Interactor.B" "TREMBL.Accessions.Interactor.B"
[29] "REFSEQ.Accessions.Interactor.B"     "Ontology.Term.IDs"
[31] "Ontology.Term.Names"                "Ontology.Term.Categories"
[33] "Ontology.Term.Qualifier.IDs"        "Ontology.Term.Qualifier.Names"
[35] "Ontology.Term.Types"                "Organism.Name.Interactor.A"
[37] "Organism.Name.Interactor.B"

In [10]:
species_code <- 9606
processed_data <- biogrid_data %>%
  dplyr::select(
    gene1 = Official.Symbol.Interactor.A,
    gene2 = Official.Symbol.Interactor.B,
    species_codeA = Organism.ID.Interactor.A,
    species_codeB = Organism.ID.Interactor.B,
    Experimental.System.Type
  ) %>%
  dplyr::mutate(species_code = species_code, est = factor(Experimental.System.Type, levels = c("physical", "genetic"))) %>%
  dplyr::filter(species_codeA == species_codeB, species_codeA == species_code) %>%
  arrange(est) %>%
  distinct(gene1, gene2, .keep_all = TRUE) %>%
  dplyr::select(gene1, gene2, species_code, est)

In [11]:
saveRDS(processed_data, "inst/extdata/biogrid_9606_v4.4.248.rds")

In [12]:
readRDS("inst/extdata/intact_9606_v20250328.rds")

       gene1    gene2     species_code score
1      MDM2     TP53      9606         1.00
2      TP53     MDM2      9606         1.00
3      CDK4     CCND1     9606         0.99
4      CCND1    CDK4      9606         0.99
5      CCNT1    CDK9      9606         0.98
6      EIF4EBP1 EIF4E     9606         0.98
7      BCL2L1   BAD       9606         0.98
8      CASP8    FADD      9606         0.98
9      HRAS     RAF1      9606         0.98
10     RAF1     HRAS      9606         0.98
11     EGFR     SHC1      9606         0.98
12     CBL      SH3KBP1   9606         0.98
13     SH3KBP1  CBL       9606         0.98
14     PEX3     PEX19     9606         0.98
15     RAD51D   XRCC2     9606         0.98
16     EIF4E    EIF4EBP1  9606         0.98
17     BRCA1    BRIP1     9606         0.98
18     BRIP1    BRCA1     9606         0.98
19     MYC      MAX       9606         0.98
20     BRCA2    RAD51     9606         0.98
21     GRB2     EGFR      9606         0.98
22     GRB2     SHC1      9606         0.98
23     RAD51    BRCA2     9606         0.98
24     EIF4A3   CASC3     9606         0.98
25     RAC1     PAK1      9606         0.98
26     LSM2     LSM3      9606         0.98
27     CSNK2B   CSNK2A1   9606         0.98
28     CHUK     IKBKG     9606         0.98
29     IKBKB    IKBKG     9606         0.98
30     IKBKG    CHUK      9606         0.98
⋮      ⋮        ⋮         ⋮            ⋮
606303 CDH5     CD99      9606         0.27
606304 CDH5     TPM1      9606         0.27
606305 CDH5     TUBB      9606         0.27
606306 CDH5     ARF6      9606         0.27
606307 CDH5     TUBA1C    9606         0.27
606308 CDH5     HSPH1     9606         0.27
606309 CDH5     MMTAG2    9606         0.27
606310 CDH5     CAND1     9606         0.27
606311 CDH5     CCT2      9606         0.27
606312 CDH5     HSP90AA1  9606         0.27
606313 CDH5     HNRNPM    9606         0.27
606314 CDH5     CCT7      9606         0.27
606315 CDH5     XRCC5     9606         0.27
606316 CDH5     RAN       9606         0.27
606317 CDH5     HNRNPK    9606         0.27
606318 CDH5     HNRNPA2B1 9606         0.27
606319 CDH5     VAT1      9606         0.27
606320 CDH5     SND1      9606         0.27
606321 CDH5     CCN2      9606         0.27
606322 CDH5     LMNA      9606         0.27
606323 CDH5     PPP2R1A   9606         0.27
606324 CDH5     MEGF6     9606         0.27
606325 CDH5     ADRM1     9606         0.27
606326 CDH5     PPIA      9606         0.27
606327 CDH5     SEMG1     9606         0.27
606328 HSP90B1  CSNK2A1   9606         0.22
606329 EPS8     USP6NL    9606         0.22
606330 EMILIN1  ITGB1     9606         0.22
606331 KRT8     RAF1      9606         0.22
606332 F11R     CASK      9606         0.22

In [13]:
processed_data <- biogrid_data %>%
  dplyr::select(
    gene1 = Official.Symbol.Interactor.A,
    gene2 = Official.Symbol.Interactor.B,
    species_codeA = Organism.ID.Interactor.A,
    species_codeB = Organism.ID.Interactor.B,
    Experimental.System.Type
  ) %>%
  dplyr::filter(species_codeA == species_codeB, species_codeA == 9606)



if (verbose) {
  message(sprintf("Processed %d unique interactions", nrow(processed_data)))
  message(sprintf("Unique proteins: %d", length(unique(c(processed_data$gene1, processed_data$gene2)))))
}

Processed 1219381 unique interactions

Unique proteins: 20334

In [14]:
biogrid_data %>% colnames()

 [1] "X.BioGRID.Interaction.ID"           "Entrez.Gene.Interactor.A"
 [3] "Entrez.Gene.Interactor.B"           "BioGRID.ID.Interactor.A"
 [5] "BioGRID.ID.Interactor.B"            "Systematic.Name.Interactor.A"
 [7] "Systematic.Name.Interactor.B"       "Official.Symbol.Interactor.A"
 [9] "Official.Symbol.Interactor.B"       "Synonyms.Interactor.A"
[11] "Synonyms.Interactor.B"              "Experimental.System"
[13] "Experimental.System.Type"           "Author"
[15] "Publication.Source"                 "Organism.ID.Interactor.A"
[17] "Organism.ID.Interactor.B"           "Throughput"
[19] "Score"                              "Modification"
[21] "Qualifications"                     "Tags"
[23] "Source.Database"                    "SWISS.PROT.Accessions.Interactor.A"
[25] "TREMBL.Accessions.Interactor.A"     "REFSEQ.Accessions.Interactor.A"
[27] "SWISS.PROT.Accessions.Interactor.B" "TREMBL.Accessions.Interactor.B"
[29] "REFSEQ.Accessions.Interactor.B"     "Ontology.Term.IDs"
[31] "Ontology.Term.Names"                "Ontology.Term.Categories"
[33] "Ontology.Term.Qualifier.IDs"        "Ontology.Term.Qualifier.Names"
[35] "Ontology.Term.Types"                "Organism.Name.Interactor.A"
[37] "Organism.Name.Interactor.B"

In [15]:
# Process the data to required format
# BioGRID format processing
processed_data <- biogrid_data %>%
  dplyr::select(
    gene1 = Official.Symbol.Interactor.A,
    gene2 = Official.Symbol.Interactor.B,
    species_codeA = Organism.ID.Interactor.A,
    species_codeB = Organism.ID.Interactor.B,
    Score = Score
  ) %>%
  dplyr::mutate(
    # Convert gene IDs to character and clean
    geneA = as.character(.data$geneA),
    geneB = as.character(.data$geneB),

    # Ensure species codes are character
    species_codeA = as.character(.data$species_codeA),
    species_codeB = as.character(.data$species_codeB),

    # BioGRID doesn't have confidence scores, use 1.0 as default
    score = 1.0,

    # Filter for specified species
    species_code = .data$species_codeA
  ) %>%
  # Filter for specified species
  dplyr::filter(
    .data$species_codeA == species_code,
    .data$species_codeB == species_code,
    .data$species_codeA == .data$species_codeB
  ) %>%
  # Clean and finalize
  dplyr::mutate(
    geneA = toupper(.data$geneA),
    geneB = toupper(.data$geneB)
  ) %>%
  dplyr::select(geneA, geneB, score, species_code) %>%
  dplyr::distinct() %>%
  dplyr::filter(
    !is.na(.data$geneA),
    !is.na(.data$geneB),
    .data$geneA != .data$geneB,
    .data$geneA != "",
    .data$geneB != "",
    .data$geneA != "-",
    .data$geneB != "-"
  )

# Clean up temporary files
unlink(temp_zip)
unlink(extract_dir, recursive = TRUE)

if (verbose) {
  message(sprintf("Processed %d unique interactions", nrow(processed_data)))
  message(sprintf("Unique proteins: %d", length(unique(c(processed_data$geneA, processed_data$geneB)))))
}

# Save if output file specified
if (!is.null(output_file)) {
  saveRDS(processed_data, file = output_file)
  if (verbose) {
    message(sprintf("Data saved to: %s", output_file))
  }
}

return(processed_data)

ERROR: Error in `dplyr::mutate()`:
ℹ In argument: `geneA = as.character(.data$geneA)`.
Caused by error in `.data$geneA`:
! Column `geneA` not found in `.data`.

In [ ]:
a <- list(
  string_version = "12"
)

In [ ]:
a[["string_version"]]

[1] "12"

In [ ]:

    
    if (verbose) {
      message(sprintf("Loaded %d interactions from BioGRID", nrow(biogrid_data)))
    }
    
    # Process the data to required format
    # BioGRID format processing
    processed_data <- biogrid_data %>%
      dplyr::select(
        # BioGRID column names
        geneA = .data$`Entrez Gene Interactor A`,
        geneB = .data$`Entrez Gene Interactor B`,
        species_codeA = .data$`Organism ID Interactor A`,
        species_codeB = .data$`Organism ID Interactor B`,
        experimental_system = .data$`Experimental System`,
        pubmed_id = .data$`Pubmed ID`
      ) %>%
      dplyr::mutate(
        # Convert gene IDs to character and clean
        geneA = as.character(.data$geneA),
        geneB = as.character(.data$geneB),
        
        # Ensure species codes are character
        species_codeA = as.character(.data$species_codeA),
        species_codeB = as.character(.data$species_codeB),
        
        # BioGRID doesn't have confidence scores, use 1.0 as default
        score = 1.0,
        
        # Filter for specified species
        species_code = .data$species_codeA
      ) %>%
      # Filter for specified species
      dplyr::filter(
        .data$species_codeA == species_code,
        .data$species_codeB == species_code,
        .data$species_codeA == .data$species_codeB
      ) %>%
      # Clean and finalize
      dplyr::mutate(
        geneA = toupper(.data$geneA),
        geneB = toupper(.data$geneB)
      ) %>%
      dplyr::select(geneA, geneB, score, species_code) %>%
      dplyr::distinct() %>%
      dplyr::filter(
        !is.na(.data$geneA),
        !is.na(.data$geneB),
        .data$geneA != .data$geneB,
        .data$geneA != "",
        .data$geneB != "",
        .data$geneA != "-",
        .data$geneB != "-"
      )
    
    # Clean up temporary files
    unlink(temp_zip)
    unlink(extract_dir, recursive = TRUE)
    
    if (verbose) {
      message(sprintf("Processed %d unique interactions", nrow(processed_data)))
      message(sprintf("Unique proteins: %d", length(unique(c(processed_data$geneA, processed_data$geneB)))))
    }
    
    # Save if output file specified
    if (!is.null(output_file)) {
      saveRDS(processed_data, file = output_file)
      if (verbose) {
        message(sprintf("Data saved to: %s", output_file))
      }
    }
    
    return(processed_data)
    
  }, error = function(e) {
    stop("Error processing BioGRID data: ", e$message)
  })
}

In [ ]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
species_code <- 9606

In [ ]:
# Process the data to required format
# IntAct PSI-MITAB format processing
processed_data <- intact_data %>%
    dplyr::select(
        Alt..ID.s..interactor.A,
        Alt..ID.s..interactor.B,
        Alias.es..interactor.A,
        Alias.es..interactor.B,
        Taxid.interactor.A,
        Taxid.interactor.B,
        Confidence.value.s.
    ) %>%
    # Extract species information
    dplyr::mutate(
        taxidA = stringr::str_extract(Taxid.interactor.A, "taxid:([0-9]+)") %>%
            stringr::str_remove("taxid:"),
        taxidB = stringr::str_extract(Taxid.interactor.B, "taxid:([0-9]+)") %>%
            stringr::str_remove("taxid:")
    ) %>%
    # Filter by species
    dplyr::filter(
        !is.na(taxidA), !is.na(taxidB),
        taxidA == species_code,
        taxidB == species_code,
        taxidA == taxidB
    ) %>%
    # Extract gene names using multiple patterns
    dplyr::mutate(
        # Extract from gene name annotations
        geneA_name = stringr::str_extract(
            Alias.es..interactor.A,
            "uniprotkb:[A-Za-z0-9-]+\\(gene name\\)"
        ) %>%
            stringr::str_remove("uniprotkb:") %>%
            stringr::str_remove("\\(gene name\\)") %>%
            toupper(),
        geneB_name = stringr::str_extract(
            Alias.es..interactor.B,
            "uniprotkb:[A-Za-z0-9-]+\\(gene name\\)"
        ) %>%
            stringr::str_remove("uniprotkb:") %>%
            stringr::str_remove("\\(gene name\\)") %>%
            toupper(),

        # Extract from display names as fallback
        geneA_display = stringr::str_extract(
            Alias.es..interactor.A,
            "display_short\\):([^|]+)"
        ) %>%
            stringr::str_remove("display_short\\):"),
        geneB_display = stringr::str_extract(
            Alias.es..interactor.B,
            "display_short\\):([^|]+)"
        ) %>%
            stringr::str_remove("display_short\\):"),

        # Use gene name if available, otherwise display name
        gene1 = dplyr::coalesce(geneA_name, geneA_display),
        gene2 = dplyr::coalesce(geneB_name, geneB_display),

        # Extract interaction score
        score = stringr::str_extract(Confidence.value.s., "intact-miscore:([0-9\\.]+)") %>%
            stringr::str_remove("intact-miscore:") %>%
            as.numeric(),
        species_code = taxidA
    ) %>%
    # Clean and filter
    dplyr::select(gene1, gene2, score, species_code) %>%
    dplyr::filter(
        !is.na(gene1), !is.na(gene2), gene1 != "", gene2 != "", gene1 != gene2,
        !is.na(score),
    ) %>%
    dplyr::distinct() %>%
    dplyr::arrange(dplyr::desc(score)) %>%
    dplyr::select(gene1, gene2, species_code, score)

In [ ]:
saveRDS(processed_data, "inst/extdata/intact_9606_v20250328.rds")

In [ ]:
if (verbose) {
    message(sprintf("Loaded %d interactions from IntAct", nrow(intact_data)))
}

# Process the data to required format
# IntAct PSI-MITAB format processing
processed_data <- intact_data %>%
    dplyr::select(
        Alt..ID.s..interactor.A,
        Alt..ID.s..interactor.B,
        Alias.es..interactor.A,
        Alias.es..interactor.B,
        Taxid.interactor.A,
        Taxid.interactor.B,
        Confidence.value.s.
    ) %>%
    # Extract species information
    dplyr::mutate(
        taxidA = stringr::str_extract(Taxid.interactor.A, "taxid:([0-9]+)") %>%
            stringr::str_remove("taxid:"),
        taxidB = stringr::str_extract(Taxid.interactor.B, "taxid:([0-9]+)") %>%
            stringr::str_remove("taxid:")
    ) %>%
    # Filter by species
    dplyr::filter(
        !is.na(taxidA), !is.na(taxidB),
        taxidA %in% species_filter,
        taxidB %in% species_filter,
        taxidA == taxidB
    ) %>%
    # Extract gene names using multiple patterns
    dplyr::mutate(
        # Extract from gene name annotations
        geneA_name = stringr::str_extract(
            Alias.es..interactor.A,
            "uniprotkb:[A-Za-z0-9-]+\\(gene name\\)"
        ) %>%
            stringr::str_remove("uniprotkb:") %>%
            stringr::str_remove("\\(gene name\\)") %>%
            toupper(),
        geneB_name = stringr::str_extract(
            Alias.es..interactor.B,
            "uniprotkb:[A-Za-z0-9-]+\\(gene name\\)"
        ) %>%
            stringr::str_remove("uniprotkb:") %>%
            stringr::str_remove("\\(gene name\\)") %>%
            toupper(),

        # Extract from display names as fallback
        geneA_display = stringr::str_extract(
            Alias.es..interactor.A,
            "display_short\\):([^|]+)"
        ) %>%
            stringr::str_remove("display_short\\):"),
        geneB_display = stringr::str_extract(
            Alias.es..interactor.B,
            "display_short\\):([^|]+)"
        ) %>%
            stringr::str_remove("display_short\\):"),

        # Use gene name if available, otherwise display name
        geneA = dplyr::coalesce(geneA_name, geneA_display),
        geneB = dplyr::coalesce(geneB_name, geneB_display),

        # Extract interaction score
        score = stringr::str_extract(Confidence.value.s., "intact-miscore:([0-9\\.]+)") %>%
            stringr::str_remove("intact-miscore:") %>%
            as.numeric(),
        taxid = taxidA
    ) %>%
    # Clean and filter
    dplyr::select(geneA, geneB, score, taxid) %>%
    dplyr::filter(
        !is.na(geneA), !is.na(geneB), geneA != "", geneB != "",
        !is.na(score), score >= min_score
    ) %>%
    dplyr::distinct() %>%
    dplyr::arrange(dplyr::desc(score))
dplyr::mutate(
    # Extract UniProt IDs from complex identifiers
    geneA = stringr::str_extract(.data$geneA, "uniprotkb:([A-Za-z0-9-]+)") %>%
        stringr::str_remove("uniprotkb:"),
    geneB = stringr::str_extract(.data$geneB, "uniprotkb:([A-Za-z0-9-]+)") %>%
        stringr::str_remove("uniprotkb:"),

    # Extract species codes
    species_codeA = stringr::str_extract(.data$taxidA, "taxid:([0-9]+)") %>%
        stringr::str_remove("taxid:"),
    species_codeB = stringr::str_extract(.data$taxidB, "taxid:([0-9]+)") %>%
        stringr::str_remove("taxid:"),

    # Extract IntAct confidence score
    score = stringr::str_extract(.data$score_raw, "intact-miscore:([0-9\\.]+)") %>%
        stringr::str_remove("intact-miscore:") %>%
        as.numeric()
) %>%
    # Filter for specified species
    dplyr::filter(
        .data$species_codeA == species_code,
        .data$species_codeB == species_code,
        .data$species_codeA == .data$species_codeB
    ) %>%
    # Filter by score threshold
    dplyr::filter(
        !is.na(.data$score),
        .data$score >= score_threshold
    ) %>%
    # Clean and finalize
    dplyr::mutate(
        species_code = .data$species_codeA,
        geneA = toupper(.data$geneA),
        geneB = toupper(.data$geneB)
    ) %>%
    dplyr::select(geneA, geneB, score, species_code) %>%
    dplyr::distinct() %>%
    dplyr::filter(
        !is.na(.data$geneA),
        !is.na(.data$geneB),
        .data$geneA != .data$geneB,
        .data$geneA != "",
        .data$geneB != ""
    )

In [ ]:
test <- preprocessing_intact(
    species_code = "9606",
    score_threshold = 0.4,
    output_file = NULL,
    version = "2025-03-28",
    verbose = TRUE
)

Downloading IntAct data (Version: 2025-03-28)for species 9606

Downloading from: https://ftp.ebi.ac.uk/pub/databases/intact/2025-03-28/psimitab/intact.txt

To the file: /tmp/RtmpPOUGqD/file6fc22d54fd70.txt

Warning message in utils::download.file(intact_url, temp_file, quiet = !verbose, :
“downloaded length 21767737 != reported length 7890868954”
Warning message in utils::download.file(intact_url, temp_file, quiet = !verbose, :
“URL 'https://ftp.ebi.ac.uk/pub/databases/intact/2025-03-28/psimitab/intact.txt': Timeout of 60 seconds was reached”

ERROR: Error in utils::download.file(intact_url, temp_file, quiet = !verbose, : download from 'https://ftp.ebi.ac.uk/pub/databases/intact/2025-03-28/psimitab/intact.txt' failed

In [ ]:
download_ppi_data("STRING",
    output_dir = "data-raw/",
    processing_params = list(
        species_filter = c("9606"),
        min_score = 0.0
    ),
    overwrite = FALSE,
    verbose = TRUE
)

Downloading STRING data...

Downloading from: https://stringdb-static.org/download/protein.links.v12/9606.protein.links.v12.txt.gz

Warning message in download.file(config$url, paste0(temp_file, ".gz"), quiet = !verbose):
“downloaded length 0 != reported length 153”
Warning message in download.file(config$url, paste0(temp_file, ".gz"), quiet = !verbose):
“cannot open URL 'https://stringdb-static.org/download/protein.links.v12/9606.protein.links.v12.txt.gz': HTTP status was '404 Not Found'”
Warning message in value[[3L]](cond):
“Download failed for STRING: cannot open URL 'https://stringdb-static.org/download/protein.links.v12/9606.protein.links.v12.txt.gz'”
Warning message in value[[3L]](cond):
“Falling back to local file processing”

ERROR: Error in process_local_ppi_data(database_type, output_dir, processing_params, : Local STRING data file not found at: data-raw/string_interactions.txt

In [ ]:
df <- data.table::fread("data-raw/core.psimitab", sep = "\t", check.names = TRUE, quote = "", header = FALSE)

In [ ]:
df <- data.table::fread("data-raw/BIOGRID-ALL-4.4.248.tab3.txt", sep = "\t", check.names = TRUE, quote = "", header = TRUE)
df %>%
    dplyr::select(
        Official.Symbol.Interactor.A, Official.Symbol.Interactor.B,
        Organism.ID.Interactor.A,
        Organism.ID.Interactor.B, Organism.Name.Interactor.A, Organism.Name.Interactor.B, Throughput, Score, Modification,
        Experimental.System,
        Experimental.System.Type,
        Author,
        Publication.Source,
        Organism.ID.Interactor.A,
        Organism.ID.Interactor.B,
        Throughput,
        Score, Qualifications, Tags
    ) %>%
    dplyr::filter(Organism.ID.Interactor.A == Organism.ID.Interactor.B, Organism.ID.Interactor.A %in% c(9606, 10090), Organism.ID.Interactor.B %in% c(9606, 10090)) %>%
    arrange(Score) -> sadf
saveRDS(sadf, "inst/extdata/biogrid_processed.rds")

In [ ]:
df %>%
    pull(Experimental.System) %>%
    unique()

 [1] "Two-hybrid"                    "Affinity Capture-MS"
 [3] "Affinity Capture-Western"      "Dosage Rescue"
 [5] "Reconstituted Complex"         "Synthetic Growth Defect"
 [7] "Synthetic Lethality"           "Synthetic Rescue"
 [9] "Affinity Capture-Luminescence" "Biochemical Activity"
[11] "Co-crystal Structure"          "Far Western"
[13] "FRET"                          "Protein-peptide"
[15] "Co-localization"               "Affinity Capture-RNA"
[17] "Protein-RNA"                   "PCA"
[19] "Co-purification"               "Co-fractionation"
[21] "Dosage Lethality"              "Phenotypic Enhancement"
[23] "Phenotypic Suppression"        "Dosage Growth Defect"
[25] "Negative Genetic"              "Positive Genetic"
[27] "Synthetic Haploinsufficiency"  "Proximity Label-MS"
[29] "Cross-Linking-MS (XL-MS)"      "Surface Display"

In [ ]:
df %>%
    dplyr::select(Throughput, Experimental.System, Experimental.System.Type, Score, Source.Database) %>%
    distinct()

       Throughput                     Experimental.System
1      Low Throughput                 Two-hybrid
2      High Throughput                Two-hybrid
3      High Throughput                Affinity Capture-MS
4      Low Throughput                 Affinity Capture-MS
5      Low Throughput                 Affinity Capture-Western
6      Low Throughput                 Dosage Rescue
7      Low Throughput                 Reconstituted Complex
8      High Throughput|Low Throughput Synthetic Growth Defect
9      Low Throughput                 Synthetic Lethality
10     High Throughput                Synthetic Lethality
11     High Throughput|Low Throughput Synthetic Lethality
12     Low Throughput                 Synthetic Rescue
13     High Throughput                Affinity Capture-Luminescence
14     High Throughput                Affinity Capture-Western
15     Low Throughput                 Biochemical Activity
16     Low Throughput                 Co-crystal Structure
17     Low Throughput                 Far Western
18     Low Throughput                 FRET
19     Low Throughput                 Protein-peptide
20     Low Throughput                 Co-localization
21     High Throughput                Protein-peptide
22     Low Throughput                 Affinity Capture-RNA
23     Low Throughput                 Protein-RNA
24     Low Throughput                 PCA
25     High Throughput|Low Throughput Affinity Capture-Western
26     High Throughput                Reconstituted Complex
27     High Throughput                Biochemical Activity
28     Low Throughput                 Co-purification
29     Low Throughput                 Co-fractionation
30     Low Throughput                 Dosage Lethality
⋮      ⋮                              ⋮
581904 High Throughput                Affinity Capture-MS
581905 High Throughput                Affinity Capture-MS
581906 High Throughput                Affinity Capture-MS
581907 High Throughput                Affinity Capture-MS
581908 High Throughput                Affinity Capture-MS
581909 High Throughput                Affinity Capture-MS
581910 High Throughput                Affinity Capture-MS
581911 High Throughput                Affinity Capture-MS
581912 High Throughput                Affinity Capture-MS
581913 High Throughput                Affinity Capture-MS
581914 High Throughput                Affinity Capture-MS
581915 High Throughput                Affinity Capture-MS
581916 High Throughput                Affinity Capture-MS
581917 High Throughput                Affinity Capture-MS
581918 High Throughput                Affinity Capture-MS
581919 High Throughput                Affinity Capture-MS
581920 High Throughput                Affinity Capture-MS
581921 High Throughput                Affinity Capture-MS
581922 High Throughput                Affinity Capture-MS
581923 High Throughput                Affinity Capture-MS
581924 High Throughput                Affinity Capture-MS
581925 High Throughput                Affinity Capture-MS
581926 High Throughput                Affinity Capture-MS
581927 High Throughput                Affinity Capture-MS
581928 High Throughput                Affinity Capture-MS
581929 High Throughput                Affinity Capture-MS
581930 High Throughput                Affinity Capture-MS
581931 High Throughput                Affinity Capture-MS
581932 High Throughput                Affinity Capture-MS
581933 High Throughput                Affinity Capture-MS
       Experimental.System.Type Score       Source.Database
1      physical                 -           BIOGRID
2      physical                 -           BIOGRID
3      physical                 -           BIOGRID
4      physical                 -           BIOGRID
5      physical                 -           BIOGRID
6      genetic                  -           BIOGRID
7      physical                 -           BIOGRID
8      genetic                  -           BIOGRID
9      genetic                  -           BIOGRID
10     genetic                  -           BIOGRID
11     genetic                  -           BIOGRID
12     genetic                  -           BIOGRID
13     physical                 -           BIOGRID
14     physical                 -           BIOGRID
15     physical                 -           BIOGRID
16     physical                 -           BIOGRID
17     physical                 -           BIOGRID
18     physical                 -           BIOGRID
19     physical                 -           BIOGRID
20     physical                 -           BIOGRID
21     physical                 -           BIOGRID
22     physical                 -           BIOGRID
23     physical                 -           BIOGRID
24     physical                 -           BIOGRID
25     physical                 -           BIOGRID
26     physical                 -           BIOGRID
27     physical                 -           BIOGRID
28     physical                 -           BIOGRID
29     physical                 -           BIOGRID
30     genetic                  -           BIOGRID
⋮      ⋮                        ⋮           ⋮
581904 physical                 0.69246895  BIOGRID
581905 physical                 0.47075113  BIOGRID
581906 physical                 0.675400034 BIOGRID
581907 physical                 0.828867322 BIOGRID
581908 physical                 0.671463115 BIOGRID
581909 physical                 0.916801361 BIOGRID
581910 physical                 0.819922014 BIOGRID
581911 physical                 0.999938908 BIOGRID
581912 physical                 0.988688441 BIOGRID
581913 physical                 0.999804616 BIOGRID
581914 physical                 0.540252207 BIOGRID
581915 physical                 0.999558446 BIOGRID
581916 physical                 0.728532557 BIOGRID
581917 physical                 0.963636067 BIOGRID
581918 physical                 0.999602175 BIOGRID
581919 physical                 0.461471969 BIOGRID
581920 physical                 0.754178859 BIOGRID
581921 physical                 0.42720146  BIOGRID
581922 physical                 0.479166533 BIOGRID
581923 physical                 0.52435671  BIOGRID
581924 physical                 0.767676812 BIOGRID
581925 physical                 0.930654699 BIOGRID
581926 physical                 0.468637644 BIOGRID
581927 physical                 0.674042662 BIOGRID
581928 physical                 0.981457779 BIOGRID
581929 physical                 0.99657636  BIOGRID
581930 physical                 0.603422654 BIOGRID
581931 physical                 0.978979332 BIOGRID
581932 physical                 0.960508254 BIOGRID
581933 physical                 0.685431914 BIOGRID

In [ ]:
df %>% dplyr::select(
    Official.Symbol.Interactor.A, Official.Symbol.Interactor.B,
    Organism.ID.Interactor.A,
    Organism.ID.Interactor.B, Organism.Name.Interactor.A, Organism.Name.Interactor.B, Throughput, Score, Modification,
    Experimental.System,
    Experimental.System.Type,
    Author,
    Publication.Source,
    Organism.ID.Interactor.A,
    Organism.ID.Interactor.B,
    Throughput,
    Score, Qualifications, Tags
)

        Official.Symbol.Interactor.A Official.Symbol.Interactor.B
1       MAP2K4                       FLNC
2       MYPN                         ACTN2
3       ACVR1                        FNTA
4       GATA2                        PML
5       RPA2                         STAT3
6       ARF1                         GGA3
7       ARF3                         ARFIP2
8       ARF3                         ARFIP1
9       XRN1                         ALDOA
10      APP                          APPBP2
11      APLP1                        DAB1
12      CITED2                       TFAP2A
13      EP300                        TFAP2A
14      APOB                         MTTP
15      ARRB2                        RALGDS
16      CSF1R                        GRB2
17      PRRC2A                       GRB2
18      LSM1                         NARS
19      SLC4A1                       SLC4A1AP
20      BCL3                         BARD1
21      ADRB1                        GIPC1
22      BRCA1                        ATF1
23      BRCA1                        MSH2
24      BRCA1                        BARD1
25      BRCA1                        MSH6
26      ARVCF                        CDH15
27      PCBD1                        CACNA1C
28      PSEN2                        CAPN1
29      CAPN3                        TTN
30      ITPR1                        CA8
⋮       ⋮                            ⋮
2804505 piwi                         RpL28
2804506 piwi                         RpS29
2804507 piwi                         Hsp26
2804508 piwi                         RpL4
2804509 piwi                         betaTub56D
2804510 piwi                         RpS18
2804511 piwi                         Fib
2804512 piwi                         RpL15
2804513 piwi                         apt
2804514 piwi                         RpS6
2804515 piwi                         Spindly
2804516 piwi                         alphaTub84B
2804517 piwi                         RpL13A
2804518 piwi                         NHP2
2804519 piwi                         RpL6
2804520 piwi                         RpL7A
2804521 piwi                         lost
2804522 piwi                         His1:CG33825
2804523 piwi                         CG4038
2804524 piwi                         sesB
2804525 piwi                         RpS9
2804526 piwi                         RpL37A
2804527 piwi                         RpL27
2804528 piwi                         Fmr1
2804529 piwi                         gammaCOP
2804530 piwi                         Imp
2804531 piwi                         RpL17
2804532 Ssrp                         piwi
2804533 piwi                         Ssrp
2804534 dsk1                         pabp
        Organism.ID.Interactor.A Organism.ID.Interactor.B
1       9606                     9606
2       9606                     9606
3       9606                     9606
4       9606                     9606
5       9606                     9606
6       9606                     9606
7       9606                     9606
8       9606                     9606
9       9606                     9606
10      9606                     9606
11      9606                     9606
12      9606                     9606
13      9606                     9606
14      9606                     9606
15      9606                     9606
16      9606                     9606
17      9606                     9606
18      9606                     9606
19      9606                     9606
20      9606                     9606
21      9606                     9606
22      9606                     9606
23      9606                     9606
24      9606                     9606
25      9606                     9606
26      9606                     9606
27      9606                     9606
28      9606                     9606
29      9606                     9606
30      9606                     9606
⋮       ⋮                        ⋮
2804505   7227                     7227
2804506   7227                     7227
2804507   7227                     7227
2804508   7227                     7227
2804509   7227                     7227
2804510   7227                     7227
2804511   7227                     7227
2804512   7227                     7227
2804513   7227                     7227
2804514   7227                     7227
2804515   7227                     7227
2804516   7227                     7227
2804517   7227                     7227
2804518   7227                     7227
2804519   7227                     7227
2804520   7227                     7227
2804521   7227                     7227
2804522   7227                     7227
2804523   7227                     7227
2804524   7227                     7227
2804525   7227                     7227
2804526   7227                     7227
2804527   7227                     7227
2804528   7227                     7227
2804529   7227                     7227
2804530   7227                     7227
2804531   7227                     7227
2804532   7227                     7227
2804533   7227                     7227
2804534 284812                   284812
        Organism.Name.Interactor.A       Organism.Name.Interactor.B
1       Homo sapiens                     Homo sapiens
2       Homo sapiens                     Homo sapiens
3       Homo sapiens                     Homo sapiens
4       Homo sapiens                     Homo sapiens
5       Homo sapiens                     Homo sapiens
6       Homo sapiens                     Homo sapiens
7       Homo sapiens                     Homo sapiens
8       Homo sapiens                     Homo sapiens
9       Homo sapiens                     Homo sapiens
10      Homo sapiens                     Homo sapiens
11      Homo sapiens                     Homo sapiens
12      Homo sapiens                     Homo sapiens
13      Homo sapiens                     Homo sapiens
14      Homo sapiens                     Homo sapiens
15      Homo sapiens                     Homo sapiens
16      Homo sapiens                     Homo sapiens
17      Homo sapiens                     Homo sapiens
18      Homo sapiens                     Homo sapiens
19      Homo sapiens                     Homo sapiens
20      Homo sapiens                     Homo sapiens
21      Homo sapiens                     Homo sapiens
22      Homo sapiens                     Homo sapiens
23      Homo sapiens                     Homo sapiens
24      Homo sapiens                     Homo sapiens
25      Homo sapiens                     Homo sapiens
26      Homo sapiens                     Homo sapiens
27      Homo sapiens                     Homo sapiens
28      Homo sapiens                     Homo sapiens
29      Homo sapiens                     Homo sapiens
30      Homo sapiens                     Homo sapiens
⋮       ⋮                                ⋮
2804505 Drosophila melanogaster          Drosophila melanogaster
2804506 Drosophila melanogaster          Drosophila melanogaster
2804507 Drosophila melanogaster          Drosophila melanogaster
2804508 Drosophila melanogaster          Drosophila melanogaster
2804509 Drosophila melanogaster          Drosophila melanogaster
2804510 Drosophila melanogaster          Drosophila melanogaster
2804511 Drosophila melanogaster          Drosophila melanogaster
2804512 Drosophila melanogaster          Drosophila melanogaster
2804513 Drosophila melanogaster          Drosophila melanogaster
2804514 Drosophila melanogaster          Drosophila melanogaster
2804515 Drosophila melanogaster          Drosophila melanogaster
2804516 Drosophila melanogaster          Drosophila melanogaster
2804517 Drosophila melanogaster          Drosophila melanogaster
2804518 Drosophila melanogaster          Drosophila melanogaster
2804519 Drosophila melanogaster          Drosophila melanogaster
2804520 Drosophila melanogaster          Drosophila melanogaster
2804521 Drosophila melanogaster          Drosophila melanogaster
2804522 Drosophila melanogaster          Drosophila melanogaster
2804523 Drosophila melanogaster          Drosophila melanogaster
2804524 Drosophila melanogaster          Drosophila melanogaster
2804525 Drosophila melanogaster          Drosophila melanogaster
2804526 Drosophila melanogaster          Drosophila melanogaster
2804527 Drosophila melanogaster          Drosophila melanogaster
2804528 Drosophila melanogaster          Drosophila melanogaster
2804529 Drosophila melanogaster          Drosophila melanogaster
2804530 Drosophila melanogaster          Drosophila melanogaster
2804531 Drosophila melanogaster          Drosophila melanogaster
2804532 Drosophila melanogaster          Drosophila melanogaster
2804533 Drosophila melanogaster          Drosophila melanogaster
2804534 Schizosaccharomyces pombe (972h) Schizosaccharomyces pombe (972h)
        Throughput      Score Modification Experimental.System
1       Low Throughput  -     -            Two-hybrid
2       Low Throughput  -     -            Two-hybrid
3       Low Throughput  -     -            Two-hybrid
4       Low Throughput  -     -            Two-hybrid
5       Low Throughput  -     -            Two-hybrid
6       Low Throughput  -     -            Two-hybrid
7       Low Throughput  -     -            Two-hybrid
8       Low Throughput  -     -            Two-hybrid
9       High Throughput -     -            Two-hybrid
10      Low Throughput  -     -            Two-hybrid
11      Low Throughput  -     -            Two-hybrid
12      Low Throughput  -     -            Two-hybrid
13      Low Throughput  -     -            Two-hybrid
14      Low Throughput  -     -            Two-hybrid
15      Low Throughput  -     -            Two-hybrid
16      Low Throughput  -     -            Two-hybrid
17      Low Throughput  -     -            Two-hybrid
18      High Throughput -     -            Two-hybrid
19      Low Throughput  -     -            Two-hybrid
20      Low Throughput  -     -            Two-hybrid
21      Low Throughput  -     -            Two-hybrid
22      Low Throughput  -     -            Two-hybrid
23      Low Throughput  -     -            Two-hybrid
24      Low Throughput  -     -            Two-hybrid
25      Low Throughput  -     -            Two-hybrid
26      Low Throughput  -     -            Two-hybrid
27      Low Throughput  -     -            Two-hybrid
28      Low Throughput  -     -            Two-hybrid
29      Low Throughput  -     -            Two-hybrid
30      Low Throughput  -     -            Two-hybrid
⋮       ⋮               ⋮     ⋮            ⋮
2804505 High Throughput -     -            Affinity Capture-MS
2804506 High Throughput -     -            Affinity Capture-MS
2804507 High Throughput -     -            Affinity Capture-MS
2804508 High Throughput -     -            Affinity Capture-MS
2804509 High Throughput -     -            Affinity Capture-MS
2804510 High Throughput -     -            Affinity Capture-MS
2804511 High Throughput -     -            Affinity Capture-MS
2804512 High Throughput -     -            Affinity Capture-MS
2804513 High Throughput -     -            Affinity Capture-MS
2804514 High Throughput -     -            Affinity Capture-MS
2804515 High Throughput -     -            Affinity Capture-MS
2804516 High Throughput -     -            Affinity Capture-MS
2804517 High Throughput -     -            Affinity Capture-MS
2804518 High Throughput -     -            Affinity Capture-MS
2804519 High Throughput -     -            Affinity Capture-MS
2804520 High Throughput -     -            Affinity Capture-MS
2804521 High Throughput -     -            Affinity Capture-MS
2804522 High Throughput -     -            Affinity Capture-MS
2804523 High Throughput -     -            Affinity Capture-MS
2804524 High Throughput -     -            Affinity Capture-MS
2804525 High Throughput -     -            Affinity Capture-MS
2804526 High Throughput -     -            Affinity Capture-MS
2804527 High Throughput -     -            Affinity Capture-MS
2804528 High Throughput -     -            Affinity Capture-MS
2804529 High Throughput -     -            Affinity Capture-MS
2804530 High Throughput -     -            Affinity Capture-MS
2804531 High Throughput -     -            Affinity Capture-MS
2804532 Low Throughput  -     -            Affinity Capture-Western
2804533 Low Throughput  -     -            Affinity Capture-Western
2804534 Low Throughput  -     -            Affinity Capture-MS
        Experimental.System.Type Author                  Publication.Source
1       physical                 Marti A (1997)          PUBMED:9006895
2       physical                 Bang ML (2001)          PUBMED:11309420
3       physical                 Wang T (1996)           PUBMED:8599089
4       physical                 Tsuzuki S (2000)        PUBMED:10938104
5       physical                 Kim J (2000)            PUBMED:10875894
6       physical                 Dell'Angelica EC (2000) PUBMED:10747089
7       physical                 Kanoh H (1997)          PUBMED:9038142
8       physical                 Kanoh H (1997)          PUBMED:9038142
9       physical                 Lehner B (2004)         PUBMED:15231747
10      physical                 Zheng P (1998)          PUBMED:9843960
11      physical                 Homayouni R (1999)      PUBMED:10460257
12      physical                 Braganca J (2003)       PUBMED:12586840
13      physical                 Braganca J (2003)       PUBMED:12586840
14      physical                 Bradbury P (1999)       PUBMED:9915855
15      physical                 Bhattacharya M (2002)   PUBMED:12105416
16      physical                 Mancini A (1997)        PUBMED:9380408
17      physical                 Lehner B (2004)         PUBMED:14667819
18      physical                 Lehner B (2004)         PUBMED:15231747
19      physical                 Chen J (1998)           PUBMED:9422766
20      physical                 Dechend R (1999)        PUBMED:10362352
21      physical                 Hu LA (2003)            PUBMED:12724327
22      physical                 Houvras Y (2000)        PUBMED:10945975
23      physical                 Wang Q (2001)           PUBMED:11498787
24      physical                 Wu LC (1996)            PUBMED:8944023
25      physical                 Wang Q (2001)           PUBMED:11498787
26      physical                 Kaufmann U (2000)       PUBMED:11058098
27      physical                 Waters PJ (2001)        PUBMED:11461190
28      physical                 Shinozaki K (1998)      PUBMED:9852298
29      physical                 Ono Y (1998)            PUBMED:9642272
30      physical                 Hirota J (2003)         PUBMED:12611586
⋮       ⋮                        ⋮                       ⋮
2804505 physical                 Chen J (2025)           PUBMED:39657757
2804506 physical                 Chen J (2025)           PUBMED:39657757
2804507 physical                 Chen J (2025)           PUBMED:39657757
2804508 physical                 Chen J (2025)           PUBMED:39657757
2804509 physical                 Chen J (2025)           PUBMED:39657757
2804510 physical                 Chen J (2025)           PUBMED:39657757
2804511 physical                 Chen J (2025)           PUBMED:39657757
2804512 physical                 Chen J (2025)           PUBMED:39657757
2804513 physical                 Chen J (2025)           PUBMED:39657757
2804514 physical                 Chen J (2025)           PUBMED:39657757
2804515 physical                 Chen J (2025)           PUBMED:39657757
2804516 physical                 Chen J (2025)           PUBMED:39657757
2804517 physical                 Chen J (2025)           PUBMED:39657757
2804518 physical                 Chen J (2025)           PUBMED:39657757
2804519 physical                 Chen J (2025)           PUBMED:39657757
2804520 physical                 Chen J (2025)           PUBMED:39657757
2804521 physical                 Chen J (2025)           PUBMED:39657757
2804522 physical                 Chen J (2025)           PUBMED:39657757
2804523 physical                 Chen J (2025)           PUBMED:39657757
2804524 physical                 Chen J (2025)           PUBMED:39657757
2804525 physical                 Chen J (2025)           PUBMED:39657757
2804526 physical                 Chen J (2025)           PUBMED:39657757
2804527 physical                 Chen J (2025)           PUBMED:39657757
2804528 physical                 Chen J (2025)           PUBMED:39657757
2804529 physical                 Chen J (2025)           PUBMED:39657757
2804530 physical                 Chen J (2025)           PUBMED:39657757
2804531 physical                 Chen J (2025)           PUBMED:39657757
2804532 physical                 Chen J (2025)           PUBMED:39657757
2804533 physical                 Chen J (2025)           PUBMED:39657757
2804534 physical                 Tang Z (2012)           PUBMED:22683458
        Qualifications                              Tags
1       -                                           -
2       -                                           -
3       -                                           -
4       -                                           -
5       -                                           -
6       -                                           -
7       -                                           -
8       -                                           -
9       -                                           -
10      -                                           -
11      -                                           -
12      -                                           -
13      -                                           -
14      -                                           -
15      -                                           -
16      -                                           -
17      -                                           -
18      -                                           -
19      -                                           -
20      -                                           -
21      -                                           -
22      -                                           -
23      -                                           -
24      -                                           -
25      -                                           -
26      -                                           -
27      -                                           -
28      -                                           -
29      -                                           -
30      -                                           -
⋮       ⋮                                           ⋮
2804505 -                                           -
2804506 -                                           -
2804507 -                                           -
2804508 -                                           -
2804509 -                                           -
2804510 -                                           -
2804511 -                                           -
2804512 -                                           -
2804513 -                                           -
2804514 -                                           -
2804515 -                                           -
2804516 -                                           -
2804517 -                                           -
2804518 -                                           -
2804519 -                                           -
2804520 -                                           -
2804521 -                                           -
2804522 -                                           -
2804523 -                                           -
2804524 -                                           -
2804525 -                                           -
2804526 -                                           -
2804527 -                                           -
2804528 -                                           -

In [ ]:
# Build PPI network using STRING database
net <- build_ppi_network(
    proteins = NULL, # Use full network
    data_sources = c("STRING", "IntAct"),
    min_confidence = 0.7,
    species = "Homo sapiens",
    string_version = "12"
)



# Summary statistics
cat("Network Summary:\n")
cat("Nodes:", length(igraph::V(net)), "\n")
cat("Edges:", length(igraph::E(net)), "\n")
cat("Average degree:", mean(degree(net)), "\n")

ℹ Loading MPAGE




Warning message:
“Objects listed as exports, but not present in namespace:
• add_custom_proteins
• save_rna_mod_proteins”
Downloading full STRING network for species 9606

STRING DB Network Summary:
Nodes: 16201
Edges: 473860
Average degree: 58.49762

Loading IntAct network from: /workspaces/MPAGE/inst/extdata/intact_processed.rds

IntAct DB Network Summary:
Nodes: 5784
Edges: 21915
Average degree: 7.577801
Network Summary:
Nodes: 16544
Edges: 248963
Average degree: 30.09707

Downloading BioGRID data...

Loading BioGRID data from: /tmp/RtmpNNgF4Q/BIOGRID-ALL-4.4.248.tab3.txt

Warning message in FUN(file, exdir = tmpdir):
“error -1 in extracting from zip file”

ERROR: Error in value[[3L]](cond): Error reading BioGRID file: File is empty: /tmp/RtmpNNgF4Q/BIOGRID-ALL-4.4.248.tab3.txt

In [ ]:
get_string_ppi <- function(species_code, string_version, output_file) {
    tryCatch(
        {
            string_db <- STRINGdb::STRINGdb$new(
                species = species_code,
                version = string_version,
                score_threshold = 0
            )

            # Get full network instead of protein-limited network
            message("Downloading full STRING network for species ", species_code)
            stringdb_proteins <- string_db$get_proteins()
            # Get all interactions for the species above threshold
            all_interactions <- string_db$get_interactions(
                stringdb_proteins$protein_external_id
            )

            if (nrow(all_interactions) == 0) {
                return(NULL)
            }

            # Map interactions to gene symbols
            all_interactions$gene1 <- stringdb_proteins$preferred_name[match(all_interactions$from, stringdb_proteins$protein_external_id)]
            all_interactions$gene2 <- stringdb_proteins$preferred_name[match(all_interactions$to, stringdb_proteins$protein_external_id)]

            # Filter valid interactions
            all_interactions <- all_interactions[!is.na(all_interactions$gene1) & !is.na(all_interactions$gene2), ]

            saveRDS(all_interactions[, c("gene1", "gene2", "combined_score")], output_file)
            return(all_interactions[, c("gene1", "gene2", "combined_score")])
        },
        error = function(e) {
            warning("Error accessing STRING database: ", e$message)
            return(NULL)
        }
    )
}

In [ ]:
interactions <- get_string_ppi(9606, "12", "test.rds")

Downloading full STRING network for species 9606

In [ ]:
species_code <- 9606
string_version <- "12"
sprintf("stringdb_%s_%s.rds", as.character(species_code), string_version)

[1] "stringdb_9606_12.rds"

In [ ]:
interactions[, c("gene1", "gene2", "combined_score")]

         gene1    gene2     combined_score
1        ARF5     RALGPS2   173
2        ARF5     FHDC1     154
3        ARF5     ATP6V1E1  151
4        ARF5     CYTH2     471
5        ARF5     PSD3      201
6        ARF5     TTC9C     180
7        ARF5     SLC2A4    181
8        ARF5     GGA1      594
9        ARF5     RCC1L     154
10       ARF5     UBA52     161
11       ARF5     GOSR2     303
12       ARF5     EPHB1     168
13       ARF5     GORASP2   217
14       ARF5     FYTTD1    155
15       ARF5     MET       347
16       ARF5     TUBA4B    197
17       ARF5     KIF21A    513
18       ARF5     CLTC      322
19       ARF5     DNAJA1    206
20       ARF5     RPGRIP1L  227
21       ARF5     MYL5      153
22       ARF5     EIF2B2    160
23       ARF5     MARS1     164
24       ARF5     PRCC      163
25       ARF5     SYK       174
26       ARF5     PPP2R2A   201
27       ARF5     RAB1B     648
28       ARF5     TRAPPC6A  154
29       ARF5     BTF3      206
30       ARF5     RAB11FIP5 501
⋮        ⋮        ⋮         ⋮
13715375 NFYA     RFX7      218
13715376 GPR139   RFX7      214
13715377 TSNAXIP1 RFX7      199
13715378 ZBTB7B   RFX7      168
13715379 LONP2    RFX7      323
13715380 DYNC2H1  RFX7      187
13715381 ZNF264   RFX7      210
13715382 ZNF354C  RFX7      247
13715383 IFT140   RFX7      293
13715384 DNAAF4   RFX7      304
13715385 KIAA0319 RFX7      235
13715386 HIF3A    RFX7      165
13715387 RFX8     RFX7      606
13715388 RDH10    RFX7      171
13715389 DTX2     RFX7      270
13715390 ZSCAN32  RFX7      173
13715391 VAV3     RFX7      220
13715392 POU1F1   RFX7      152
13715393 ZCRB1    RFX7      394
13715394 BAZ2A    RFX7      163
13715395 CCNO     RFX7      177
13715396 YWHAB    RFX7      237
13715397 INO80D   RFX7      290
13715398 TNRC6C   RFX7      311
13715399 OLFM1    RFX7      327
13715400 MPHOSPH9 RFX7      195
13715401 VCX      RFX7      158
13715402 YPEL2    RFX7      226
13715403 SAMD3    RFX7      169
13715404 ZSCAN9   RFX7      251