In [19]:
# MPAGE Package Testing
# This notebook demonstrates basic functionality of the MPAGE package

# Load the package
devtools::load_all()

ℹ Loading MPAGE
Warning message:
“Objects listed as exports, but not present in namespace:
• add_custom_proteins
• save_rna_mod_proteins”

In [ ]:
df <- data.table::fread("data-raw/core.psimitab", sep = "\t", check.names = TRUE, quote = "", header = FALSE)

In [5]:
df <- data.table::fread("data-raw/BIOGRID-ALL-4.4.248.tab3.txt", sep = "\t", check.names = TRUE, quote = "", header = TRUE)

In [ ]:
df %>% colnames()

 [1] "X.BioGRID.Interaction.ID"           "Entrez.Gene.Interactor.A"
 [3] "Entrez.Gene.Interactor.B"           "BioGRID.ID.Interactor.A"
 [5] "BioGRID.ID.Interactor.B"            "Systematic.Name.Interactor.A"
 [7] "Systematic.Name.Interactor.B"       "Official.Symbol.Interactor.A"
 [9] "Official.Symbol.Interactor.B"       "Synonyms.Interactor.A"
[11] "Synonyms.Interactor.B"              "Experimental.System"
[13] "Experimental.System.Type"           "Author"
[15] "Publication.Source"                 "Organism.ID.Interactor.A"
[17] "Organism.ID.Interactor.B"           "Throughput"
[19] "Score"                              "Modification"
[21] "Qualifications"                     "Tags"
[23] "Source.Database"                    "SWISS.PROT.Accessions.Interactor.A"
[25] "TREMBL.Accessions.Interactor.A"     "REFSEQ.Accessions.Interactor.A"
[27] "SWISS.PROT.Accessions.Interactor.B" "TREMBL.Accessions.Interactor.B"
[29] "REFSEQ.Accessions.Interactor.B"     "Ontology.Term.IDs"
[31] "Ontology.Term.Names"                "Ontology.Term.Categories"
[33] "Ontology.Term.Qualifier.IDs"        "Ontology.Term.Qualifier.Names"
[35] "Ontology.Term.Types"                "Organism.Name.Interactor.A"
[37] "Organism.Name.Interactor.B"

In [25]:
df %>%
    dplyr::select(
        Official.Symbol.Interactor.A, Official.Symbol.Interactor.B,
        Organism.ID.Interactor.A,
        Organism.ID.Interactor.B, Organism.Name.Interactor.A, Organism.Name.Interactor.B, Throughput, Score, Modification,
        Experimental.System,
        Experimental.System.Type,
        Author,
        Publication.Source,
        Organism.ID.Interactor.A,
        Organism.ID.Interactor.B,
        Throughput,
        Score, Qualifications, Tags
    ) %>%
    dplyr::filter(Organism.ID.Interactor.A == Organism.ID.Interactor.B, Organism.ID.Interactor.A %in% c(9606, 10090), Organism.ID.Interactor.B %in% c(9606, 10090)) %>%
    arrange(Score) -> sadf
saveRDS(sadf, "inst/extdata/biogrid_processed.rds")

In [26]:
sadf

        Official.Symbol.Interactor.A Official.Symbol.Interactor.B
1       MAP2K4                       FLNC
2       MYPN                         ACTN2
3       ACVR1                        FNTA
4       GATA2                        PML
5       RPA2                         STAT3
6       ARF1                         GGA3
7       ARF3                         ARFIP2
8       ARF3                         ARFIP1
9       XRN1                         ALDOA
10      APP                          APPBP2
11      APLP1                        DAB1
12      CITED2                       TFAP2A
13      EP300                        TFAP2A
14      APOB                         MTTP
15      ARRB2                        RALGDS
16      CSF1R                        GRB2
17      PRRC2A                       GRB2
18      LSM1                         NARS
19      SLC4A1                       SLC4A1AP
20      BCL3                         BARD1
21      ADRB1                        GIPC1
22      BRCA1                        ATF1
23      BRCA1                        MSH2
24      BRCA1                        BARD1
25      BRCA1                        MSH6
26      ARVCF                        CDH15
27      PCBD1                        CACNA1C
28      PSEN2                        CAPN1
29      CAPN3                        TTN
30      ITPR1                        CA8
⋮       ⋮                            ⋮
1297409 COQ9                         SYNJ2BP
1297410 C2orf47                      C2orf47
1297411 PRSS35                       PRSS35
1297412 COQ9                         RTN4IP1
1297413 PRELID1                      PRELID1
1297414 C7orf55                      C7orf55-LUC7L2
1297415 TRUB2                        TRUB2
1297416 COQ9                         RAB32
1297417 COQ9                         SDR39U1
1297418 HOGA1                        HOGA1
1297419 COQ9                         PTPMT1
1297420 PPM1K                        NME2
1297421 LYRM4                        ISCU
1297422 ADCK4                        ADCK4
1297423 OXCT1                        OXCT1
1297424 PPM1K                        BCKDHB
1297425 CHCHD1                       CHCHD1
1297426 COQ9                         DCAKD
1297427 LYRM4                        LYRM4
1297428 APOOL                        DNAJC11
1297429 HSPA5                        HSP90B1
1297430 DNAJB5                       HSPA2
1297431 DNAJC1                       TOR1AIP1
1297432 HSPA5                        P4HB
1297433 SEC61B                       UGGT1
1297434 FGD5                         MYH14
1297435 DNAJC10                      NUP210
1297436 EBAG9                        GOLGB1
1297437 CD2BP2                       SNRNP40
1297438 EAPP                         SNRNP200
        Organism.ID.Interactor.A Organism.ID.Interactor.B
1       9606                     9606
2       9606                     9606
3       9606                     9606
4       9606                     9606
5       9606                     9606
6       9606                     9606
7       9606                     9606
8       9606                     9606
9       9606                     9606
10      9606                     9606
11      9606                     9606
12      9606                     9606
13      9606                     9606
14      9606                     9606
15      9606                     9606
16      9606                     9606
17      9606                     9606
18      9606                     9606
19      9606                     9606
20      9606                     9606
21      9606                     9606
22      9606                     9606
23      9606                     9606
24      9606                     9606
25      9606                     9606
26      9606                     9606
27      9606                     9606
28      9606                     9606
29      9606                     9606
30      9606                     9606
⋮       ⋮                        ⋮
1297409 9606                     9606
1297410 9606                     9606
1297411 9606                     9606
1297412 9606                     9606
1297413 9606                     9606
1297414 9606                     9606
1297415 9606                     9606
1297416 9606                     9606
1297417 9606                     9606
1297418 9606                     9606
1297419 9606                     9606
1297420 9606                     9606
1297421 9606                     9606
1297422 9606                     9606
1297423 9606                     9606
1297424 9606                     9606
1297425 9606                     9606
1297426 9606                     9606
1297427 9606                     9606
1297428 9606                     9606
1297429 9606                     9606
1297430 9606                     9606
1297431 9606                     9606
1297432 9606                     9606
1297433 9606                     9606
1297434 9606                     9606
1297435 9606                     9606
1297436 9606                     9606
1297437 9606                     9606
1297438 9606                     9606
        Organism.Name.Interactor.A Organism.Name.Interactor.B Throughput
1       Homo sapiens               Homo sapiens               Low Throughput
2       Homo sapiens               Homo sapiens               Low Throughput
3       Homo sapiens               Homo sapiens               Low Throughput
4       Homo sapiens               Homo sapiens               Low Throughput
5       Homo sapiens               Homo sapiens               Low Throughput
6       Homo sapiens               Homo sapiens               Low Throughput
7       Homo sapiens               Homo sapiens               Low Throughput
8       Homo sapiens               Homo sapiens               Low Throughput
9       Homo sapiens               Homo sapiens               High Throughput
10      Homo sapiens               Homo sapiens               Low Throughput
11      Homo sapiens               Homo sapiens               Low Throughput
12      Homo sapiens               Homo sapiens               Low Throughput
13      Homo sapiens               Homo sapiens               Low Throughput
14      Homo sapiens               Homo sapiens               Low Throughput
15      Homo sapiens               Homo sapiens               Low Throughput
16      Homo sapiens               Homo sapiens               Low Throughput
17      Homo sapiens               Homo sapiens               Low Throughput
18      Homo sapiens               Homo sapiens               High Throughput
19      Homo sapiens               Homo sapiens               Low Throughput
20      Homo sapiens               Homo sapiens               Low Throughput
21      Homo sapiens               Homo sapiens               Low Throughput
22      Homo sapiens               Homo sapiens               Low Throughput
23      Homo sapiens               Homo sapiens               Low Throughput
24      Homo sapiens               Homo sapiens               Low Throughput
25      Homo sapiens               Homo sapiens               Low Throughput
26      Homo sapiens               Homo sapiens               Low Throughput
27      Homo sapiens               Homo sapiens               Low Throughput
28      Homo sapiens               Homo sapiens               Low Throughput
29      Homo sapiens               Homo sapiens               Low Throughput
30      Homo sapiens               Homo sapiens               Low Throughput
⋮       ⋮                          ⋮                          ⋮
1297409 Homo sapiens               Homo sapiens               High Throughput
1297410 Homo sapiens               Homo sapiens               High Throughput
1297411 Homo sapiens               Homo sapiens               High Throughput
1297412 Homo sapiens               Homo sapiens               High Throughput
1297413 Homo sapiens               Homo sapiens               High Throughput
1297414 Homo sapiens               Homo sapiens               High Throughput
1297415 Homo sapiens               Homo sapiens               High Throughput
1297416 Homo sapiens               Homo sapiens               High Throughput
1297417 Homo sapiens               Homo sapiens               High Throughput
1297418 Homo sapiens               Homo sapiens               High Throughput
1297419 Homo sapiens               Homo sapiens               High Throughput
1297420 Homo sapiens               Homo sapiens               High Throughput
1297421 Homo sapiens               Homo sapiens               High Throughput
1297422 Homo sapiens               Homo sapiens               High Throughput
1297423 Homo sapiens               Homo sapiens               High Throughput
1297424 Homo sapiens               Homo sapiens               High Throughput
1297425 Homo sapiens               Homo sapiens               High Throughput
1297426 Homo sapiens               Homo sapiens               High Throughput
1297427 Homo sapiens               Homo sapiens               High Throughput
1297428 Homo sapiens               Homo sapiens               High Throughput
1297429 Homo sapiens               Homo sapiens               High Throughput
1297430 Homo sapiens               Homo sapiens               High Throughput
1297431 Homo sapiens               Homo sapiens               High Throughput
1297432 Homo sapiens               Homo sapiens               High Throughput
1297433 Homo sapiens               Homo sapiens               High Throughput
1297434 Homo sapiens               Homo sapiens               High Throughput
1297435 Homo sapiens               Homo sapiens               High Throughput
1297436 Homo sapiens               Homo sapiens               High Throughput
1297437 Homo sapiens               Homo sapiens               High Throughput
1297438 Homo sapiens               Homo sapiens               High Throughput
        Score  Modification Experimental.System Experimental.System.Type
1       -      -            Two-hybrid          physical
2       -      -            Two-hybrid          physical
3       -      -            Two-hybrid          physical
4       -      -            Two-hybrid          physical
5       -      -            Two-hybrid          physical
6       -      -            Two-hybrid          physical
7       -      -            Two-hybrid          physical
8       -      -            Two-hybrid          physical
9       -      -            Two-hybrid          physical
10      -      -            Two-hybrid          physical
11      -      -            Two-hybrid          physical
12      -      -            Two-hybrid          physical
13      -      -            Two-hybrid          physical
14      -      -            Two-hybrid          physical
15      -      -            Two-hybrid          physical
16      -      -            Two-hybrid          physical
17      -      -            Two-hybrid          physical
18      -      -            Two-hybrid          physical
19      -      -            Two-hybrid          physical
20      -      -            Two-hybrid          physical
21      -      -            Two-hybrid          physical
22      -      -            Two-hybrid          physical
23      -      -            Two-hybrid          physical
24      -      -            Two-hybrid          physical
25      -      -            Two-hybrid          physical
26      -      -            Two-hybrid          physical
27      -      -            Two-hybrid          physical
28      -      -            Two-hybrid          physical
29      -      -            Two-hybrid          physical
30      -      -            Two-hybrid          physical
⋮       ⋮      ⋮            ⋮                   ⋮
1297409 99.9   -            Affinity Capture-MS physical
1297410 99.9   -            Affinity Capture-MS physical
1297411 99.9   -            Affinity Capture-MS physical
1297412 99.9   -            Affinity Capture-MS physical
1297413 99.9   -            Affinity Capture-MS physical
1297414 99.9   -            Affinity Capture-MS physical
1297415 99.9   -            Affinity Capture-MS physical
1297416 99.9   -            Affinity Capture-MS physical
1297417 99.9   -            Affinity Capture-MS physical
1297418 99.9   -            Affinity Capture-MS physical
1297419 99.9   -            Affinity Capture-MS physical
1297420 99.9   -            Affinity Capture-MS physical
1297421 99.9   -            Affinity Capture-MS physical
1297422 99.9   -            Affinity Capture-MS physical
1297423 99.9   -            Affinity Capture-MS physical
1297424 99.9   -            Affinity Capture-MS physical
1297425 99.9   -            Affinity Capture-MS physical
1297426 99.9   -            Affinity Capture-MS physical
1297427 99.9   -            Affinity Capture-MS physical
1297428 99.9   -            Affinity Capture-MS physical
1297429 99.92  -            Proximity Label-MS  physical
1297430 990.0  -            Affinity Capture-MS physical
1297431 990.0  -            Proximity Label-MS  physical
1297432 990.0  -            Proximity Label-MS  physical
1297433 990.0  -            Proximity Label-MS  physical
1297434 994.54 -            Affinity Capture-MS physical
1297435 995.0  -            Proximity Label-MS  physical
1297436 995.0  -            Proximity Label-MS  physical
1297437 998.0  -            Affinity Capture-MS physical
1297438 9990.0 -            Affinity Capture-MS physical
        Author                  Publication.Source
1       Marti A (1997)          PUBMED:9006895
2       Bang ML (2001)          PUBMED:11309420
3       Wang T (1996)           PUBMED:8599089
4       Tsuzuki S (2000)        PUBMED:10938104
5       Kim J (2000)            PUBMED:10875894
6       Dell'Angelica EC (2000) PUBMED:10747089
7       Kanoh H (1997)          PUBMED:9038142
8       Kanoh H (1997)          PUBMED:9038142
9       Lehner B (2004)         PUBMED:15231747
10      Zheng P (1998)          PUBMED:9843960
11      Homayouni R (1999)      PUBMED:10460257
12      Braganca J (2003)       PUBMED:12586840
13      Braganca J (2003)       PUBMED:12586840
14      Bradbury P (1999)       PUBMED:9915855
15      Bhattacharya M (2002)   PUBMED:12105416
16      Mancini A (1997)        PUBMED:9380408
17      Lehner B (2004)         PUBMED:14667819
18      Lehner B (2004)         PUBMED:15231747
19      Chen J (1998)           PUBMED:9422766
20      Dechend R (1999)        PUBMED:10362352
21      Hu LA (2003)            PUBMED:12724327
22      Houvras Y (2000)        PUBMED:10945975
23      Wang Q (2001)           PUBMED:11498787
24      Wu LC (1996)            PUBMED:8944023
25      Wang Q (2001)           PUBMED:11498787
26      Kaufmann U (2000)       PUBMED:11058098
27      Waters PJ (2001)        PUBMED:11461190
28      Shinozaki K (1998)      PUBMED:9852298
29      Ono Y (1998)            PUBMED:9642272
30      Hirota J (2003)         PUBMED:12611586
⋮       ⋮                       ⋮
1297409 Floyd BJ (2016)         PUBMED:27499296
1297410 Floyd BJ (2016)         PUBMED:27499296
1297411 Floyd BJ (2016)         PUBMED:27499296
1297412 Floyd BJ (2016)         PUBMED:27499296
1297413 Floyd BJ (2016)         PUBMED:27499296
1297414 Floyd BJ (2016)         PUBMED:27499296
1297415 Floyd BJ (2016)         PUBMED:27499296
1297416 Floyd BJ (2016)         PUBMED:27499296
1297417 Floyd BJ (2016)         PUBMED:27499296
1297418 Floyd BJ (2016)         PUBMED:27499296
1297419 Floyd BJ (2016)         PUBMED:27499296
1297420 Floyd BJ (2016)         PUBMED:27499296
1297421 Floyd BJ (2016)         PUBMED:27499296
1297422 Floyd BJ (2016)         PUBMED:27499296
1297423 Floyd BJ (2016)         PUBMED:27499296
1297424 Floyd BJ (2016)         PUBMED:27499296
1297425 Floyd BJ (2016)         PUBMED:27499296
1297426 Floyd BJ (2016)         PUBMED:27499296
1297427 Floyd BJ (2016)         PUBMED:27499296
1297428 Floyd BJ (2016)         PUBMED:27499296
1297429 Piette BL (2021)        PUBMED:33957083
1297430 Piette BL (2021)        PUBMED:33957083
1297431 Piette BL (2021)        PUBMED:33957083
1297432 Piette BL (2021)        PUBMED:33957083
1297433 Go CD (2021)            PUBMED:34079125
1297434 Li K (2021)             PUBMED:33762435
1297435 Piette BL (2021)        PUBMED:33957083
1297436 Go CD (2021)            PUBMED:34079125
1297437 Cloutier P (2017)       PUBMED:28561026
1297438 Cloutier P (2017)       PUBMED:28561026
        Qualifications
1       -
2       -
3       -
4       -
5       -
6       -
7       -
8       -
9       -
10      -
11      -
12      -
13      -
14      -
15      -
16      -
17      -
18      -
19      -
20      -
21      -
22      -
23      -
24      -
25      -
26      -
27      -
28      -
29      -
30      -
⋮       ⋮
1297409 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297410 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297411 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297412 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297413 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297414 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297415 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297416 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297417 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297418 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297419 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297420 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297421 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297422 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297423 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297424 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297425 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297426 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297427 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297428 The scores represent percentile of the interaction (out of all interactions) based on the CompPASS algorithm.
1297429 BioID|High confidence proximal protein interactions had an average probability of the identified interaction (AvgP) >= 0.98. The associated score represents the fold change of spectral counts (or intensities) for each individual interaction.
1297430 High confidence interactions were identified as having an average probability of the identified interaction (AvgP) >= 0.98. The associated score represents the fold change of spectral counts (or intensities) for each individual interaction.
1297431 BioID|High confidence proximal protein interactions had an average probability of the identified interaction (AvgP) >= 0.98. The associated score represents the fold change of spectral counts (or intensities) for each individual interaction.

In [ ]:
df %>% dplyr::select(
    Official.Symbol.Interactor.A, Official.Symbol.Interactor.B,
    Organism.ID.Interactor.A,
    Organism.ID.Interactor.B, Organism.Name.Interactor.A, Organism.Name.Interactor.B, Throughput, Score, Modification,
    Experimental.System,
    Experimental.System.Type,
    Author,
    Publication.Source,
    Organism.ID.Interactor.A,
    Organism.ID.Interactor.B,
    Throughput,
    Score, Qualifications, Tags
)

        Official.Symbol.Interactor.A Official.Symbol.Interactor.B
1       MAP2K4                       FLNC
2       MYPN                         ACTN2
3       ACVR1                        FNTA
4       GATA2                        PML
5       RPA2                         STAT3
6       ARF1                         GGA3
7       ARF3                         ARFIP2
8       ARF3                         ARFIP1
9       XRN1                         ALDOA
10      APP                          APPBP2
11      APLP1                        DAB1
12      CITED2                       TFAP2A
13      EP300                        TFAP2A
14      APOB                         MTTP
15      ARRB2                        RALGDS
16      CSF1R                        GRB2
17      PRRC2A                       GRB2
18      LSM1                         NARS
19      SLC4A1                       SLC4A1AP
20      BCL3                         BARD1
21      ADRB1                        GIPC1
22      BRCA1                        ATF1
23      BRCA1                        MSH2
24      BRCA1                        BARD1
25      BRCA1                        MSH6
26      ARVCF                        CDH15
27      PCBD1                        CACNA1C
28      PSEN2                        CAPN1
29      CAPN3                        TTN
30      ITPR1                        CA8
⋮       ⋮                            ⋮
2804505 piwi                         RpL28
2804506 piwi                         RpS29
2804507 piwi                         Hsp26
2804508 piwi                         RpL4
2804509 piwi                         betaTub56D
2804510 piwi                         RpS18
2804511 piwi                         Fib
2804512 piwi                         RpL15
2804513 piwi                         apt
2804514 piwi                         RpS6
2804515 piwi                         Spindly
2804516 piwi                         alphaTub84B
2804517 piwi                         RpL13A
2804518 piwi                         NHP2
2804519 piwi                         RpL6
2804520 piwi                         RpL7A
2804521 piwi                         lost
2804522 piwi                         His1:CG33825
2804523 piwi                         CG4038
2804524 piwi                         sesB
2804525 piwi                         RpS9
2804526 piwi                         RpL37A
2804527 piwi                         RpL27
2804528 piwi                         Fmr1
2804529 piwi                         gammaCOP
2804530 piwi                         Imp
2804531 piwi                         RpL17
2804532 Ssrp                         piwi
2804533 piwi                         Ssrp
2804534 dsk1                         pabp
        Organism.ID.Interactor.A Organism.ID.Interactor.B
1       9606                     9606
2       9606                     9606
3       9606                     9606
4       9606                     9606
5       9606                     9606
6       9606                     9606
7       9606                     9606
8       9606                     9606
9       9606                     9606
10      9606                     9606
11      9606                     9606
12      9606                     9606
13      9606                     9606
14      9606                     9606
15      9606                     9606
16      9606                     9606
17      9606                     9606
18      9606                     9606
19      9606                     9606
20      9606                     9606
21      9606                     9606
22      9606                     9606
23      9606                     9606
24      9606                     9606
25      9606                     9606
26      9606                     9606
27      9606                     9606
28      9606                     9606
29      9606                     9606
30      9606                     9606
⋮       ⋮                        ⋮
2804505   7227                     7227
2804506   7227                     7227
2804507   7227                     7227
2804508   7227                     7227
2804509   7227                     7227
2804510   7227                     7227
2804511   7227                     7227
2804512   7227                     7227
2804513   7227                     7227
2804514   7227                     7227
2804515   7227                     7227
2804516   7227                     7227
2804517   7227                     7227
2804518   7227                     7227
2804519   7227                     7227
2804520   7227                     7227
2804521   7227                     7227
2804522   7227                     7227
2804523   7227                     7227
2804524   7227                     7227
2804525   7227                     7227
2804526   7227                     7227
2804527   7227                     7227
2804528   7227                     7227
2804529   7227                     7227
2804530   7227                     7227
2804531   7227                     7227
2804532   7227                     7227
2804533   7227                     7227
2804534 284812                   284812
        Organism.Name.Interactor.A       Organism.Name.Interactor.B
1       Homo sapiens                     Homo sapiens
2       Homo sapiens                     Homo sapiens
3       Homo sapiens                     Homo sapiens
4       Homo sapiens                     Homo sapiens
5       Homo sapiens                     Homo sapiens
6       Homo sapiens                     Homo sapiens
7       Homo sapiens                     Homo sapiens
8       Homo sapiens                     Homo sapiens
9       Homo sapiens                     Homo sapiens
10      Homo sapiens                     Homo sapiens
11      Homo sapiens                     Homo sapiens
12      Homo sapiens                     Homo sapiens
13      Homo sapiens                     Homo sapiens
14      Homo sapiens                     Homo sapiens
15      Homo sapiens                     Homo sapiens
16      Homo sapiens                     Homo sapiens
17      Homo sapiens                     Homo sapiens
18      Homo sapiens                     Homo sapiens
19      Homo sapiens                     Homo sapiens
20      Homo sapiens                     Homo sapiens
21      Homo sapiens                     Homo sapiens
22      Homo sapiens                     Homo sapiens
23      Homo sapiens                     Homo sapiens
24      Homo sapiens                     Homo sapiens
25      Homo sapiens                     Homo sapiens
26      Homo sapiens                     Homo sapiens
27      Homo sapiens                     Homo sapiens
28      Homo sapiens                     Homo sapiens
29      Homo sapiens                     Homo sapiens
30      Homo sapiens                     Homo sapiens
⋮       ⋮                                ⋮
2804505 Drosophila melanogaster          Drosophila melanogaster
2804506 Drosophila melanogaster          Drosophila melanogaster
2804507 Drosophila melanogaster          Drosophila melanogaster
2804508 Drosophila melanogaster          Drosophila melanogaster
2804509 Drosophila melanogaster          Drosophila melanogaster
2804510 Drosophila melanogaster          Drosophila melanogaster
2804511 Drosophila melanogaster          Drosophila melanogaster
2804512 Drosophila melanogaster          Drosophila melanogaster
2804513 Drosophila melanogaster          Drosophila melanogaster
2804514 Drosophila melanogaster          Drosophila melanogaster
2804515 Drosophila melanogaster          Drosophila melanogaster
2804516 Drosophila melanogaster          Drosophila melanogaster
2804517 Drosophila melanogaster          Drosophila melanogaster
2804518 Drosophila melanogaster          Drosophila melanogaster
2804519 Drosophila melanogaster          Drosophila melanogaster
2804520 Drosophila melanogaster          Drosophila melanogaster
2804521 Drosophila melanogaster          Drosophila melanogaster
2804522 Drosophila melanogaster          Drosophila melanogaster
2804523 Drosophila melanogaster          Drosophila melanogaster
2804524 Drosophila melanogaster          Drosophila melanogaster
2804525 Drosophila melanogaster          Drosophila melanogaster
2804526 Drosophila melanogaster          Drosophila melanogaster
2804527 Drosophila melanogaster          Drosophila melanogaster
2804528 Drosophila melanogaster          Drosophila melanogaster
2804529 Drosophila melanogaster          Drosophila melanogaster
2804530 Drosophila melanogaster          Drosophila melanogaster
2804531 Drosophila melanogaster          Drosophila melanogaster
2804532 Drosophila melanogaster          Drosophila melanogaster
2804533 Drosophila melanogaster          Drosophila melanogaster
2804534 Schizosaccharomyces pombe (972h) Schizosaccharomyces pombe (972h)
        Throughput      Score Modification Experimental.System
1       Low Throughput  -     -            Two-hybrid
2       Low Throughput  -     -            Two-hybrid
3       Low Throughput  -     -            Two-hybrid
4       Low Throughput  -     -            Two-hybrid
5       Low Throughput  -     -            Two-hybrid
6       Low Throughput  -     -            Two-hybrid
7       Low Throughput  -     -            Two-hybrid
8       Low Throughput  -     -            Two-hybrid
9       High Throughput -     -            Two-hybrid
10      Low Throughput  -     -            Two-hybrid
11      Low Throughput  -     -            Two-hybrid
12      Low Throughput  -     -            Two-hybrid
13      Low Throughput  -     -            Two-hybrid
14      Low Throughput  -     -            Two-hybrid
15      Low Throughput  -     -            Two-hybrid
16      Low Throughput  -     -            Two-hybrid
17      Low Throughput  -     -            Two-hybrid
18      High Throughput -     -            Two-hybrid
19      Low Throughput  -     -            Two-hybrid
20      Low Throughput  -     -            Two-hybrid
21      Low Throughput  -     -            Two-hybrid
22      Low Throughput  -     -            Two-hybrid
23      Low Throughput  -     -            Two-hybrid
24      Low Throughput  -     -            Two-hybrid
25      Low Throughput  -     -            Two-hybrid
26      Low Throughput  -     -            Two-hybrid
27      Low Throughput  -     -            Two-hybrid
28      Low Throughput  -     -            Two-hybrid
29      Low Throughput  -     -            Two-hybrid
30      Low Throughput  -     -            Two-hybrid
⋮       ⋮               ⋮     ⋮            ⋮
2804505 High Throughput -     -            Affinity Capture-MS
2804506 High Throughput -     -            Affinity Capture-MS
2804507 High Throughput -     -            Affinity Capture-MS
2804508 High Throughput -     -            Affinity Capture-MS
2804509 High Throughput -     -            Affinity Capture-MS
2804510 High Throughput -     -            Affinity Capture-MS
2804511 High Throughput -     -            Affinity Capture-MS
2804512 High Throughput -     -            Affinity Capture-MS
2804513 High Throughput -     -            Affinity Capture-MS
2804514 High Throughput -     -            Affinity Capture-MS
2804515 High Throughput -     -            Affinity Capture-MS
2804516 High Throughput -     -            Affinity Capture-MS
2804517 High Throughput -     -            Affinity Capture-MS
2804518 High Throughput -     -            Affinity Capture-MS
2804519 High Throughput -     -            Affinity Capture-MS
2804520 High Throughput -     -            Affinity Capture-MS
2804521 High Throughput -     -            Affinity Capture-MS
2804522 High Throughput -     -            Affinity Capture-MS
2804523 High Throughput -     -            Affinity Capture-MS
2804524 High Throughput -     -            Affinity Capture-MS
2804525 High Throughput -     -            Affinity Capture-MS
2804526 High Throughput -     -            Affinity Capture-MS
2804527 High Throughput -     -            Affinity Capture-MS
2804528 High Throughput -     -            Affinity Capture-MS
2804529 High Throughput -     -            Affinity Capture-MS
2804530 High Throughput -     -            Affinity Capture-MS
2804531 High Throughput -     -            Affinity Capture-MS
2804532 Low Throughput  -     -            Affinity Capture-Western
2804533 Low Throughput  -     -            Affinity Capture-Western
2804534 Low Throughput  -     -            Affinity Capture-MS
        Experimental.System.Type Author                  Publication.Source
1       physical                 Marti A (1997)          PUBMED:9006895
2       physical                 Bang ML (2001)          PUBMED:11309420
3       physical                 Wang T (1996)           PUBMED:8599089
4       physical                 Tsuzuki S (2000)        PUBMED:10938104
5       physical                 Kim J (2000)            PUBMED:10875894
6       physical                 Dell'Angelica EC (2000) PUBMED:10747089
7       physical                 Kanoh H (1997)          PUBMED:9038142
8       physical                 Kanoh H (1997)          PUBMED:9038142
9       physical                 Lehner B (2004)         PUBMED:15231747
10      physical                 Zheng P (1998)          PUBMED:9843960
11      physical                 Homayouni R (1999)      PUBMED:10460257
12      physical                 Braganca J (2003)       PUBMED:12586840
13      physical                 Braganca J (2003)       PUBMED:12586840
14      physical                 Bradbury P (1999)       PUBMED:9915855
15      physical                 Bhattacharya M (2002)   PUBMED:12105416
16      physical                 Mancini A (1997)        PUBMED:9380408
17      physical                 Lehner B (2004)         PUBMED:14667819
18      physical                 Lehner B (2004)         PUBMED:15231747
19      physical                 Chen J (1998)           PUBMED:9422766
20      physical                 Dechend R (1999)        PUBMED:10362352
21      physical                 Hu LA (2003)            PUBMED:12724327
22      physical                 Houvras Y (2000)        PUBMED:10945975
23      physical                 Wang Q (2001)           PUBMED:11498787
24      physical                 Wu LC (1996)            PUBMED:8944023
25      physical                 Wang Q (2001)           PUBMED:11498787
26      physical                 Kaufmann U (2000)       PUBMED:11058098
27      physical                 Waters PJ (2001)        PUBMED:11461190
28      physical                 Shinozaki K (1998)      PUBMED:9852298
29      physical                 Ono Y (1998)            PUBMED:9642272
30      physical                 Hirota J (2003)         PUBMED:12611586
⋮       ⋮                        ⋮                       ⋮
2804505 physical                 Chen J (2025)           PUBMED:39657757
2804506 physical                 Chen J (2025)           PUBMED:39657757
2804507 physical                 Chen J (2025)           PUBMED:39657757
2804508 physical                 Chen J (2025)           PUBMED:39657757
2804509 physical                 Chen J (2025)           PUBMED:39657757
2804510 physical                 Chen J (2025)           PUBMED:39657757
2804511 physical                 Chen J (2025)           PUBMED:39657757
2804512 physical                 Chen J (2025)           PUBMED:39657757
2804513 physical                 Chen J (2025)           PUBMED:39657757
2804514 physical                 Chen J (2025)           PUBMED:39657757
2804515 physical                 Chen J (2025)           PUBMED:39657757
2804516 physical                 Chen J (2025)           PUBMED:39657757
2804517 physical                 Chen J (2025)           PUBMED:39657757
2804518 physical                 Chen J (2025)           PUBMED:39657757
2804519 physical                 Chen J (2025)           PUBMED:39657757
2804520 physical                 Chen J (2025)           PUBMED:39657757
2804521 physical                 Chen J (2025)           PUBMED:39657757
2804522 physical                 Chen J (2025)           PUBMED:39657757
2804523 physical                 Chen J (2025)           PUBMED:39657757
2804524 physical                 Chen J (2025)           PUBMED:39657757
2804525 physical                 Chen J (2025)           PUBMED:39657757
2804526 physical                 Chen J (2025)           PUBMED:39657757
2804527 physical                 Chen J (2025)           PUBMED:39657757
2804528 physical                 Chen J (2025)           PUBMED:39657757
2804529 physical                 Chen J (2025)           PUBMED:39657757
2804530 physical                 Chen J (2025)           PUBMED:39657757
2804531 physical                 Chen J (2025)           PUBMED:39657757
2804532 physical                 Chen J (2025)           PUBMED:39657757
2804533 physical                 Chen J (2025)           PUBMED:39657757
2804534 physical                 Tang Z (2012)           PUBMED:22683458
        Qualifications                              Tags
1       -                                           -
2       -                                           -
3       -                                           -
4       -                                           -
5       -                                           -
6       -                                           -
7       -                                           -
8       -                                           -
9       -                                           -
10      -                                           -
11      -                                           -
12      -                                           -
13      -                                           -
14      -                                           -
15      -                                           -
16      -                                           -
17      -                                           -
18      -                                           -
19      -                                           -
20      -                                           -
21      -                                           -
22      -                                           -
23      -                                           -
24      -                                           -
25      -                                           -
26      -                                           -
27      -                                           -
28      -                                           -
29      -                                           -
30      -                                           -
⋮       ⋮                                           ⋮
2804505 -                                           -
2804506 -                                           -
2804507 -                                           -
2804508 -                                           -
2804509 -                                           -
2804510 -                                           -
2804511 -                                           -
2804512 -                                           -
2804513 -                                           -
2804514 -                                           -
2804515 -                                           -
2804516 -                                           -
2804517 -                                           -
2804518 -                                           -
2804519 -                                           -
2804520 -                                           -
2804521 -                                           -
2804522 -                                           -
2804523 -                                           -
2804524 -                                           -
2804525 -                                           -
2804526 -                                           -
2804527 -                                           -
2804528 -                                           -

In [ ]:
# Build PPI network using STRING database
net <- build_ppi_network(
    proteins = NULL, # Use full network
    data_sources = c("STRING", "IntAct"),
    min_confidence = 0.7,
    species = "Homo sapiens",
    string_version = "12"
)



# Summary statistics
cat("Network Summary:\n")
cat("Nodes:", length(igraph::V(net)), "\n")
cat("Edges:", length(igraph::E(net)), "\n")
cat("Average degree:", mean(degree(net)), "\n")

ℹ Loading MPAGE




Warning message:
“Objects listed as exports, but not present in namespace:
• add_custom_proteins
• save_rna_mod_proteins”
Downloading full STRING network for species 9606

STRING DB Network Summary:
Nodes: 16201
Edges: 473860
Average degree: 58.49762

Loading IntAct network from: /workspaces/MPAGE/inst/extdata/intact_processed.rds

IntAct DB Network Summary:
Nodes: 5784
Edges: 21915
Average degree: 7.577801
Network Summary:
Nodes: 16544
Edges: 248963
Average degree: 30.09707

Downloading BioGRID data...

Loading BioGRID data from: /tmp/RtmpNNgF4Q/BIOGRID-ALL-4.4.248.tab3.txt

Warning message in FUN(file, exdir = tmpdir):
“error -1 in extracting from zip file”

ERROR: Error in value[[3L]](cond): Error reading BioGRID file: File is empty: /tmp/RtmpNNgF4Q/BIOGRID-ALL-4.4.248.tab3.txt