In [ ]:
# MPAGE Package Testing
# This notebook demonstrates basic functionality of the MPAGE package

# Load the package
devtools::load_all()

# Build PPI network using STRING database
net <- build_ppi_network(
    proteins = NULL,  # Use full network
    data_sources = c("STRING"),
    min_confidence = 0.7,
    species = "Homo sapiens",
    string_version = "12"
)

# Display network information
print(net)

# Summary statistics
cat("Network Summary:\n")
cat("Nodes:", length(V(net)), "\n")
cat("Edges:", length(E(net)), "\n")
cat("Average degree:", mean(degree(net)), "\n")

In [ ]:
net <- build_ppi_network(
    proteins = NULL,
    data_sources = c("STRING"),
    min_confidence = 0.7,
    include_experimental = TRUE,
    exclude_predicted = FALSE,
    species = "Homo sapiens"
)

Downloading full STRING network for species 9606

In [ ]:
net

IGRAPH f55e4a4 UNW- 16201 473860 --
+ attr: name (v/c), weight (e/n), source (e/c)
+ edges from f55e4a4 (vertex names):
 [1] ARF5 --ACAP1     ARF5 --COPA      ARF5 --RAB11FIP3 ARF5 --COPB2
 [5] ARF5 --COPE      ARF5 --ARF3      ARF5 --ARFGAP1   ARF5 --RAB11FIP1
 [9] ARF5 --CYTH1     ARF5 --IQSEC1    ARF5 --RAB11A    ARF5 --ARFGAP2
[13] ARF5 --COPB1     ARF5 --ARF4      ARF5 --ASAP1     ARF5 --RAB11FIP4
[17] ARF5 --GORAB     ARF5 --ACAP2     ARF5 --ARFGAP3   ARF5 --ARFIP1
[21] ARF5 --ARF1      ARF5 --CDKN2A    ARF5 --GBF1      ARF5 --ARFIP2
[25] ARF5 --AGAP1     ARF5 --ASAP2     ARF5 --COPZ1     M6PR --GGA3
[29] M6PR --VTI1A     M6PR --TGOLN2    M6PR --GGA2      M6PR --GGA1
+ ... omitted several edges

In [3]:
string_db <- STRINGdb::STRINGdb$new(
    species = 9606,
    version = "12",
    score_threshold = 0.7 * 1000
)

In [16]:
all_interactions <- string_db$get_interactions(
    string_db$get_proteins()$protein_external_id
)

In [1]:
library(dplyr)
library(stringr)
library(stringi)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
# IntAct Database Preprocessing
# This cell demonstrates processing IntAct PPI data

# Load required libraries
library(dplyr)
library(stringr)
library(data.table)
library(igraph)

# IntAct preprocessing function
preprocess_intact_data <- function(input_file, output_file = NULL, species_filter = c("9606", "10090")) {
    """
    Preprocess IntAct database file for MPAGE package
    
    Args:
        input_file: Path to IntAct TSV file
        output_file: Path to save processed RDS file (optional)
        species_filter: Vector of NCBI taxonomy IDs to filter
    
    Returns:
        Cleaned interaction data frame
    """
    
    message("Loading IntAct data from: ", input_file)
    
    # Read IntAct data
    df <- data.table::fread(input_file, sep = "\t", check.names = TRUE)
    
    message("Processing ", nrow(df), " interactions...")
    
    # Select relevant columns and extract gene names
    processed_data <- df %>%
        dplyr::select(
            Alt..ID.s..interactor.A,
            Alt..ID.s..interactor.B,
            Alias.es..interactor.A,
            Alias.es..interactor.B,
            Taxid.interactor.A,
            Taxid.interactor.B,
            Confidence.value.s.
        ) %>%
        # Extract species information
        dplyr::mutate(
            taxidA = str_extract(Taxid.interactor.A, "taxid:([0-9]+)") %>% str_remove("taxid:"),
            taxidB = str_extract(Taxid.interactor.B, "taxid:([0-9]+)") %>% str_remove("taxid:")
        ) %>%
        # Filter by species
        dplyr::filter(
            taxidA %in% species_filter &
            taxidB %in% species_filter &
            taxidA == taxidB
        ) %>%
        # Extract gene names from aliases
        dplyr::mutate(
            geneA = str_extract(Alias.es..interactor.A, "uniprotkb:[A-Za-z0-9-]+\(gene name\)") %>% 
                   str_remove("uniprotkb:") %>% str_remove("\(gene name\)") %>%
                   str_to_upper(),
            geneB = str_extract(Alias.es..interactor.B, "uniprotkb:[A-Za-z0-9-]+\(gene name\)") %>% 
                   str_remove("uniprotkb:") %>% str_remove("\(gene name\)") %>%
                   str_to_upper(),
            score = str_extract(Confidence.value.s., "intact-miscore:([0-9\\.]+)") %>% 
                   str_remove("intact-miscore:") %>% 
                   as.numeric(),
            taxid = taxidA
        ) %>%
        # Clean and filter
        dplyr::select(geneA, geneB, score, taxid) %>%
        dplyr::filter(!is.na(geneA), !is.na(geneB), !is.na(score)) %>%
        dplyr::distinct() %>%
        dplyr::arrange(desc(score))
    
    # Create summary statistics
    cat("Processing complete:\n")
    cat("Total interactions:", nrow(processed_data), "\n")
    cat("Unique proteins:", length(unique(c(processed_data$geneA, processed_data$geneB))), "\n")
    cat("Species:", paste(unique(processed_data$taxid), collapse = ", "), "\n")
    cat("Score range:", range(processed_data$score, na.rm = TRUE), "\n")
    
    # Save if output file provided
    if (!is.null(output_file)) {
        saveRDS(processed_data, output_file)
        message("Saved processed data to: ", output_file)
    }
    
    return(processed_data)
}

# Test the preprocessing function
input_file <- "/workspaces/MPAGE/data-raw/intact.txt"
output_file <- "/workspaces/MPAGE/data-raw/intact_processed.rds"

if (file.exists(input_file)) {
    intact_data <- preprocess_intact_data(input_file, output_file)
    
    # Display summary
    cat("\n=== IntAct Data Summary ===\n")
    print(intact_data %>% head())
    
    # Species breakdown
    cat("\n=== Species Breakdown ===\n")
    intact_data %>%
        group_by(taxid) %>%
        summarise(interactions = n(), .groups = 'drop') %>%
        print()
    
} else {
    cat("Input file not found: ", input_file)
}

In [ ]:
# MPAGE Package Testing and Validation
# This notebook demonstrates core functionality and validates the package

# Load required libraries
library(dplyr)
library(igraph)
library(ggplot2)

# Load the package
devtools::load_all()

# Test 1: Basic PPI network construction
message("=== Testing PPI Network Construction ===")

# Build full STRING network
net_full <- build_ppi_network(
    proteins = NULL,
    data_sources = c("STRING"),
    min_confidence = 0.7,
    species = "Homo sapiens",
    string_version = "12"
)

# Network summary
cat("Full STRING Network:\n")
cat(sprintf("Nodes: %d\n", length(V(net_full))))
cat(sprintf("Edges: %d\n", length(E(net_full))))
cat(sprintf("Average degree: %.2f\n", mean(degree(net_full))))

# Test 2: RNA modification proteins
message("\n=== Testing RNA Modification Proteins ===")

# Get all m6A proteins
m6a_proteins <- get_rna_mod_proteins(
    modification_types = "m6A",
    use_built_in = TRUE
)

cat("m6A proteins found:", nrow(m6a_proteins), "\n")
print(head(m6a_proteins))

# Test 3: Subnetwork extraction
message("\n=== Testing Subnetwork Extraction ===")

# Extract subnetwork for m6A proteins
m6a_network <- build_ppi_network(
    proteins = unique(m6a_proteins$gene_symbol),
    data_sources = c("STRING"),
    min_confidence = 0.7,
    species = "Homo sapiens"
)

cat("m6A subnetwork:\n")
cat(sprintf("Nodes: %d\n", length(V(m6a_network))))
cat(sprintf("Edges: %d\n", length(E(m6a_network))))

# Test 4: IntAct data processing (if available)
if (file.exists("data-raw/intact.txt")) {
    message("\n=== Testing IntAct Processing ===")
    
    # Process IntAct data
    intact_processed <- preprocess_intact_data(
        input_file = "data-raw/intact.txt",
        species_filter = c("9606", "10090"),
        min_score = 0.3
    )
    
    # Create IntAct network
    intact_net <- load_intact_network(
        processed_file = "data-raw/intact_processed.rds",
        species = "9606",
        min_score = 0.3
    )
    
    cat("IntAct Network:\n")
    cat(sprintf("Nodes: %d\n", length(V(intact_net))))
    cat(sprintf("Edges: %d\n", length(E(intact_net))))
} else {
    message("\n=== Skipping IntAct Tests (data file not found) ===")
}

# Test 5: Module identification
message("\n=== Testing Module Identification ===")

# Identify modules in m6A network
if (length(V(m6a_network)) > 0) {
    modules <- identify_modules(
        ppi_network = m6a_network,
        algorithm = "FASTGREEDY"
    )
    
    cat("Modules found:", length(modules), "\n")
    cat("Module sizes:", sapply(modules, length), "\n")
} else {
    cat("No m6A network found for module identification\n")
}

# Test 6: Performance summary
message("\n=== Performance Summary ===")

# Create summary data frame
summary_df <- data.frame(
    Network = c("Full STRING", "m6A STRING", "IntAct"),
    Nodes = c(length(V(net_full)), length(V(m6a_network)), 
              ifelse(exists("intact_net"), length(V(intact_net)), NA)),
    Edges = c(length(E(net_full)), length(E(m6a_network)), 
              ifelse(exists("intact_net"), length(E(intact_net)), NA)),
    stringsAsFactors = FALSE
)

print(summary_df)

# Test 7: Validation checks
message("\n=== Validation Checks ===")

# Check for missing values
validation_results <- list(
    full_network_valid = !is.null(net_full) && length(V(net_full)) > 0,
    m6a_proteins_valid = nrow(m6a_proteins) > 0,
    m6a_network_valid = !is.null(m6a_network) && length(V(m6a_network)) > 0
)

print(validation_results)

# Save test results
saveRDS(list(
    full_network = net_full,
    m6a_proteins = m6a_proteins,
    m6a_network = m6a_network,
    summary = summary_df,
    validation = validation_results
), "testing_results.rds")

message("\n=== Testing Complete ===")
message("Results saved to testing_results.rds")

In [ ]:
saveRDS(all_interactions, "/workspaces/MPAGE/data-raw/intact_igraph.rds")

In [ ]:
all_interactions %>% head()

  geneA geneB  score taxid
1 SYNJ1 AMPH   0.67  9606
2 SYNJ1 SH3GL1 0.44  9606
3 DNM1  AMPH   0.82  9606
4 DNM1  SH3GL1 0.44  9606
5 DNM2  SH3GL1 0.35  9606
6 DNM2  AMPH   0.71  9606

In [ ]:
all_interactions %>%
    group_by(taxid) %>%
    summarise(n = n())

  taxid n
1 10090  21458
2 9606  595011

In [ ]:
saveRDS(net, "/workspaces/MPAGE/data-raw/intact_igraph.rds")

In [47]:
df %>% dplyr::filter(Confidence.value.s. == "intact-miscore:0.53", str_detect(Alias.es..interactor.B, "PCBP2"))

  X.ID.s..interactor.A ID.s..interactor.B
1 uniprotkb:P11940     uniprotkb:Q15366
2 uniprotkb:Q12771     uniprotkb:Q15366
3 uniprotkb:Q12771     uniprotkb:Q15366
  Alt..ID.s..interactor.A
1 intact:EBI-81531|intact:EBI-28983164|uniprotkb:Q15097|uniprotkb:Q93004|ensembl:ENSP00000313007.5|ensembl:ENSP00000428749.2|ensembl:ENSP00000428840.2|ensembl:ENSP00000429119.2|ensembl:ENSP00000429790.2|ensembl:ENSP00000429892.2|ensembl:ENSP00000430012.2
2 intact:EBI-8609859|intact:MINT-1526261
3 intact:EBI-8609859|intact:MINT-1526261
  Alt..ID.s..interactor.B
1 intact:EBI-945799|uniprotkb:Q6PKG5|intact:EBI-9640573|uniprotkb:Q6IPF4|intact:EBI-2555278|uniprotkb:A8K7X6|uniprotkb:F8VYL7|uniprotkb:Q32Q82|uniprotkb:Q68Y55|uniprotkb:I6L8F9|uniprotkb:Q59HD4|uniprotkb:G3V0E8|uniprotkb:B4DXP5|ensembl:ENSP00000408949.2
2 intact:EBI-945799|uniprotkb:Q6PKG5|intact:EBI-9640573|uniprotkb:Q6IPF4|intact:EBI-2555278|uniprotkb:A8K7X6|uniprotkb:F8VYL7|uniprotkb:Q32Q82|uniprotkb:Q68Y55|uniprotkb:I6L8F9|uniprotkb:Q59HD4|uniprotkb:G3V0E8|uniprotkb:B4DXP5|ensembl:ENSP00000408949.2
3 intact:EBI-945799|uniprotkb:Q6PKG5|intact:EBI-9640573|uniprotkb:Q6IPF4|intact:EBI-2555278|uniprotkb:A8K7X6|uniprotkb:F8VYL7|uniprotkb:Q32Q82|uniprotkb:Q68Y55|uniprotkb:I6L8F9|uniprotkb:Q59HD4|uniprotkb:G3V0E8|uniprotkb:B4DXP5|ensembl:ENSP00000408949.2
  Alias.es..interactor.A
1 psi-mi:pabp1_human(display_long)|uniprotkb:PABPC1(gene name)|psi-mi:PABPC1(display_short)|uniprotkb:PAB1(gene name synonym)|uniprotkb:PABP1(gene name synonym)|uniprotkb:PABPC2(gene name synonym)|uniprotkb:PABP(gene name synonym)
2 psi-mi:q12771_human(display_long)
3 psi-mi:q12771_human(display_long)
  Alias.es..interactor.B
1 psi-mi:pcbp2_human(display_long)|uniprotkb:PCBP2(gene name)|psi-mi:PCBP2(display_short)|uniprotkb:Alpha-CP2(gene name synonym)|uniprotkb:Heterogeneous nuclear ribonucleoprotein E2(gene name synonym)
2 psi-mi:pcbp2_human(display_long)|uniprotkb:PCBP2(gene name)|psi-mi:PCBP2(display_short)|uniprotkb:Alpha-CP2(gene name synonym)|uniprotkb:Heterogeneous nuclear ribonucleoprotein E2(gene name synonym)
3 psi-mi:pcbp2_human(display_long)|uniprotkb:PCBP2(gene name)|psi-mi:PCBP2(display_short)|uniprotkb:Alpha-CP2(gene name synonym)|uniprotkb:Heterogeneous nuclear ribonucleoprotein E2(gene name synonym)
  Interaction.detection.method.s. Publication.1st.author.s.
1 psi-mi:"MI:0096"(pull down)     Wang et al. (1999)
2 psi-mi:"MI:0018"(two hybrid)    Kiledjian et al. (1997)
3 psi-mi:"MI:0096"(pull down)     Kiledjian et al. (1997)
  Publication.Identifier.s.         Taxid.interactor.A
1 pubmed:10373504|mint:MINT-5211576 taxid:9606(human)|taxid:9606(Homo sapiens)
2 mint:MINT-5221578|pubmed:9234743  taxid:9606(human)|taxid:9606(Homo sapiens)
3 mint:MINT-5221578|pubmed:9234743  taxid:9606(human)|taxid:9606(Homo sapiens)
  ⋯ Checksum.s..interactor.A              Checksum.s..interactor.B
1 ⋯ rogid:XudTSPq2h9ckKAc48X88RVafPRU9606 rogid:KWabGhH+pfSX5k0vzs3SXH8Agaw9606
2 ⋯ rogid:wNHcwFLt1g3q5j3DCQ/SW6u05VM9606 rogid:KWabGhH+pfSX5k0vzs3SXH8Agaw9606
3 ⋯ rogid:wNHcwFLt1g3q5j3DCQ/SW6u05VM9606 rogid:KWabGhH+pfSX5k0vzs3SXH8Agaw9606
  Interaction.Checksum.s.                                       Negative
1 intact-crc:7139D82B3D772339|rigid:j5oioWbwKbmgKYXOplV2QD/1WdA FALSE
2 intact-crc:AA7DB477AC2E408B|rigid:7H7szteIW4uF3ThIU5XTXwlvE6w FALSE
3 intact-crc:C93CECC87A14F52E|rigid:7H7szteIW4uF3ThIU5XTXwlvE6w FALSE
  Feature.s..interactor.A Feature.s..interactor.B Stoichiometry.s..interactor.A
1 -                       -                       -
2 tag:?-?(MINT-1526273)   tag:?-?(MINT-1526279)   -
3 -                       -                       -
  Stoichiometry.s..interactor.B
1 -
2 -
3 -
  Identification.method.participant.A
1 psi-mi:"MI:0396"(predetermined participant)
2 psi-mi:"MI:0078"(nucleotide sequence identification)
3 psi-mi:"MI:0396"(predetermined participant)
  Identification.method.participant.B
1 psi-mi:"MI:0396"(predetermined participant)
2 psi-mi:"MI:0078"(nucleotide sequence identification)
3 psi-mi:"MI:0396"(predetermined participant)

In [ ]:
all_interactions %>%
    dplyr::filter(is.na(geneA))

     geneA geneB    score
1    NA    PCBP2    0.53
2    NA    SYNJ1    0.56
3    NA    SNW1     0.44
4    NA    RAD51B   0.56
5    NA    BAX      0.59
6    NA    B2M      0.44
7    NA    B2M      0.88
8    NA    NA       0.86
9    NA    F8       0.44
10   NA    NA       0.88
11   NA    B2M      0.79
12   NA    IGLC1    0.44
13   NA    B2M      0.93
14   NA    NA       0.82
15   NA    MAP3K3   0.40
16   NA    RELA     0.40
17   NA    YWHAG    0.40
18   NA    E2F1     0.40
19   NA    SMURF2   0.37
20   NA    ATF7IP   0.37
21   NA    SMAD4    0.37
22   NA    KAT5     0.37
23   NA    RIF1     0.37
24   NA    TLE1     0.37
25   NA    UNC119   0.37
26   NA    CHD3     0.37
27   NA    VIM      0.37
28   NA    ADAP1    0.37
29   NA    FXYD6    0.37
30   NA    HSPA5    0.37
⋮    ⋮     ⋮        ⋮
7157 NA    NOL7     0.35
7158 NA    SCAF8    0.35
7159 NA    ZC3H4    0.35
7160 NA    PTX3     0.35
7161 NA    MAPKAPK2 0.35
7162 NA    C1D      0.35
7163 NA    XXYLT1   0.35
7164 NA    KCTD12   0.35
7165 NA    CDC123   0.35
7166 NA    MICAL2   0.35
7167 NA    NPC2     0.35
7168 NA    ARMCX2   0.35
7169 NA    UBE2E3   0.28
7170 NA    NFIX     0.28
7171 NA    SPRED2   0.28
7172 NA    RASA1    0.28
7173 NA    LRP6     0.28
7174 NA    RHOU     0.28
7175 NA    SERPINE1 0.28
7176 NA    SHANK2   0.28
7177 NA    MDM2     0.28
7178 NA    SOX11    0.28
7179 NA    SPHK2    0.28
7180 NA    SMURF1   0.54
7181 NA    TMIGD2   0.28
7182 NA    NTF3     0.28
7183 NA    ADAM12   0.28
7184 NA    CCNT2    0.28
7185 NA    USP30    0.28
7186 NA    S100A8   0.28

In [ ]:
string_ids <- unique(c(all_interactions$from, all_interactions$to))
mapped_proteins <- string_db$map(string_ids, "gene", removeUnmapped = TRUE)

ERROR: Error in matrix(NA, length(strColsFrom), nrow(dfToMap)): non-numeric matrix extent

In [ ]:
string_ids

    [1] "9606.ENSP00000000233" "9606.ENSP00000000412" "9606.ENSP00000001008"
    [4] "9606.ENSP00000001146" "9606.ENSP00000002125" "9606.ENSP00000002165"
    [7] "9606.ENSP00000002596" "9606.ENSP00000002829" "9606.ENSP00000003084"
   [10] "9606.ENSP00000003100" "9606.ENSP00000003302" "9606.ENSP00000004531"
   [13] "9606.ENSP00000004982" "9606.ENSP00000005178" "9606.ENSP00000005226"
   [16] "9606.ENSP00000005257" "9606.ENSP00000005260" "9606.ENSP00000005284"
   [19] "9606.ENSP00000005286" "9606.ENSP00000005340" "9606.ENSP00000005386"
   [22] "9606.ENSP00000005587" "9606.ENSP00000006015" "9606.ENSP00000006053"
   [25] "9606.ENSP00000006275" "9606.ENSP00000006526" "9606.ENSP00000006658"
   [28] "9606.ENSP00000007390" "9606.ENSP00000007414" "9606.ENSP00000007699"
   [31] "9606.ENSP00000007735" "9606.ENSP00000008391" "9606.ENSP00000008527"
   [34] "9606.ENSP00000008938" "9606.ENSP00000009041" "9606.ENSP00000009105"
   [37] "9606.ENSP00000009530" "9606.ENSP00000011292" "9606.ENSP00000011473"
   [40] "9606.ENSP00000011619" "9606.ENSP00000011653" "9606.ENSP00000011898"
   [43] "9606.ENSP00000012049" "9606.ENSP00000012443" "9606.ENSP00000013070"
   [46] "9606.ENSP00000013125" "9606.ENSP00000013222" "9606.ENSP00000013807"
   [49] "9606.ENSP00000014914" "9606.ENSP00000014930" "9606.ENSP00000016171"
   [52] "9606.ENSP00000016913" "9606.ENSP00000016946" "9606.ENSP00000017003"
   [55] "9606.ENSP00000019103" "9606.ENSP00000020926" "9606.ENSP00000020945"
   [58] "9606.ENSP00000023064" "9606.ENSP00000023939" "9606.ENSP00000025008"
   [61] "9606.ENSP00000025301" "9606.ENSP00000026218" "9606.ENSP00000027335"
   [64] "9606.ENSP00000029410" "9606.ENSP00000035307" "9606.ENSP00000037243"
   [67] "9606.ENSP00000037502" "9606.ENSP00000039007" "9606.ENSP00000040584"
   [70] "9606.ENSP00000040663" "9606.ENSP00000040738" "9606.ENSP00000040877"
   [73] "9606.ENSP00000043402" "9606.ENSP00000044462" "9606.ENSP00000045083"
   [76] "9606.ENSP00000046087" "9606.ENSP00000046794" "9606.ENSP00000052754"
   [79] "9606.ENSP00000053243" "9606.ENSP00000053468" "9606.ENSP00000053469"
   [82] "9606.ENSP00000053867" "9606.ENSP00000054650" "9606.ENSP00000054666"
   [85] "9606.ENSP00000054668" "9606.ENSP00000054950" "9606.ENSP00000055077"
   [88] "9606.ENSP00000055335" "9606.ENSP00000055682" "9606.ENSP00000056217"
   [91] "9606.ENSP00000056233" "9606.ENSP00000061240" "9606.ENSP00000064724"
   [94] "9606.ENSP00000064778" "9606.ENSP00000064780" "9606.ENSP00000070846"
   [97] "9606.ENSP00000072644" "9606.ENSP00000072869" "9606.ENSP00000074304"
  [100] "9606.ENSP00000075120" "9606.ENSP00000075503" "9606.ENSP00000078429"
  [103] "9606.ENSP00000078445" "9606.ENSP00000080059" "9606.ENSP00000081029"
  [106] "9606.ENSP00000083182" "9606.ENSP00000085068" "9606.ENSP00000085219"
  [109] "9606.ENSP00000086933" "9606.ENSP00000155093" "9606.ENSP00000155840"
  [112] "9606.ENSP00000155858" "9606.ENSP00000155926" "9606.ENSP00000156084"
  [115] "9606.ENSP00000156109" "9606.ENSP00000156471" "9606.ENSP00000156626"
  [118] "9606.ENSP00000157600" "9606.ENSP00000157812" "9606.ENSP00000158762"
  [121] "9606.ENSP00000158771" "9606.ENSP00000159060" "9606.ENSP00000159111"
  [124] "9606.ENSP00000160262" "9606.ENSP00000160373" "9606.ENSP00000160382"
  [127] "9606.ENSP00000160827" "9606.ENSP00000161559" "9606.ENSP00000161863"
  [130] "9606.ENSP00000162391" "9606.ENSP00000162749" "9606.ENSP00000163416"
  [133] "9606.ENSP00000164024" "9606.ENSP00000164133" "9606.ENSP00000164139"
  [136] "9606.ENSP00000164227" "9606.ENSP00000164305" "9606.ENSP00000165524"
  [139] "9606.ENSP00000166139" "9606.ENSP00000166244" "9606.ENSP00000166345"
  [142] "9606.ENSP00000167106" "9606.ENSP00000167586" "9606.ENSP00000167588"
  [145] "9606.ENSP00000168148" "9606.ENSP00000168216" "9606.ENSP00000168712"
  [148] "9606.ENSP00000169298" "9606.ENSP00000169551" "9606.ENSP00000170150"
  [151] "9606.ENSP00000170168" "9606.ENSP00000170447" "9606.ENSP00000170564"
  [154] "9606.ENSP00000171887" "9606.ENSP00000172229" "9606.ENSP00000173229"
  [157] "9606.ENSP00000173527" "9606.ENSP00000173898" "9606.ENSP00000174618"
  [160] "9606.ENSP00000175091" "9606.ENSP00000175756" "9606.ENSP00000176183"
  [163] "9606.ENSP00000176195" "9606.ENSP00000176763" "9606.ENSP00000177694"
  [166] "9606.ENSP00000177742" "9606.ENSP00000178638" "9606.ENSP00000178640"
  [169] "9606.ENSP00000179259" "9606.ENSP00000180166" "9606.ENSP00000180173"
  [172] "9606.ENSP00000181383" "9606.ENSP00000181796" "9606.ENSP00000181839"
  [175] "9606.ENSP00000182290" "9606.ENSP00000182527" "9606.ENSP00000184183"
  [178] "9606.ENSP00000184266" "9606.ENSP00000184956" "9606.ENSP00000185150"
  [181] "9606.ENSP00000185206" "9606.ENSP00000186436" "9606.ENSP00000187762"
  [184] "9606.ENSP00000188312" "9606.ENSP00000188790" "9606.ENSP00000192314"
  [187] "9606.ENSP00000193322" "9606.ENSP00000193391" "9606.ENSP00000194130"
  [190] "9606.ENSP00000194155" "9606.ENSP00000194214" "9606.ENSP00000194530"
  [193] "9606.ENSP00000196061" "9606.ENSP00000196371" "9606.ENSP00000196489"
  [196] "9606.ENSP00000198536" "9606.ENSP00000198767" "9606.ENSP00000198801"
  [199] "9606.ENSP00000199280" "9606.ENSP00000199320" "9606.ENSP00000199389"
  [202] "9606.ENSP00000199447" "9606.ENSP00000199708" "9606.ENSP00000199764"
  [205] "9606.ENSP00000199814" "9606.ENSP00000199936" "9606.ENSP00000200135"
  [208] "9606.ENSP00000200181" "9606.ENSP00000200453" "9606.ENSP00000200457"
  [211] "9606.ENSP00000200557" "9606.ENSP00000200652" "9606.ENSP00000200676"
  [214] "9606.ENSP00000200691" "9606.ENSP00000201031" "9606.ENSP00000201586"
  [217] "9606.ENSP00000201647" "9606.ENSP00000202017" "9606.ENSP00000202556"
  [220] "9606.ENSP00000202625" "9606.ENSP00000202677" "9606.ENSP00000202816"
  [223] "9606.ENSP00000202967" "9606.ENSP00000203001" "9606.ENSP00000203407"
  [226] "9606.ENSP00000203556" "9606.ENSP00000203629" "9606.ENSP00000203630"
  [229] "9606.ENSP00000203664" "9606.ENSP00000204517" "9606.ENSP00000204549"
  [232] "9606.ENSP00000204566" "9606.ENSP00000204604" "9606.ENSP00000204679"
  [235] "9606.ENSP00000204726" "9606.ENSP00000204961" "9606.ENSP00000205061"
  [238] "9606.ENSP00000205143" "9606.ENSP00000205194" "9606.ENSP00000205214"
  [241] "9606.ENSP00000205402" "9606.ENSP00000205557" "9606.ENSP00000205636"
  [244] "9606.ENSP00000205948" "9606.ENSP00000206020" "9606.ENSP00000206262"
  [247] "9606.ENSP00000206423" "9606.ENSP00000206474" "9606.ENSP00000206513"
  [250] "9606.ENSP00000206542" "9606.ENSP00000206595" "9606.ENSP00000206765"
  [253] "9606.ENSP00000207457" "9606.ENSP00000207549" "9606.ENSP00000207870"
  [256] "9606.ENSP00000209668" "9606.ENSP00000209728" "9606.ENSP00000209873"
  [259] "9606.ENSP00000209875" "9606.ENSP00000209884" "9606.ENSP00000209929"
  [262] "9606.ENSP00000210060" "9606.ENSP00000210187" "9606.ENSP00000210313"
  [265] "9606.ENSP00000210444" "9606.ENSP00000210633" "9606.ENSP00000211076"
  [268] "9606.ENSP00000211122" "9606.ENSP00000211287" "9606.ENSP00000211413"
  [271] "9606.ENSP00000211998" "9606.ENSP00000212015" "9606.ENSP00000212355"
  [274] "9606.ENSP00000214869" "9606.ENSP00000215057" "9606.ENSP00000215071"
  [277] "9606.ENSP00000215095" "9606.ENSP00000215368" "9606.ENSP00000215375"
  [280] "9606.ENSP00000215530" "9606.ENSP00000215531" "9606.ENSP00000215565"
  [283] "9606.ENSP00000215567" "9606.ENSP00000215570" "9606.ENSP00000215574"
  [286] "9606.ENSP00000215582" "9606.ENSP00000215631" "9606.ENSP00000215637"
  [289] "9606.ENSP00000215659" "9606.ENSP00000215727" "9606.ENSP00000215730"
  [292] "9606.ENSP00000215742" "9606.ENSP00000215743" "9606.ENSP00000215754"
  [295] "9606.ENSP00000215781" "9606.ENSP00000215793" "9606.ENSP00000215794"
  [298] "9606.ENSP00000215829" "9606.ENSP00000215832" "9606.ENSP00000215838"
  [301] "9606.ENSP00000215855" "9606.ENSP00000215882" "9606.ENSP00000215885"
  [304] "9606.ENSP00000215886" "9606.ENSP00000215904" "9606.ENSP00000215909"
  [307] "9606.ENSP00000215917" "9606.ENSP00000215941" "9606.ENSP00000215957"
  [310] "9606.ENSP00000215980" "9606.ENSP00000216024" "9606.ENSP00000216027"
  [313] "9606.ENSP00000216034" "9606.ENSP00000216036" "9606.ENSP00000216037"
  [316] "9606.ENSP00000216038" "9606.ENSP00000216039" "9606.ENSP00000216044"
  [319] "9606.ENSP00000216068" "9606.ENSP00000216075" "9606.ENSP00000216099"
  [322] "9606.ENSP00000216101" "9606.ENSP00000216106" "9606.ENSP00000216115"
  [325] "9606.ENSP00000216117" "9606.ENSP00000216121" "9606.ENSP00000216122"
  [328] "9606.ENSP00000216124" "9606.ENSP00000216127" "9606.ENSP00000216129"
  [331] "9606.ENSP00000216133" "9606.ENSP00000216139" "9606.ENSP00000216160"
  [334] "9606.ENSP00000216177" "9606.ENSP00000216180" "9606.ENSP00000216181"
  [337] "9606.ENSP00000216185" "9606.ENSP00000216190" "9606.ENSP00000216200"
  [340] "9606.ENSP00000216211" "9606.ENSP00000216218" "9606.ENSP00000216223"
  [343] "9606.ENSP00000216225" "9606.ENSP00000216237" "9606.ENSP00000216252"
  [346] "9606.ENSP00000216254" "9606.ENSP00000216259" "9606.ENSP00000216264"
  [349] "9606.ENSP00000216271" "9606.ENSP00000216274" "9606.ENSP00000216277"
  [352] "9606.ENSP00000216286" "9606.ENSP00000216294" "9606.ENSP00000216297"
  [355] "9606.ENSP00000216330" "9606.ENSP00000216336" "9606.ENSP00000216338"
  [358] "9606.ENSP00000216341" "9606.ENSP00000216361" "9606.ENSP00000216366"
  [361] "9606.ENSP00000216367" "9606.ENSP00000216373" "9606.ENSP00000216392"
  [364] "9606.ENSP00000216410" "9606.ENSP00000216416" "9606.ENSP00000216420"
  [367] "9606.ENSP00000216442" "9606.ENSP00000216446" "9606.ENSP00000216452"
  [370] "9606.ENSP00000216455" "9606.ENSP00000216468" "9606.ENSP00000216479"
  [373] "9606.ENSP00000216484" "9606.ENSP00000216487" "9606.ENSP00000216489"
  [376] "9606.ENSP00000216492" "9606.ENSP00000216513" "9606.ENSP00000216540"
  [379] "9606.ENSP00000216554" "9606.ENSP00000216629" "9606.ENSP00000216639"
  [382] "9606.ENSP00000216714" "9606.ENSP00000216727" "9606.ENSP00000216733"
  [385] "9606.ENSP00000216756" "9606.ENSP00000216780" "9606.ENSP00000216797"
  [388] "9606.ENSP00000216802" "9606.ENSP00000216807" "9606.ENSP00000216832"
  [391] "9606.ENSP00000216862" "9606.ENSP00000216911" "9606.ENSP00000216962"
  [394] "9606.ENSP00000216968" "9606.ENSP00000217026" "9606.ENSP00000217043"
  [397] "9606.ENSP00000217086" "9606.ENSP00000217109" "9606.ENSP00000217121"
  [400] "9606.ENSP00000217131" "9606.ENSP00000217133" "9606.ENSP00000217159"
  [403] "9606.ENSP00000217169" "9606.ENSP00000217173" "9606.ENSP00000217182"
  [406] "9606.ENSP00000217188" "9606.ENSP00000217195" "9606.ENSP00000217244"
  [409] "9606.ENSP00000217246" "9606.ENSP00000217260" "9606.ENSP00000217270"
  [412] "9606.ENSP00000217289" "9606.ENSP00000217372" "9606.ENSP00000217381"
  [415] "9606.ENSP00000217386" "9606.ENSP00000217402" "9606.ENSP00000217407"
  [418] "9606.ENSP00000217420" "9606.ENSP00000217423" "9606.ENSP00000217426"
  [421] "9606.ENSP00000217446" "9606.ENSP00000217455" "9606.ENSP00000217456"
  [424] "9606.ENSP00000217515" "9606.ENSP00000217740" "9606.ENSP00000217901"
  [427] "9606.ENSP00000217909" "9606.ENSP00000217958" "9606.ENSP00000217961"
  [430] "9606.ENSP00000217971" "9606.ENSP00000218004" "9606.ENSP00000218006"
  [433] "9606.ENSP00000218008" "9606.ENSP00000218068" "9606.ENSP00000218075"
  [436] "9606.ENSP00000218089" "9606.ENSP00000218099" "9606.ENSP00000218104"
  [439] "9606.ENSP00000218176" "9606.ENSP00000218230" "9606.ENSP00000218249"
  [442] "9606.ENSP00000218316" "9606.ENSP00000218340" "9606.ENSP00000218348"
  [445] "9606.ENSP00000218388" "9606.ENSP00000218516" "9606.ENSP00000218548"
  [448] "9606.ENSP00000218721" "9606.ENSP00000218758" "9606.ENSP00000218867"
  [451] "9606.ENSP00000219022" "9606.ENSP00000219066" "9606.ENSP00000219069"
  [454] "9606.ENSP00000219070" "9606.ENSP00000219097" "9606.ENSP00000219139"
  [457] "9606.ENSP00000219150" "9606.ENSP00000219162" "9606.ENSP00000219169"
  [460] "9606.ENSP00000219197" "9606.ENSP00000219204" "9606.ENSP00000219207"
  [463] "9606.ENSP00000219235" "9606.ENSP00000219240" "9606.ENSP00000219244"
  [466] "9606.ENSP00000219252" "9606.ENSP00000219255" "9606.ENSP00000219271"
  [469] "9606.ENSP00000219281" "9606.ENSP00000219299" "9606.ENSP00000219302"
  [472] "9606.ENSP00000219313" "9606.ENSP00000219315" "9606.ENSP00000219334"
  [475] "9606.ENSP00000219345" "9606.ENSP00000219368" "9606.ENSP00000219400"
  [478] "9606.ENSP00000219406" "9606.ENSP00000219409" "9606.ENSP00000219431"
  [481] "9606.ENSP00000219439" "9606.ENSP00000219476" "9606.ENSP00000219478"
  [484] "9606.ENSP00000219479" "9606.ENSP00000219481" "9606.ENSP00000219548"
  [487] "9606.ENSP00000219551" "9606.ENSP00000219596" "9606.ENSP00000219599"
  [490] "9606.ENSP00000219611" "9606.ENSP00000219660" "9606.ENSP00000219746"
  [493] "9606.ENSP00000219782" "9606.ENSP00000219789" "9606.ENSP00000219833"
  [496] "9606.ENSP00000219837" "9606.ENSP00000219905" "9606.ENSP00000219919"
  [499] "9606.ENSP00000220003" "9606.ENSP00000220058" "9606.ENSP00000220166"
  [502] "9606.ENSP00000220325" "9606.ENSP00000220420" "9606.ENSP00000220429"
  [505] "9606.ENSP00000220478" "9606.ENSP00000220496" "9606.ENSP00000220507"
  [508] "9606.ENSP00000220509" "9606.ENSP00000220514" "9606.ENSP00000220562"
  [511] "9606.ENSP00000220592" "9606.ENSP00000220597" "9606.ENSP00000220616"
  [514] "9606.ENSP00000220659" "9606.ENSP00000220669" "9606.ENSP00000220751"
  [517] "9606.ENSP00000220764" "9606.ENSP00000220772" "9606.ENSP00000220809"
  [520] "9606.ENSP00000220812" "9606.ENSP00000220822" "9606.ENSP00000220849"
  [523] "9606.ENSP00000220853" "9606.ENSP00000220913" "9606.ENSP00000220966"
  [526] "9606.ENSP00000221086" "9606.ENSP00000221114" "9606.ENSP00000221130"
  [529] "9606.ENSP00000221132" "9606.ENSP00000221138" "9606.ENSP00000221166"
  [532] "9606.ENSP00000221200" "9606.ENSP00000221233" "9606.ENSP00000221265"
  [535] "9606.ENSP00000221307" "9606.ENSP00000221399" "9606.ENSP00000221403"
  [538] "9606.ENSP00000221418" "9606.ENSP00000221419" "9606.ENSP00000221444"
  [541] "9606.ENSP00000221452" "9606.ENSP00000221455" "9606.ENSP00000221459"
  [544] "9606.ENSP00000221462" "9606.ENSP00000221476" "9606.ENSP00000221480"
  [547] "9606.ENSP00000221485" "9606.ENSP00000221486" "9606.ENSP00000221494"
  [550] "9606.ENSP00000221496" "9606.ENSP00000221498" "9606.ENSP00000221515"
  [553] "9606.ENSP00000221538" "9606.ENSP00000221543" "9606.ENSP00000221561"
  [556] "9606.ENSP00000221566" "9606.ENSP00000221573" "9606.ENSP00000221665"
  [559] "9606.ENSP00000221671" "9606.ENSP00000221700" "9606.ENSP00000221742"
  [562] "9606.ENSP00000221797" "9606.ENSP00000221801" "9606.ENSP00000221804"
  [565] "9606.ENSP00000221847" "9606.ENSP00000221855" "9606.ENSP00000221859"
  [568] "9606.ENSP00000221891" "9606.ENSP00000221922" "9606.ENSP00000221930"
  [571] "9606.ENSP00000221957" "9606.ENSP00000221972" "9606.ENSP00000221973"
  [574] "9606.ENSP00000221978" "9606.ENSP00000221980" "9606.ENSP00000221992"
  [577] "9606.ENSP00000221996" "9606.ENSP00000222002" "9606.ENSP00000222005"
  [580] "9606.ENSP00000222008" "9606.ENSP00000222032" "9606.ENSP00000222033"
  [583] "9606.ENSP00000222115" "9606.ENSP00000222120" "9606.ENSP00000222122"
  [586] "9606.ENSP00000222139" "9606.ENSP00000222145" "9606.ENSP00000222219"
  [589] "9606.ENSP00000222224" "9606.ENSP00000222247" "9606.ENSP00000222248"
  [592] "9606.ENSP00000222254" "9606.ENSP00000222256" "9606.ENSP00000222271"
  [595] "9606.ENSP00000222284" "9606.ENSP00000222286" "9606.ENSP00000222305"
  [598] "9606.ENSP00000222329" "9606.ENSP00000222330" "9606.ENSP00000222345"
  [601] "9606.ENSP00000222374" "9606.ENSP00000222381" "9606.ENSP00000222388"
  [604] "9606.ENSP00000222390" "9606.ENSP00000222399" "9606.ENSP00000222402"
  [607] "9606.ENSP00000222462" "9606.ENSP00000222481" "9606.ENSP00000222482"
  [610] "9606.ENSP00000222511" "9606.ENSP00000222543" "9606.ENSP00000222547"
  [613] "9606.ENSP00000222553" "9606.ENSP00000222567" "9606.ENSP00000222573"
  [616] "9606.ENSP00000222574" "9606.ENSP00000222584" "9606.ENSP00000222644"
  [619] "9606.ENSP00000222674" "9606.ENSP00000222693" "9606.ENSP00000222718"
  [622] "9606.ENSP00000222725" "9606.ENSP00000222726" "9606.ENSP00000222728"
  [625] "9606.ENSP00000222747" "9606.ENSP00000222792" "9606.ENSP00000222812"
  [628] "9606.ENSP00000222823" "9606.ENSP00000222968" "9606.ENSP00000222982"
  [631] "9606.ENSP00000222990" "9606.ENSP00000223023" "9606.ENSP00000223026"
  [634] "9606.ENSP00000223029" "9606.ENSP00000223061" "9606.ENSP00000223073"
  [637] "9606.ENSP00000223095" "9606.ENSP00000223114" "9606.ENSP00000223127"
  [640] "9606.ENSP00000223129" "9606.ENSP00000223136" "9606.ENSP00000223145"
  [643] "9606.ENSP00000223167" "9606.ENSP00000223208" "9606.ENSP00000223215"
  [646] "9606.ENSP00000223273" "9606.ENSP00000223293" "9606.ENSP00000223321"
  [649] "9606.ENSP00000223324" "9606.ENSP00000223364" "9606.ENSP00000223366"
  [652] "9606.ENSP00000223369" "9606.ENSP00000223398" "9606.ENSP00000223500"
  [655] "9606.ENSP00000223528" "9606.ENSP00000223641" "9606.ENSP00000223642"
  [658] "9606.ENSP00000223795" "9606.ENSP00000223836" "9606.ENSP00000223862"
  [661] "9606.ENSP00000223864" "9606.ENSP00000224073" "9606.ENSP00000224140"
  [664] "9606.ENSP00000224337" "9606.ENSP00000224356" "9606.ENSP00000224652"
  [667] "9606.ENSP00000224721" "9606.ENSP00000224784" "9606.ENSP00000224862"
  [670] "9606.ENSP00000224950" "9606.ENSP00000225171" "9606.ENSP00000225174"
  [673] "9606.ENSP00000225275" "9606.ENSP00000225276" "9606.ENSP00000225296"
  [676] "9606.ENSP00000225298" "9606.ENSP00000225328" "9606.ENSP00000225371"
  [679] "9606.ENSP00000225387" "9606.ENSP00000225388" "9606.ENSP00000225430"
  [682] "9606.ENSP00000225474" "9606.ENSP00000225504" "9606.ENSP00000225512"
  [685] "9606.ENSP00000225519" "9606.ENSP00000225525" "9606.ENSP00000225538"
  [688] "9606.ENSP00000225576" "9606.ENSP00000225577" "9606.ENSP00000225609"
  [691] "9606.ENSP00000225614" "9606.ENSP00000225655" "9606.ENSP00000225665"
  [694] "9606.ENSP00000225688" "9606.ENSP00000225698" "9606.ENSP00000225719"
  [697] "9606.ENSP00000225724" "9606.ENSP00000225726" "9606.ENSP00000225728"
  [700] "9606.ENSP00000225729" "9606.ENSP00000225737" "9606.ENSP00000225792"
  [703] "9606.ENSP00000225823" "9606.ENSP00000225831" "9606.ENSP00000225842"
  [706] "9606.ENSP00000225844" "9606.ENSP00000225899" "9606.ENSP00000225916"
  [709] "9606.ENSP00000225927" "9606.ENSP00000225929" "9606.ENSP00000225941"
  [712] "9606.ENSP00000225964" "9606.ENSP00000225969" "9606.ENSP00000225983"
  [715] "9606.ENSP00000226004" "9606.ENSP00000226021" "9606.ENSP00000226067"
  [718] "9606.ENSP00000226091" "9606.ENSP00000226105" "9606.ENSP00000226193"
  [721] "9606.ENSP00000226207" "9606.ENSP00000226218" "9606.ENSP00000226225"
  [724] "9606.ENSP00000226230" "9606.ENSP00000226247" "9606.ENSP00000226279"
  [727] "9606.ENSP00000226284" "9606.ENSP00000226299" "9606.ENSP00000226317"
  [730] "9606.ENSP00000226319" "9606.ENSP00000226355" "9606.ENSP00000226382"
  [733] "9606.ENSP00000226413" "9606.ENSP00000226444" "9606.ENSP00000226524"
  [736] "9606.ENSP00000226574" "9606.ENSP00000226730" "9606.ENSP00000226760"
  [739] "9606.ENSP00000226796" "9606.ENSP00000226798" "9606.ENSP00000226951"
  [742] "9606.ENSP00000227155" "9606.ENSP00000227163" "9606.ENSP00000227266"
  [745] "9606.ENSP00000227322" "9606.ENSP00000227348" "9606.ENSP00000227451"
  [748] "9606.ENSP00000227471" "9606.ENSP00000227474" "9606.ENSP00000227507"
  [751] "9606.ENSP00000227520" "9606.ENSP00000227524" "9606.ENSP00000227525"
  [754] "9606.ENSP00000227638" "9606.ENSP00000227667" "9606.ENSP00000227752"
  [757] "9606.ENSP00000227756" "9606.ENSP00000227868" "9606.ENSP00000227880"
  [760] "9606.ENSP00000227918" "9606.ENSP00000228027" "9606.ENSP00000228136"
  [763] "9606.ENSP00000228251" "9606.ENSP00000228318" "9606.ENSP00000228347"
  [766] "9606.ENSP00000228434" "9606.ENSP00000228437" "9606.ENSP00000228438"
  [769] "9606.ENSP00000228463" "9606.ENSP00000228468" "9606.ENSP00000228476"
  [772] "9606.ENSP00000228495" "9606.ENSP00000228506" "9606.ENSP00000228510"
  [775] "9606.ENSP00000228515" "9606.ENSP00000228534" "9606.ENSP00000228567"